xml/vt_docker_quick.xml

- see http://doccomments.provo.novell.com/comments/28724

fixed user comment

---

xml/vt_best_practices.xml

aspell check

---

xml/vt_docker_quick.xml

Introduce the Docker registry and Portus.
Please read it carefully, my spell checked didn't work against this xml document. Plus I'm not able to render it.
People interested:  @eotchi, @mssola and @taroth21

Update the Docker quickstart guide

---

xml/vt_best_practices.xml

Add filesystem sharing chapter; move most of chapter to section 1; add more external ref; add entropy chapter;

filesystem sharing, entropy, moving everything to sect1

---

xml/vt_best_practices.xml

Here are is a commit fixing a few errors + one adding a section about spice default listen address

Misc fixes

---

xml/vt_best_practices.xml

virt-sandbox, though in technology preview brings a lot of interesting
features in the virtualization world. Documenting it in the best
practices would help advertising them.

vt best practices: add a subsection on virt-sandbox

---

xml/vt_best_practices.xml

Improve the grammar and wording of text in sections 1-3.

vt-best-practices: general grammar fixes

---

xml/vt_best_practices.xml

Minor improvements to the "I/O in Virtualization" section of VT
best practices doc.

vt-best-practices: Improvements for Section 4

---

xml/vt_best_practices.xml

Various improvements to wording and grammer in Section 5.1.

vt-best-practices: Improvements for Memory and Pages section

---

xml/vt_best_practices.xml

Improve section 5.2, KSM and Page Sharing. Add a warning about
page sharing across NUMA nodes.

vt-best-practices: Improve section on KSM

---

xml/vt_best_practices.xml

Add examples of workloads that benefit from THP, and those that
may perform poorly.

vt-best-practices: Improve THP content

---

xml/art_sle_amazon_ecs.xml

- Document the use of the SUSE provided pre-built docker images

- More details about the integration with Amazon ecs.

---

xml/vt_docker_quick.xml

Extended the doc. Also fixed the indentation of the surrouning area.
Ping @eotchi, @taroth21 and @jordimassaguerpla

Updated the Docker quickstart to cover the limitations of Power

---

xml/vt_docker_quick.xml

Explain how to add the Containers Module without using YaST.
This can be really useful for people scripting stuff.
Ping @eotchi and @taroth21

Docker quickstart: non interactive installation

---

xml/ay_bigfile.xml

Firewall documentation is quite complete. dns-server and dhcp-server are in a minimum-effort basis (documented by examples) since they have way too many options.

dns-server, dhcp-server and firewall sections

---

xml/vt_docker_quick.xml

add explanation of version incompatibilities between docker and
docker registry
Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>

fix bsc#976420

---

xml/ay_bigfile.xml

This PR documents importing SSH keys and server configuration.
Thanks!

Add documentation about importing SSH keys/configuration

---

xml/adm_sudo.xml
xml/book_sle_admin.xml
xml/entity-decl.ent

I don't expect any less than 20 complaints and corrections!

Add chapter about sudo to admin guide

---

xml/ay_bigfile.xml

Related to [bsc#984146](https://bugzilla.suse.com/show_bug.cgi?id=984146).

Add explanation about keep_install_network default value

---

xml/tuning_utilities_dstat.xml

It's CSV not CVS :-)
Also the 'that' sounds not right here, I am not sure whether 'which' is
the best solution though.

Fix typo and use other wording

---

xml/ay_bigfile.xml

- bsc#990116
- I've added more examples and explained the usage of <ask> directive, especially the case with lists of items

Added more verbose examples for AutoYast <ask>

---

xml/ay_bigfile.xml

I've added a tip about signatures-handling during installer self-update.

Add signatures-handling self-update tip

---

xml/ay_bigfile.xml
xml/inst_yast2.xml

Updates from code review PR#69

---

xml/security_ssh.xml

(which is usually the most up-to-date one, since it may be updated most
often)

Add reference to in-package documentation

---

xml/net_proxy.xml

fix for https://bugzilla.opensuse.org/show_bug.cgi?id=1011014

---

xml/deployment_docupdates.xml
xml/deployment_prep_zseries_info_i.xml

@fsundermeyer Can you take a look and see if this looks fine-ish? (I preemptively closed the bug. Also consulted Ihno who was fine with at least my release notes entry.)

z Systems: Add information about susehmc.ins (bsc#1009081)

---

xml/kgraft.xml

As this is my first sect1, feedback and comments are very welcome.

Life patching lifecycle, https://fate.suse.com/322049

---

xml/hardening.xml

* Fixed typos and restructured some sentences
* Added information about wiping files / wear leveling
* unified prompt style by using prompt entity
* Fixed information about ASLR and NX bit
* Fixed deprecated SSH examples
* Added changelog section

Updated Hardening Guide

---

xml/deployment_prep_zseries.xml
xml/sle_update_upgrading.xml

Upgrading on z not required in SLED

Profiling for upgrading zSystems

---

xml/deployment_docupdates.xml
xml/sle_update_background.xml

SCC created a page for life cycles of modules. Link added to deployment guide.

added link to SLES modules life cycles, bsc#1014266

---

xml/deployment_docupdates.xml
xml/yast2_sw_addon.xml

Note about Modules Life Cycles in Installing Add-ons and Extensions

---

xml/inst_yast2.xml

bsc#1010297 and bsc#1012335#c28

system mount points for FCoE and iSCSI in deployment guide

---

xml/storage_docupdates.xml
xml/storage_multipath.xml

* replaced IDE with SATA
* added warning about regex in multipath.conf

Added Warning about Regular Expressions in multipath.conf

---

xml/ay_bigfile.xml

Replaces https://github.com/SUSE/doc-sle/pull/103 (I deleted my own repository without noticing that a PR was still open). It contains changes suggested by @fsundermeyer.

 Add AutoYaST self_update element

---

xml/ay_bigfile.xml
xml/ay_docupdates.xml

Improve usage description of extensions and add a docupdates entry; bsc#1007513

Improve usage description of extensions; bsc#1007513

---

xml/book_sle_admin.xml
xml/yast2_gui.xml
xml/yast2_ncurses.xml

advanced hotkeys in yast2, bsc#1010039

---

xml/ay_bigfile.xml

- Found while reading docu at https://www.suse.com/documentation/sles-12/singlehtml/book_autoyast/book_autoyast.html#CreateProfile.Register
- Section 4.3 System Registration and Extension Selection

Finishing the setup_before_proposal tag

---

xml/security_firewall.xml

No zone assigned = External Zone

Fix bsc#989145

---

xml/ay_bigfile.xml

Here are the patches I sent you earlier by mail as PR. I guess this is easier to apply.

Feature/ay reorg bsc#1033550

---

xml/ay_bigfile.xml

* This reverts commit e48bef17a4841ab2261b7ccc14d4964e949d37ef.
* This feature is not available in SP2 but in SP3.
* See [bsc#1045972](https://bugzilla.suse.com/show_bug.cgi?id=1045972) for more details.

Remove btrfs default subvol

---

xml/opensuse_update.xml

https://bugzilla.suse.com/show_bug.cgi?id=1045370

Add link to online release notes

---

xml/ay_bigfile.xml

Documentation of product selection in AY profile. 

---

.dockerignore
.travis.yml
Dockerfile

* Get docker image from susedoc org on docker hub
* find DC-*-all files and run daps validate

Use Docker with Travis CI

---

xml/book_sle_deployment.xml
xml/deployment_image.xml
xml/deployment_intro.xml
xml/deployment_prep_aarch64_workflow.xml
xml/deployment_prep_x86_workflow.xml

Add chapter Cloning Disk Images

---

xml/art_opensuse_install_quick.xml
xml/art_sle_install_quick.xml
xml/ay_bigfile.xml
xml/book_opensuse_startup.xml
xml/book_sle_deployment.xml
xml/deployment_bootoptions.xml
xml/deployment_docupdates.xml
xml/deployment_installserver.xml
xml/deployment_prep_aarch64_makeavail.xml
xml/deployment_prep_aarch64_workflow.xml
xml/deployment_prep_power_preparing.xml
xml/deployment_prep_x86_makeavail.xml
xml/deployment_prep_x86_workflow.xml
xml/deployment_remote.xml
xml/inst_yast2.xml
xml/opensuse_update.xml
xml/sle_update_offline.xml
xml/smt_mirroring.xml
xml/troubleshooting.xml
xml/tuning_systemresources.xml
xml/yast2_sw_repo.xml

Move installation boot options from YaST install to
separate chapter.

Move install boot options

---

xml/ay_bigfile.xml
xml/system_repair.xml

This PR includes the changes from #186 and adds some style fixes.

Update AutoYaST addons documentation

---

xml/deployment_bootoptions.xml

Removed "non-inbox" from warning and restructured the text.

Reword Secure Boot SolidDriver warning 

---

xml/inst_yast2.xml
xml/storage_lvm.xml

No raid or LVM for /boot on z

---

xml/hardening.xml

Same as #194 with 2 minor fixes.

 Reworked and extended section "Securing the Network—Open Network Ports Detection"

---

xml/ay_bigfile.xml

Small updates to AutoYaST documentation for SLE/openSUSE 15.

AutoYaST SLE 15 documentation updates

---

xml/book_sle_deployment.xml
xml/deployment_kernelupdate.xml
xml/entity-decl.ent

* Allows installation on current hardware

Add chapter about kISO

---

xml/art_opensuse_install_quick.xml
xml/art_sle_install_quick.xml
xml/inst_yast2.xml
xml/lvm.xml
xml/raid.xml
xml/storage_iscsi-lio.xml
xml/storage_iscsi.xml
xml/storage_lvm.xml
xml/storage_planning.xml
xml/storage_raid.xml
xml/storage_raid10.xml
xml/yast2_manpart.xml

* do not explain partitions
* limited scope of partition tables section

Reworked YaST partitioner

---

xml/deployment_prep_aarch64_nsysreqs.xml

Change Hardware for ARM AArch64

---

xml/hardening.xml

hardening guide: reworked ftp/telnet/rsh section

---

xml/hardening.xml

- added information about security related mount options
- minor grammatical changes

hardening guide: reworked partition section

---

xml/hardening.xml

- recommendation about encryption
- comparing backups for integrity

hardening guide: reworked backup section

---

xml/entity-decl.ent
xml/hardening.xml

- replaced SuSEfirewall2 reference by firewalld reference for SLE-15
- added nftables reference which will be available in SLE-15 as well.

hardening guide: reworked firewall section

---

xml/art_opensuse_install_quick.xml
xml/art_sle_install_quick.xml
xml/ay_bigfile.xml
xml/deployment_bootoptions.xml
xml/deployment_docupdates.xml
xml/deployment_installserver.xml
xml/deployment_prep_boot.xml
xml/deployment_prep_power_preparing.xml
xml/deployment_remote.xml
xml/deployment_xpointer.xml
xml/inst_yast2.xml
xml/opensuse_update.xml
xml/sle_update_offline.xml
xml/smt_mirroring.xml
xml/troubleshooting.xml
xml/tuning_systemresources.xml
xml/yast2_sw_repo.xml

* Updates to YaST section to include remote installation

Update Remote Installation Chapter

---

xml/ay_bigfile.xml

Replace AY SuSEFirewall2 config by Firewalld

---

xml/sle_update_offline.xml

Minor additions to PR #240.
Thank you, @lslezak

SLE15 Offline Upgrade

---

xml/yast2_sw_addon.xml

Try base product registration code first, https://github.com/yast/yast-registration/pull/352
I am not sure if it makes sense to document such a detail. Feel free to reject it, if it does not fit.

Document the fix to bsc#1075551

---

xml/security_firewall.xml

Firewall rpcbind based protocols

---

xml/sle_update_online.xml

* Add procedure for online migration with zypper
* FATE#323505

Add 'Migrate from openSUSE Leap to SLE'

---

xml/ay_bigfile.xml

We are dropping support for such a feature.

Drop support to read an existing mount table

---

xml/opensuse_reference_intro.xml
xml/sle_update_background.xml
xml/sle_update_backporting.xml
xml/sle_update_offline.xml
xml/sle_update_online.xml
xml/sle_update_preparation.xml

* Fix XML ID prefixes
* Split long sentences
* Replace uncommon words

Change 'Upgrade Guide', stylecheck

---

xml/storage_nvmeof.xml

* Change intro sentence for external links
Cherry-pick changes to maintenance/SLE12SP3 branch after squash merge.

[WIP] Change 'NVMe over Fabric'

---

xml/ay_bigfile.xml

Add note about AutoYaST linuxrc rootpassword

---

xml/ay_bigfile.xml
xml/entity-decl.ent

@fsundermeyer + AutoYaST team: please review
(proposed name change to be consistent with other SLES books)

book 'AutoYaST' to 'AutoYaST Guide'

---

xml/deployment_yast_installer.xml

* FATE#322180
* Btrfs supported for data volumes

Change Deployment Guide Partitioning

---

xml/deployment_remote.xml

As discussed in https://bugzilla.suse.com/show_bug.cgi?id=1078785

VNC via the browser is not encrypted

---

xml/ay_12_migrate_15.xml

Note added by @imobachgs (see https://github.com/yast/yast-autoinstallation/pull/424)

Add a note about partition_type in the profile changes document

---

xml/ay_12_migrate_15.xml

Update AutoYaST Upgrade section:
- The current documentation has been moved to a new "Software" section
- Added new "Registration" section

Added registration upgrade section

---

xml/hardening.xml

* Remove parts
* Clarify headlines
* Change XML IDs
* Remove link to old AppArmor documentation

Update 'Hardening Guide'

---

xml/docker_installation.xml

Add a section mentioning the update policy and recommendations regarding
Docker in the Containers Module.
Signed-off-by: Valentin Rothberg <vrothberg@suse.com>

dockerquick: add section for updates

---

xml/apparmor_profiles.xml

See
* https://features.opensuse.org/323500
* https://bugzilla.opensuse.org/show_bug.cgi?id=1081212
Source
* man 5 apparmor

Add new AppArmor rules

---

xml/64bit_issues.xml
xml/adm_shell.xml
xml/adm_support.xml
xml/apache2.xml
xml/bootconcept.xml
xml/chrony.xml
xml/entity-decl.ent
xml/grub2.xml
xml/grub2_yast_i.xml
xml/kgraft.xml
xml/net_basic.xml
xml/net_dns.xml
xml/net_nfs.xml
xml/net_proxy.xml
xml/net_samba.xml
xml/net_sync.xml
xml/net_teaming.xml
xml/net_wicked.xml
xml/nm.xml
xml/powermanagement.xml
xml/rpm.xml
xml/sle_admin_intro.xml
xml/systemd.xml
xml/update-alternatives.xml
xml/vnc.xml
xml/x11.xml
xml/x11_fonts.xml
xml/yast2_ncurses.xml
xml/yast2_you.xml
xml/zypper.xml

[WiP] Proofing fixes SLE 15 GA

---

xml/ay_12_migrate_15.xml
xml/ay_bigfile.xml

Update Btrfs subvolumes documentation in AutoYaST (related to bsc#1076337, bsc#1090095 and bsc#1091669).

Update subvolumes documentation

---

xml/libvirt_guest_installation.xml

Add virt-install location paramter

---

xml/libvirt_guest_installation.xml
xml/vt_installation.xml

Add OVMF to virt-install

---

xml/security_pcidss.xml

Replace SUSEFirewall2 with firewalld

---

xml/rmt_client.xml
xml/rmt_config_files.xml
xml/rmt_migrate_from_smt.xml
xml/rmt_mirroring.xml
xml/rmt_overview.xml
xml/rmt_scripts.xml

RMT Guide Review / Bugfixes

---

xml/art_sle_amazon_ecs.xml
xml/book_sles_docker.xml
xml/common_docupdates_sp2_i.xml
xml/docker_building_images.xml
xml/docker_containers.xml
xml/docker_dockerizing_application.xml
xml/docker_installation.xml
xml/docker_overview.xml
xml/docker_registry.xml
xml/lxc.xml
xml/security_pcidss.xml
xml/sle_update_background.xml
xml/yast2_sw_addon.xml

Use Apache2 Web server, completely rewrite section

Fix bsc#1084275 to create a better example (for SLE12SP3)

---

xml/art_sle_install_quick.xml
xml/art_sle_modules_quick.xml
xml/deployment_yast_installer.xml
xml/docker_overview.xml
xml/hardening.xml
xml/sle_update_background.xml
xml/upgrade_intro.xml
xml/vt_tools.xml
xml/yast2_sw_addon.xml
xml/zypper.xml

Add link to https://www.suse.com/lifecycle

Fix bsc#1104673 about lifecycle

---

xml/docker_dockerizing_application.xml
xml/docker_docupdates.xml

This PR contains the following changes:
* Fix bsc#1105887 to create a better example
* Add docupdate for bsc#1105887

Add better Docker example for bsc1105887

---

xml/storage_docupdates.xml
xml/storage_multipath.xml

This PR contains the following changes:
* Clarify sentence according to [bsc#1067789](https://bugzilla.suse.com/show_bug.cgi?id=1067789)
* Mention it in docupdate section

Mention how to create config file for multipath (bsc#1067789)

---

xml/ay_bigfile.xml

Continues #331 with minor amendments.

Add partition_type description

---

xml/journalctl.xml

Hi,
I made very minor changes to this file. I checked all of the instructions, and they worked for me. The original author wrote this article well; it needed very little editing.
-Brandon

Very minor changes to journalctl.xml

---

xml/64bit_issues.xml
xml/aarch64_inst_problem.xml

Hi,
these files have been changed per suggestions by @cwickert and @dmpop .
Thanks,
Brandon

Changes Suggested by the Team

---

xml/rmt_certificates.xml

Minor change, no addition to Doc Updates

Fix screen indentation in RMT Guide

---

.github/PULL_REQUEST_TEMPLATE.md

This updates the Github Pull Request template with a more descriptive text.
Check all of the items below.

Update text for PR checks

---

xml/admin_docupdates.xml

fixed typo in Admin Guide docupdates

---

xml/admin_docupdates.xml
xml/ay_bigfile.xml
xml/ay_docupdates.xml
xml/book_gnomeuser.xml
xml/book_security.xml
xml/book_sle_admin.xml
xml/book_sle_deployment.xml
xml/book_sle_tuning.xml
xml/book_sle_upgrade.xml
xml/book_sle_virtualization.xml
xml/book_sles_docker.xml
xml/book_sles_storage.xml
xml/deployment_docupdates.xml
xml/docker_docupdates.xml
xml/gnome_docupdates.xml
xml/security_docupdates.xml
xml/storage_docupdates.xml
xml/tuning_docupdates.xml
xml/upgrade_docupdates.xml
xml/virt_docupdates.xml

disable docupdate appendices, added comments

---

xml/ay_bigfile.xml

Up to now the host section has not been described
- [x ] To maintenance/SLE15SP0

added host section

---

xml/libvirt_managing.xml

Add information for external snapshots
- [Y] To maintenance/SLE12SP3
- [Y] To maintenance/SLE12SP4
- [Y] To maintenance/SLE15SP0

Add information for external snapshots (bsc#1125660)

---

xml/ay_bigfile.xml

*Are backports required?*    NO

user btrfs subvolume

---

xml/art_sle_modules_quick.xml
xml/yast2_sw.xml

Implement Fate#320573: [POST-GM] [R] Add 'services' view to yast2 sw_single

mention services view in yast sw_single

---

xml/net_samba.xml

The samba.conf setting is of course a server setting

---

xml/ay_bigfile.xml

It updates AutoYaST configuration management documentation that was
pretty incomplete (fate#322722).

AutoYaST configuration management update

---

xml/art_sle_install_quick.xml
xml/ay_12_migrate_15.xml
xml/deployment_yast_installer.xml
xml/entity-decl.ent

Packages DVD or Packages ISO needs to be renamed to "Packages Image". References to burning it to DVD need to be removed.

[WIP] Packages image does not fit on DVD (bsc#1126857)

---

xml/book_sle_klp.xml
xml/klp.xml

Not sure whether this option for the title... It is also not completely sure whether we actually still need this as a separate guide.

An attempt at making KLP Guide name a little less circular

---

xml/sle_update_preparation.xml

Merged applicable changes from maintenance/SLE12SP4,
based on https://github.com/SUSE/doc-sle/commit/07d3b5db773f188758bb342c14516b596705284d.
Will double-check with Reinhard before merging.

Upgrade Guide: PostgresQL preps

---

xml/klp.xml

Fixes error introduced to https://github.com/SUSE/doc-sle/pull/424/. This PR is a reminder to complete unfinished tasks, and for reviewers to make changes if necessary.
- [ X] To maintenance/SLE15SP0

Restore updated chapter title

---

images/src/svg/new-maintenance-model+ltss.svg

Update maintenance model image with upgrade info from kdupke

---

xml/sle_update_online.xml

Fix for
https://bugzilla.suse.com/show_bug.cgi?id=1132855
See https://w3.suse.de/~fs/doku/SLE_15_SP1/sec.upgrade-online.zypper-plain_color_en.pdf for a PDF build

Fixed section "Upgrading with Plain Zypper"

---

xml/book_sle_admin.xml
xml/transactional_updates.xml

https://jira.suse.com/browse/SLE-4315

[WIP] new transactional-update chapter

---

xml/ay_bigfile.xml

This PR tries to clarify how AutoYaST pre-scripts work.
Related links:
* https://trello.com/c/3re8LvvF/1049-autoyast-hw-probing-behavior-vs-scripts
* https://bugzilla.suse.com/show_bug.cgi?id=1133045

Improve AutoYaST pre-scripts description

---

xml/docker_building_images.xml

Be more explicit about differences between SLE 12 and 15+ and clarify
some statements.
I'm sure there's a FATE/JIRA/WHATEVER about this somewhere, but could not find it...

Add information about tags and metainformation in SLE base images

---

xml/sle_update_offline.xml

Offline migration from SLES 12 to SLES 15 via SCC, see https://bugzilla.suse.com/show_bug.cgi?id=1112881

Offline upgrade scc bsc#1112881

---

xml/art_amd-sev.xml

These commits have some awesome improvements for the AMD SEV article :-).

Improvements for AMD SEV article

---

xml/rmt_install.xml

Add storage space recommendations and location of mirrored packages
- [ x] To maintenance/SLE15SP1
- [ x] To maintenance/SLE15SP0

Add advice re storage space for RMT, note location of packages storage

---

xml/mobile.xml

Rewrote the outdated _Mobile Devices_ chapter and commented out the redundant _More Information_ section.
If accepted and merged, we might want to cherry-pick this into SLE15

Update Mobile Devices chapter

---

xml/book_sle_admin.xml
xml/yast2_gui.xml
xml/yast2_ncurses.xml

The overall goal of the revision is to make the YaST chapter more consistent and better structured. There are four main changes:
- Added a short intro
- Revised the ncurses-section
- Moved content around to make the structure more logical
- Added references to YaST-related topics elsewhere in the documentation

YaST content revision

---

xml/ay_bigfile.xml

new keyboard description file

---

xml/deployment_prep_zseries_prep_i.xml

Fix Travis CI errors for openSUSE Leap 15.0

---

xml/storage_filesystems.xml

Deleting Btrfs subvolume is not as straight as it seems. This section describes a procedure how to
successfully achieve this.

Deleting Btrfs subvolume from the root file system (bsc#1148243)

---

xml/adm_wbem.xml
xml/net_dhcp.xml
xml/storage_nvmeof.xml
xml/xen_virtualization_vhost.xml

https://bugzilla.suse.com/show_bug.cgi?id=1144748

fixes bsc#1144748 (broken links sles12s4)

---

xml/hardening.xml

As of bsc#1152504, updating the introduction to the Common Criteria chapter (1.1): removing details about old product versions and simplifying sentences.    

[WIP] Hardening Guide: update and simplify intro

---

xml/art_amd-sev.xml
xml/ay_bigfile.xml
xml/docker_building_images.xml
xml/docker_overview.xml
xml/docker_registry.xml
xml/hardening.xml
xml/libvirt_configuration.xml
xml/qemu_monitor.xml
xml/security_spectre_meltdown_checker.xml
xml/smt_install.xml
xml/tuning_cgroups.xml
xml/tuning_systemd_coredump.xml
xml/utilities.xml
xml/virt_support.xml
xml/vt_best_practices.xml
xml/vt_introduction.xml

Integrate the corrections from the 2nd proofing drop for SP5 (English-only manuals).
*Are backports required?* 
Merge applicable changes to:

Integrate Language Proofing Corrections

---

xml/smt_mirroring.xml

Reproduce this single-character change from SLE12SP5 version

Change "sle-12_x86_64" to "sle-12-x86_64" (BSC#1158682)

---

xml/ay_bigfile.xml

The regarding keymap code entry is also a valid entry.
No, head only

adapted keyboard valid entries

---

xml/ay_auto_installation.xml

Corrections to integrating linuxrc info w AutoYaST control file

---

xml/deployment_prep_zseries.xml
xml/deployment_prep_zseries_info_i.xml
xml/deployment_prep_zseries_prep_i.xml

Update and  revise the _Installation on IBM Z_ guide.

Z series sle12sp5 update

---

xml/art_sles_rpi_quick.xml
xml/deployment_prep_aarch64_raspi.xml
xml/entity-decl.ent

Initial round of text updates for Raspberry Pi Quick Start and Deployment Guide.
jsc#SLE-7277, jsc#SLE-7276

SLE15-SP2 Raspberry Pi updates

---

xml/ay_bigfile.xml

Fix a comment marker which was backwards
Probably? :)

Backwards XML comment

---

xml/net_samba.xml
xml/snapper.xml

This is not particularly exhaustive, I just tried to make some parts of
this chapter more consistent, fix a few language issues and improve the intro. But essentially, this is a drive-by commit.
- [?] To maintenance/SLE12SP5
- [?] To maintenance/SLE12SP4
- [?] To maintenance/SLE12SP3

snapper: language fixes

---

xml/art_jeos_quickstart.xml

Amend the JEOS quickstart guide with the proofreading corrections from Dublin. I have also done a little bit of rewrapping and fixing indentation.

Dublin proofing corrections for JEOS quickstart guide

---

xml/common_intro_lifecycle_support_i.xml
xml/gnome_custom.xml

Make the requested changes to the GNOME guide book from the proofing corrections.

Incorporate Dublin proofing corrections to SLE GNOME guide (LGHP)

---

xml/art_sles_rpi_quick.xml

Made the corrections requested by the proofreading team. Very slight XML reformatting to keep lines the correct length.
As requested by @taroth21 

Integrate Dublin proofreading corrections for SLE RasPi quickstart

---

xml/common_intro_lifecycle_support_i.xml
xml/sle_update_background.xml
xml/sle_update_backporting.xml
xml/sle_update_offline.xml
xml/sle_update_online.xml
xml/sle_update_upgrading.xml

Make all the changes to the Upgrade Guide as requested by the proofreaders in Dublin.

Incorporate all changes from Dublin proofreaders into Upgrade Guide

---

xml/libvirt_guest_installation.xml

This one updates the installation ISO image names to match SLE15SP1 and SP 0 environment.

Installing Add-on inside VMGuest (bsc#1163377)

---

xml/troubleshooting.xml

Rewrite of the Gnome troubleshooting procedure based on  feedback from Yifan Jiang.

Gnome troubleshooting procedure

---

xml/tuning_cgroups.xml

Resolves Jira #SLE-10123
Please review especially for technical correctness. Not sure that the section on configuring individual users is correct.

Add new section on configuring the TasksMax settings in systemd

---

xml/art_jeos_quickstart.xml

Adding jeos tip for installing Product Patches after firstboot

Adding jeos tip for installing Product Patches after firstboot

---

xml/libvirt_configuration_virsh.xml

This PR improves some existing text in the virsh chapter of the virtualization guide and adds some new text for new settings.
ONLY patch 1 needs to be backported to the following 
- [x ] To maintenance/SLE15SP1
- [x ] To maintenance/SLE15SP0
- [ x] To maintenance/SLE12SP5
Patch 2 and 3 are new for SLE15 SP2.

Improvements for virsh chapter of virtualization guide

---

xml/libvirt_managing.xml

Adds basic info about virsh's parallel migration

Parallel migration for virsh (jsc#SLE-9226)

---

xml/vt_installation.xml

Adds basic info to enable nested virtualization for KVM

KVM nested virtualization (jsc#SLE-11329)

---

xml/vt_installation.xml

Updates libvirt's virtual firmware section, enhancing with the auto-selection mechanism.

Virtual firmware auto-selection (jsc#SLE-9223)

---

xml/deployment_prep_aarch64_raspi.xml

Fix typo in link to OTP bit description document

---

xml/xen_administrating.xml

The new procedure helps identify CPU features on VMhosts to use only those which are supported  on all of them during migraiton.

Detecting CPU features to verify VM migration (jsc#SLE-10184)

---

xml/docker_building_images.xml

This is a do-over of https://github.com/SUSE/doc-sle/pull/617 because I messed it up.

Docker on demand

---

xml/containers-get.xml

Fix a broken link
N/A
I don't know.

Fix link to Registry

---

xml/security_ldap.xml

Several minor updates to the LDAP section
* bsc#1169703

Small changes to LDAP chapter (bsc#1169703)

---

xml/containers-build.xml
xml/containers-docker-building-images.xml
xml/containers-docker-dockerizing-application.xml
xml/containers-docker-installation.xml
xml/containers-docker-registry.xml
xml/containers-get.xml
xml/containers-terminology.xml

Review and feedback by @Vogtinator 
* bsc#...
* jsc#SLE-...

Feedback from fvogt WIP

---

xml/entity-decl.ent
xml/virt_support.xml

Synchronized the info with RNs
no

Virtualization guide updates on supported host/guest systems

---

xml/ay_custom_user_scripts.xml

Adapt to the latest changes in autoyast - PR https://github.com/yast/yast-autoinstallation/pull/612
no, new changes for SP3

AY scripts: improve and adapt to SP3 changes

---

xml/MAIN.SLEDS.xml
xml/book_security.xml
xml/common_criteria.xml
xml/common_intro_available_doc_i.xml
xml/file_management.xml
xml/hardening.xml
xml/physical_security.xml
xml/seccheck.xml
xml/security_pcidss.xml
xml/security_preface.xml
xml/software_management.xml
xml/user_management.xml

This is the first pass at merging the two guides, aiming for a reasonably
coherent blend of content. Next tasks: content review, and link check.
SLE 15* only. PR is for travisci to run checks without disrupting the maint branch
* bsc#...
* jsc#SLE-...

Merge Security Guide and Hardening Guide

---

DC-SLES-hardening
xml/MAIN.SLEDS.xml
xml/common_intro_available_doc_i.xml
xml/hardening.xml
xml/security_pcidss.xml
xml/security_preface.xml

Reverts SUSE/doc-sle#669. TravisCI fails with 'DC file(s) is/are configured in config.xml but not present in repository: DC-SLES-hardening'
https://travis-ci.org/github/SUSE/doc-sle/builds/731622227

Revert "correct build errors, https://travis-ci.org/github/SUSE/doc-sle/build…"

---

DC-SLES-hardening
xml/hardening.xml

Reverts SUSE/doc-sle#673
TravisCI errors, perhaps I should have waited for weekly docserv rebuild. This PR is not urgent & can wait til next Monday.
https://travis-ci.org/github/SUSE/doc-sle/builds/732003802

Revert "removed remaining files that reference the Hardening Guide,"

---

xml/ay_firewall.xml

Describing new feature. Firewall configuration is going to be applied in first stage whenever possible.

Firewall configuration via AutoYaST

---

xml/entity-decl.ent

- rm abstract_hardening, merge with Security Guide abstract, Hardening Guide is merged into the Security Guide

merge abstracts of security/hardening guide

---

xml/tuning_cgroups.xml

Clarification of usage and effects of resource accounting via cgroups.
Note I didn't compile the XML and the text may miss some common docs conventions.
* jsc#PM-2229
| [*] 15 SP3  | (`master` only)   
| [*] 15 SP2  | [ ] 

Cgroup accounting

---

xml/storage_filesystems.xml

A new section describes what `btrfs balance` does and how to customize its behaviour
* bsc#1170577
| [x] 12 SP4  | [ ] 
| [x] 12 SP3  | [ ] 

Added a section on 'btrfs balance' (bsc#1170577)

---

xml/art_sles_rpi_quick.xml

Add another note about wireless authentication, fixes bsc#1166998
bsc#1166998
| [ x] 15 SP2  | [ ] 
| [ x] 15 SP1  | [ ] 

Update RPi guide, wireless auth info(bsc#1166998)

---

xml/rmt_config_files.xml
xml/rmt_mirroring.xml
xml/rmt_rmt-cli.xml

Added documentation for new RMT features:
* rmt-cli repos clean
* rmt-cli systems remove
* "rmt-cli mirror" subcommands
* web server performance settings
Please hold on merging this pull request until the features are released.
| [x] 15 SP2  | [x] 

Added documentation for new features of RMT

---

xml/deployment_prep_zseries.xml

Added a link to a new external source of documentation
* bsc#1178472
| [x 12 SP4  | [ ] 
| [x] 12 SP3  | [ ] 

Added a link to new source of documentation (bsc#1178472)

---

xml/virt_support.xml

add oracle KVM as this is certified by Oracle
| [ ] 15 SP3  | (`master` only)

add Oracle KVM in the list

---

xml/containers-docker-registry.xml
xml/entity-decl.ent

Rewrite the part on running a local Docker registry using the registry container image from registry.suse.com
* bsc#1178131

Container revise registry

---

xml/MAIN.SLEDS.xml
xml/entity-decl.ent

Bump version number, adjust Bugzilla links.
| [x] 15 SP3  | (`master` only)

Prepare for SP3 Doc Start 

---

xml/uefi.xml

Rewrite the MOK chapter.
* bsc#1178170

Revise MOK chapter

---

xml/libvirt_configuration_gui.xml
xml/libvirt_configuration_virsh.xml

Added a note with a solution for the hotplug issue.
* bsc#1179228

Hotplug caveat with SLES11 guests

---

xml/ay_partitioning.xml

This PR describes how to set up `tmpfs` file systems using AutoYaST. It will available starting in SP3.
Thanks!
* [jsc#SLE-11308](https://jira.suse.com/browse/SLE-11308)
* PR: https://github.com/yast/yast-storage-ng/pull/1187

AutoYaST: Add information about setting up tmpfs

---

xml/libvirt_guest_installation.xml
xml/xen_virtualization_vhost.xml

Beta-tester Ulrich  Windl suggested a few improvements for the Virtualization guide. This update includes all of them.
* bsc#1179924

Ulrich Windl's suggestions for Virtualization guide (bsc#1179924)

---

xml/deployment_expert_partitioner_overview.xml
xml/storage_degraded_raid.xml

This PR contains validation fixes.

Fix validation issues

---

xml/security_ldap.xml

re https://github.com/SUSE/doc-sle/pull/728

Fixes a command error, dsctl not dscreate

---

xml/containers-docker-registry.xml
xml/containers-troubleshoot.xml

Add the Troubleshooting chapter.
* jsc#SLE-10416

Container guide troubleshooting

---

xml/security_ldap.xml

re https://jira.suse.com/browse/SLE-16707
https://jira.suse.com/browse/SLE-14732

Add section to LDAP guide stopping and starting server

---

xml/vt_best_practices.xml

Mention, when talking about KSM, that the qemu-ksm package is now
available and that, if installed, it provides a service file that can be
used to start and stop KSM itself.
* jsc#SLE-11692

vt_best_practices: cover the qemu-ksm package

---

xml/sle_update_preparation.xml

please check my suggestion (test purposes for github as well)
* bsc#...
* jsc#SLE-...

Change phrase

---

xml/sle_update_preparation.xml

removed 'recommended' 
* bsc#...
* jsc#SLE-...

small improvement

---

xml/ay_security_settings.xml

Added new tag for describing SELinux
* jsc#SLE-17427 SLE-17307
| [ x] 15 SP2  | [ ] 

added selinux_mode tag

---

xml/sle_update_preparation.xml

Small improvements, please check
* bsc#...
* jsc#SLE-...
| [ X] 15 SP3  | (`master` only)   

Jufa sle upgrade impr inst pack

---

xml/common_intro_available_doc_i.xml
xml/containers-basics.xml
xml/kvm_intro.xml
xml/kvm_virtualization_basics.xml
xml/libvirt_management_vagrant.xml
xml/qemu_overview.xml
xml/vt_best_practices.xml
xml/vt_glossary.xml
xml/vt_introduction.xml
xml/vt_scenarios.xml

This update tries to include multiple unrelated fixes to the virt guides
@aginies please decide whether we should backport these changes to 12 branch as well
* bsc#1179241
| [x] 12 SP5  | [ ]
| [x] 12 SP4  | [ ]
| [x] 12 SP3  | [ ]

Multiple Virtualization guide improvements (bsc#1179241)

---

xml/vt_introduction.xml

Remove 1 sentence about supported KVM on POWER architectures
| [x] 12 SP5  | [ ]
| [x] 12 SP4  | [ ]
| [x] 12 SP3  | [ ]

Removed KVM support sentence for POWER architecture

---

xml/book_sle_virtualization.xml
xml/vt_qemu_tpm.xml

Added a new chapter on software TPM emulator
* jsc#SLE-17527

Added chapter on TPM emulator (jsc#SLE-17527)

---

xml/ay_12_migrate_15.xml
xml/ay_bootloader.xml
xml/ay_configuration_management.xml
xml/ay_control_file.xml
xml/ay_create_control_file.xml
xml/ay_custom_user_scripts.xml
xml/ay_dhcp_server.xml
xml/ay_dynamic_profiles.xml
xml/ay_erb_templates.xml
xml/ay_fiber_channel.xml
xml/ay_firewall.xml
xml/ay_ftp_server.xml
xml/ay_introduction.xml
xml/ay_networking.xml
xml/ay_partitioning.xml
xml/ay_pre_scripts.xml
xml/ay_registration_extensions.xml
xml/book_autoyast.xml

Still needs an overhaul of IDs, as there are dozens that are
written in camel-case and do not use correct prefixes. This is
a big job that will be handled separately.
I ignored long sentences and long computer elements.
* bsc#...
* jsc#SLE-...

Stylecheck corrections: wordy phrases, words, list formatting

---

xml/entity-decl.ent

Shortening the abstracts for the books.

shorten and streamline book abstracts

---

xml/common_intro_lifecycle_support_i.xml

Shorten the support info in our intros, remove duplicate information.

intro: shorten support info

---

xml/entity-decl.ent
xml/sle_update_background.xml
xml/sle_update_online.xml
xml/sle_update_preparation.xml
xml/sle_update_upgrading.xml

Proofing fixes for the Upgrade Guide

All proofing fixes are included for the Upgrade Guide

---

xml/art_jeos_quickstart.xml

Jeos quick: proofreading fixes

---

xml/art_sle_modules_quick.xml

Proofing fixes for Modules Quick Start Guide

---

xml/art_sle_install_quick.xml
xml/art_sle_modules_quick.xml
xml/entity-decl.ent

Proofing fixed for Installation Quick Start Guide

---

xml/security_ldap.xml

cleanups and corrections to ldap user authentication

---

xml/art_jeos.xml

Fix indentation for cloud-init examples
No open bugs for this one
| [ X] 15 SP3  | *(no backport necessary)*
| [ X] 15 SP2  | [ ]
| [ X] 15 SP1  | [ ]
| [ X] 15 SP0  | [ ]

Fix indentation for cloud-init examples

---

xml/ay_partitioning.xml
xml/ay_registration_extensions.xml
xml/ay_software.xml

some tables are too large and do not render well in HTML
or PDF

Convert too-large tables in AY Guide to variablelists

---

xml/virt_support.xml

Updates to the support info in virtualization guests

---

xml/systemd.xml

Please check my proposals.
| [ x ] 15 SP3  | *(no backport necessary)*
| [ x ] 15 SP2  | [ ]

admin guide systemd improvements

---

xml/deployment_prep_zseries.xml
xml/deployment_prep_zseries_prep_io_auto_config.xml
xml/deployment_prep_zseries_prep_secure_boot.xml

Add information on IBM Z secure boot.
* bsc#...
* jsc#SLE-...

IBM Z secure boot

---

xml/klp.xml

Added a section on the kernel patch downgradeprocedure
* bsc#...
* jsc#SLE-...

Kernel patch downgrade

---

DC-SLE-Micro-html
DEF-SLE-Micro-manuals

Prepare localization drop. Added a DEC for html build and a DEF file.

Localization Preparation SLE Micro

---

xml/systemd.xml

Bugfix for bsc#1182491
Note about drop-in files for systemd added
* bsc#1182491
* jsc#DOCTEAM-19
| [ x] 15 SP2  | [ ]

Jufa/admin guide systemd fix bsc#1182491

---

xml/systemd.xml

Ranges for drop-in files added.
* bsc#1182491
* jsc#DOCTEAM-19
| [ x] 15 SP2  | [ ]

ranges for drop-in files added

---

xml/vt_installation.xml

Added support info for secure boot.

---

xml/ay_dynamic_profiles.xml

Mention the <ask-list> element as a mechanism to build a dynamic profile.

AutoYaST: reference "ask-list" when describing dynamic profiles

---

xml/sle_update_offline.xml

Mention that orphaned packages are from an older release, unsupported, and not automatically removed.
* [bsc#1134403](https://bugzilla.suse.com/show_bug.cgi?id=1134403)

Fix bsc#1134403: more info about orphaned packages

---

xml/chrony.xml
xml/mobile.xml
xml/net_xntp.xml
xml/networkmanager.xml
xml/nm.xml

Double-check and update Network Manager content.
* SLE-17771
| [ x ] 15 SP3  | *(no backport necessary)*
| [ x ] 15 SP2  | [ ]

Network Mananger support

---

xml/art_modules.xml

Performed the following checks and issues fixed:
- Spellcheck
- Stylecheck
- Linkcheck

style-, spell, and linkcheck issues fixed

---

xml/art_installation-sleds.xml

Performed the following checks and issues fixed:
- stylecheck
- spellcheck
- linkcheck

issues from spell-, style- and linkcheck fixed

---

xml/qemu_running_vms_qemukvm.xml

* bsc#1182738
* jsc#DOCTEAM-37

Improvements for ARM architecture (bsc#1182738)

---

xml/ay_partitioning.xml
xml/ay_registration_extensions.xml

resolves BSC #https://bugzilla.suse.com/show_bug.cgi?id=1185014
| [x ] 15 SP1  | [ ]
| [x ] 15 SP0  | [ ]

Add more complete examples for listing SLE modules in an AY profile

---

xml/virt_support.xml

Support status for 15 SP3 is updated (jsc#sle 17766)

---

xml/virt_support.xml

| [x] 15 SP4  |*(no backport necessary)*
| [x] 15 SP3  | [ ]

Oracle guest is supported only for KVM

---

xml/tuning_sapconf.xml

Taken from SUSE/doc-slesforsap#81aca52 and integrated it for 15 SP3.
(For 15 SP3 only, we moved this chapter from SLES4SAP into SLE.)
* DOCTEAM-175
*  bsc#1185770

Add section about sapconf_check

---

xml/systemd.xml

Add a chapter on using systemd timer units.
* DOCTEAM-51
| [ x ] 15 SP4  |*(no backport necessary)*
| [ x ] 15 SP3  | [ ]

systemd timer units

---

xml/libvirt_management_vagrant.xml
xml/virt_support.xml

no
| [ ] 15 SP4  |*(no backport necessary)*
| [x] 15 SP3  | [ ]

Updating sp1/2 links, take 2

---

xml/security_ldap.xml
xml/security_ldap_migrate_test.xml

Add section on migrating from openldap to 389DS in Security Guide

---

xml/security_ldap_migrate_test.xml

re: re  Jira SLE-14732
- SLE 12

Add section on migration planning openldap -> 389 DS

---

xml/file_management.xml
xml/physical_security.xml
xml/security_freeradius.xml
xml/security_ldap_install.xml
xml/security_ldap_migrate_test.xml
xml/security_preface.xml
xml/user_management.xml

Security Guide: stylecheck, spellcheck, linkcheck

---

xml/tuning_cgroups.xml
xml/tuning_kexec.xml
xml/tuning_logfiles.xml
xml/tuning_sapconf.xml
xml/utilities.xml

This was a quick review, the Tuning Guide needs work on
consistent terminology and spelling, and cleaning up wording.
Tuning Guide is lower priority, will try to get to it
before next release cycle.
Linkcheck found no bad links.
- SLE 12

Tuning Guide: stylecheck, spellcheck, linkcheck

---

xml/rmt_certificates.xml
xml/rmt_install.xml

RMT: link & spell & style checks done

---

xml/libvirt_configuration_virsh.xml
xml/libvirt_connect.xml
xml/libvirt_guest_installation.xml
xml/libvirt_host.xml
xml/libvirt_management_vagrant.xml
xml/libvirt_overview.xml
xml/pv2fv.xml
xml/qemu_monitor.xml
xml/virt_support.xml
xml/vt_clocksettings.xml
xml/vt_scenarios.xml
xml/xen_administrating.xml
xml/xen_ha_setup.xml
xml/xen_virtualization_vhost.xml

Virt: link & spell & style checks done

---

xml/art_virtualization-best-practices.xml

Virt BP: link & spell & style checks done

---

.github/workflows/docbook.yml

Add initial GHA validation
Please don't merge this down to other branches quite yet.

Toms's validation GHA

---

xml/entity-decl.ent
xml/virt_support.xml

Added LinuxONE as a supported architecture (jsc#DOCTEAM-100)

---

xml/containers-get.xml

Fix DOCTEAM-21
Add a section describing image signature validation
* DOCTEAM-21
- [ x ] SLE 15 SP4/openSUSE Leap 15.4 *(if applicable to 15 SP4 _only_ -- do not merge yet!)*
- [ x ] SLE 15 SP3/openSUSE Leap 15.3 *(current `main`, no backport necessary)*
- [ x ] SLE 15 SP2/openSUSE Leap 15.2
- SLE 12

Container verification

---

xml/art_installation-sleds.xml

Incorporate Dubllin proofreading changes to SLES for SAP installation article
* bsc#...
* jsc#SLE-...
- SLE 12

Incorporate proofing changes to SLES-for-SAP install article

---

xml/troubleshooting.xml

Information about problems with dual boot added
* bsc#1185274
* jsc#DOCTEAM-178
- [x ] SLE 15 SP2/openSUSE Leap 15.2
- SLE 12

added dual boot problems bsc#1185274

---

xml/ay_partitioning.xml

resolves BSC #1186833, Jira DOCTEAM-200
- SLE 12

Replace variable list in AY Guide SLE 15 SP2 with the correct list

---

xml/ay_registration_extensions.xml

BSC 1186717, Jira DOCTEAM-201
- SLE 12

Add continuation, \, to long command in AY Guide

---

xml/art_amd-sev.xml

There is only 1 change in this -- adding the title of another guide being linked.
* bsc#...
* jsc#SLE-...
- SLE 12

Incorporate Dublin proofreading changes to AMD-SEV guide

---

xml/art_virtualization-best-practices.xml

Integrate proofreading changes from Dublin.
* bsc#...
* jsc#SLE-...
- SLE 12

Integrate proofing changes into Virtualization Best Practices

---

xml/troubleshooting.xml

Modified info about boot problems for dual boot.
* bsc#1185274
* jsc#DOCTEAM-178
- SLE 12

modified info about boot error bsc#1185274

---

xml/tuning_cgroups.xml
xml/tuning_kexec.xml
xml/tuning_sapconf.xml
xml/tuning_storagescheduler.xml
xml/utilities.xml

incorporate proofing changes in System Analysis and Tuning Guide

---

xml/containers-basics.xml
xml/containers-build-tools.xml
xml/containers-buildah-overview.xml
xml/containers-docker-building-images.xml
xml/containers-docker-containerize-app.xml
xml/containers-docker-installation.xml
xml/containers-docker-overview.xml
xml/containers-docker-registry.xml
xml/containers-docker-use.xml
xml/containers-get.xml
xml/containers-orchestration.xml
xml/containers-podman-overview.xml
xml/containers-support.xml
xml/containers-terminology.xml
xml/containers-troubleshoot.xml

Integrating proof-reading corrections from Dublin to the Container Guide. 
* bsc#...
* jsc#SLE-...
- SLE 12

Proofing corrections to the Container Guide

---

xml/apparmor_changehat.xml
xml/apparmor_intro.xml
xml/apparmor_support.xml
xml/audit_scenarios.xml
xml/common_criteria.xml
xml/file_management.xml
xml/hardening_pam_stack.xml
xml/physical_security.xml
xml/seccheck.xml
xml/security_acls.xml
xml/security_ad_support.xml
xml/security_cryptctl.xml
xml/security_firewall.xml
xml/security_kerberos.xml
xml/security_ldap_directory_tree.xml
xml/security_ldap_install.xml
xml/security_ldap_migrate_test.xml
xml/security_ldap_modules.xml
xml/security_ldap_sssd.xml
xml/security_pam.xml
xml/security_pcidss.xml
xml/security_policy_kit.xml
xml/security_preface.xml
xml/security_spectre_meltdown_checker.xml
xml/security_xca.xml
xml/security_xforwarding.xml
xml/security_yast2_security.xml
xml/selinux.xml
xml/software_management.xml
xml/user_management.xml

Applied changes from proofreader to Security and Hardening Guide

---

xml/art_jeos.xml

Also change the example to use two different passwords
* bsc#...
* jsc#SLE-...
| [ ] 15 SP4  |*(no backport necessary)*
| [ ] 15 SP3  | [ ]

Fix duplicate line

---

xml/selinux.xml

enable the patterns-devel-C-C++-devel_C_C++ pattern.
resolves BSC #1186679, Jira #DOCTEAM-187
- SLE 12

Add instructions for installing PackageHub from YaST, to

---

xml/virt_support.xml

Added Windows Server 2022 to the list of supported guests
* bsc#1187807
* jsc#DOCTEAM-243
- SLE 12

Added Windows Server 2022 to the list of supported guests

---

xml/nm.xml

Info added that Network manager is now also available for desktop computers.
* bsc#1174934
- SLE 12

NM for desktop added bsc#1174934

---

xml/smt_mirroring.xml

Updated credential merge request sentence (bsc#1187494)

---

xml/deployment_expert_partitioner.xml

Split long para for better appearance on TOC page (bsc#1188696)

---

xml/security_ldap.xml
xml/security_ldap_backups.xml
xml/security_ldap_ca.xml
xml/security_ldap_migrate_test.xml
xml/security_ldap_modules.xml
xml/security_ldap_sssd.xml
xml/security_ldap_users.xml

a bunch of fixes and cleanups
- SLE 12

clean up commands, fix formatting errors

---

xml/virt_support.xml

Updated Microsoft host/guest supported status (bsc#1190253)

---

xml/entity-decl.ent
xml/security_ldap.xml
xml/security_ldap_modules.xml
xml/security_ldap_replication.xml
xml/security_ldap_sssd.xml

write up basic replication concepts, and procedures for configuring replication
- SLE 12

First draft of LDAP replication chapter

---

l10n/sled/ar-ar/xml/security_ldap_replication.xml
l10n/sled/cs-cz/xml/security_ldap_replication.xml
l10n/sled/de-de/xml/security_ldap_replication.xml
l10n/sled/es-es/xml/security_ldap_replication.xml
l10n/sled/fr-fr/xml/security_ldap_replication.xml
l10n/sled/hu-hu/xml/security_ldap_replication.xml
l10n/sled/it-it/xml/security_ldap_replication.xml
l10n/sled/ja-jp/xml/security_ldap_replication.xml
l10n/sled/ko-kr/xml/security_ldap_replication.xml
l10n/sled/pl-pl/xml/security_ldap_replication.xml
l10n/sled/pt-br/xml/security_ldap_replication.xml
l10n/sled/ru-ru/xml/security_ldap_replication.xml
l10n/sled/zh-cn/xml/security_ldap_replication.xml
l10n/sled/zh-tw/xml/security_ldap_replication.xml
l10n/sles/ar-ar/xml/security_ldap_replication.xml
l10n/sles/cs-cz/xml/security_ldap_replication.xml
l10n/sles/de-de/xml/security_ldap_replication.xml
l10n/sles/es-es/xml/security_ldap_replication.xml
l10n/sles/fr-fr/xml/security_ldap_replication.xml
l10n/sles/hu-hu/xml/security_ldap_replication.xml
l10n/sles/it-it/xml/security_ldap_replication.xml
l10n/sles/ja-jp/xml/security_ldap_replication.xml
l10n/sles/ko-kr/xml/security_ldap_replication.xml
l10n/sles/pl-pl/xml/security_ldap_replication.xml
l10n/sles/pt-br/xml/security_ldap_replication.xml
l10n/sles/ru-ru/xml/security_ldap_replication.xml
l10n/sles/zh-cn/xml/security_ldap_backups.xml
l10n/sles/zh-cn/xml/security_ldap_replication.xml
l10n/sles/zh-tw/xml/security_ldap_replication.xml

add l10n symlinks for new file, security_ldap_replication.xml
- SLE 12

add localization symlinks for security_ldap_replication.xml

---

xml/containers-build-tools.xml

Update to SP3 to reflect that this is the SP3 branch.
* bsc#...
* jsc#SLE-...
- SLE 12

Update to SP3

---

xml/ay_configuration_installation_options.xml
xml/ay_software.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Added the software section to the SLE Micro AY guide.

---

xml/installation-opensuse.xml

Fix a minor typo
* bsc#...
* jsc#SLE-...
- SLE 12

fix minor typo

---

xml/troubleshooting.xml
xml/zseries_boot_new_kernel.xml

Integrate TID https://www.suse.com/support/kb/doc/?id=000020342
* bsc#1175827
- SLE 12

New kernel boot on IBM Z

---

xml/opensuse_update.xml

Fix minor typos and solve wrong formatted text
* bsc#...
* jsc#SLE-...
- SLE 12

fix minor typos and formatted text

---

xml/security_cryptofs.xml

correction to gpg encryption example

---

xml/art_virtualization-best-practices.xml

Scheduler change at runtime must be run by root (bsc#1192966)

---

l10n/sles/es-es/xml/common_intro_feedback_i.xml
l10n/sles/es-es/xml/common_intro_typografie_i.xml
l10n/sles/es-es/xml/deployment_prep_zseries_prep_i.xml

Typos in spanish translation fixed.
* bsc#1193094
* jsc#DOCTEAM-430
- SLE 12

bsc#1193094 fix typos ESP

---

xml/vt_cachemodes.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Uncommenting ditaa <figure> back

---

l10n/sled/ar-ar/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/cs-cz/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/de-de/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/es-es/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/fr-fr/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/hu-hu/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/it-it/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/ja-jp/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/ko-kr/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/pl-pl/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/pt-br/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/ru-ru/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/zh-cn/images/src/ditaa/virt-disk-cache.ditaa
l10n/sled/zh-tw/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/ar-ar/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/cs-cz/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/de-de/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/es-es/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/fr-fr/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/hu-hu/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/it-it/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/ja-jp/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/ko-kr/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/pl-pl/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/pt-br/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/ru-ru/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/zh-cn/images/src/ditaa/virt-disk-cache.ditaa
l10n/sles/zh-tw/images/src/ditaa/virt-disk-cache.ditaa
xml/vt_cachemodes.xml

!!!No backport needed!!!
- SLE 12

Fixing 15sp3 ditaa image fix

---

xml/security_ldap_sssd.xml

add an sssd.conf example, improve section title
- SLE 12

add sssd.conf example for 389 Directory Server

---

xml/tuning_cgroups.xml

corrected filepaths, made some minor wording corrections,
ran daps-xmlformat
- SLE 12

some systemd filepaths changed for SLE SP3 and up

---

xml/security_ldap_users.xml

Divide user & group management into task-focused sections
- SLE 12

Reorganize users & group manager section

---

xml/virt_support.xml

Small addition to an already merged PR.
Rendered PDF is attached 
[virt-support-feature-support_color_en.pdf](https://github.com/SUSE/doc-sle/files/7726865/virt-support-feature-support_color_en.pdf)
* bsc#1192256
- SLE 12

Virtualization: Xen limits improvements (bsc#1192256)

---

xml/security_ldap.xml
xml/security_ldap_active_directory_sync.xml
xml/security_ldap_install.xml

Add new section 'Synchronizing with Microsoft Active Directory' to 389 Directory Server chapter
* jsc#DOCTEAM-455
- SLE 12

Add new section to 389 Directory Server chapter

---

xml/containers-basics.xml

Trying to improve containers-basics
* bsc#...
* jsc#SLE-...
ALL SP that has this doc.
- SLE 12

Trying to improve containers-basics

---

xml/x11.xml

I find the `xrdp` method very useful, especially when running SUSE as a VM guest.  I think it is worth mentioning in the [X11 section](https://doc.opensuse.org/documentation/leap/reference/html/book-reference/cha-gui-desktop.html#sec-gui-desktop-xorg).
None
- SLE 12

About xrdp on a server

---

xml/containers-basics.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Improved phrasing

---

xml/virt_support.xml

Added Windows Server 2022 as supported host (jsc#SLE-21148)

---

xml/vt_tools.xml

Added several important cmdline virt utilities (bsc#1154707)

---

xml/net_proxy.xml

Squid chapter language review
* bsc#...
* jsc#SLE-...
- SLE 12

Squid chapter lang review

---

xml/containers-podman-overview.xml

Fix 
Update rootless mode info
* SLE-21406
- SLE 12

Rootless mode fix

---

xml/art-nvidia-vgpu.xml
xml/kernel_modules.xml
xml/pv2fv.xml
xml/security_fips.xml
xml/security_pcidss.xml

Fix SLE-21361
* bsc#...
* jsc#SLE-...
- SLE 12

Replace mkinitrd w/dracut

---

xml/deployment_prep_zseries.xml
xml/deployment_prep_zseries_prep_i.xml

Fix SLE-23616
* bsc#...
* jsc#SLE-...
- SLE 12

Update connection options

---

xml/security_fips.xml

Expand FIPS chapter with overview and use case 
resolves Jira SLE-23136
- SLE 12

Expand FIPS chapter in Security Guide

---

xml/art_virtualization-best-practices.xml

fixes:
* https://jira.suse.com/browse/DOCTEAM-508
* https://jira.suse.com/browse/DOCTEAM-509
* https://jira.suse.com/browse/DOCTEAM-510
* https://jira.suse.com/browse/DOCTEAM-511
- SLE 12

Updates based on feedback on the virtualization best practices

---

xml/ay_bootloader.xml

Try to be more specific about the use case, and what it does
- SLE 12

Clarify and expand description of AY GRUB 2 password option 

---

DC-SLES-minvm
xml/MAIN.SLEDS.xml
xml/art_minimal-vm.xml
xml/art_minvm.xml
xml/entity-decl.ent

Rename the JeOS guide to the Minimal VM Guide
* jsc#SLE-21530
- SLE 12

JeOS to Minimal VM rename

---

xml/art_virtualization-best-practices.xml

fixes https://bugzilla.suse.com/show_bug.cgi?id=1195446
- SLE 12

Update to raw image format (bsc#1195446)

---

xml/art_virtualization-best-practices.xml

+ fixed custom sysctl file name
fixes https://bugzilla.suse.com/show_bug.cgi?id=1195442
- SLE 12

Updated sudos into root prompt (bsc#1195442)

---

xml/zypper.xml

closes https://jira.suse.com/browse/DOCTEAM-505
- [x ] SLE 15 SP1
- SLE 12

Enhanced zypper up/patch with detailed info

---

xml/ay_bootloader.xml

Apply corrections from https://github.com/SUSE/doc-sle/pull/1074#discussion_r804736677
- SLE 12

apply corrections from review for ay_bootloader.xml

---

xml/book_administration.xml
xml/generic-entities.ent
xml/ulp.xml

Add the "Userspace live patching" chapter
* jsc#SLE-20214
- SLE 12

Userspace live patching

---

xml/deployment_docupdates.xml
xml/docker_docupdates.xml
xml/storage_filesystems.xml
xml/storage_iscsi.xml
xml/storage_nvmeof.xml
xml/tuning_kexec.xml

A ton of SEO fixes. Link replacement or removal. Each branch is handled separately, therefore no backports.
- SLE 12
- [x ] SLE 12 SP3

SEO fixes: kill or replace broken links all across SLE12 SP3

---

xml/net_dhcp.xml

SEO squad: fix broken links
Will be fixed for each branch separately, so no backport needed
- SLE 12

SEO issues fix link

---

xml/virt_support.xml

Updated support information for ARM/KVM/QEMU

---

xml/virt_support.xml

fix  path to kvm-supported.txt text
* bsc#...
* jsc#SLE-...
- [x ] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
- [x ] SLE 15 SP3/openSUSE Leap 15.3
- [ x] SLE 15 SP2/openSUSE Leap 15.2
- SLE 12

fix path to kvm-supported.txt text

---

xml/ay_software.xml
xml/containers-support.xml

Add the "Technology previews" chapter.
* jsc#SLE-23991
- SLE 12

Container guide tech previews

---

xml/art_minimal-vm.xml

Remove abbreviation explanation 'Just enough Operating System' from intro (former name 'JeOS' is mentioned in the abstract), but here the explanation no longer makes sense IMHO.
* jsc#SLE-21530
No backports needed.

Min VM: rm abbreviation declaration

---

xml/art_amd-sev.xml

Describe how to configure KubeVirt and the VMI spec to enable SEV guest encryption.
* bsc#...
* jsc#SLE-...
- SLE 12

AMD SEV article: Add section about KubeVirt

---

xml/ay_erb_templates.xml
xml/ay_pre_scripts.xml
xml/ay_rules_classes.xml

Extend documentation about AutoYaST ERB templates.
* bsc#...
* jsc#SLE-...
- SLE 12

Improving AutoYaST ERB documentation

---

xml/ay_erb_templates.xml

some small wording changes, formatting corrections

---

xml/security_ldap.xml
xml/security_ldap_install.xml
xml/security_ldap_sssd.xml

minor updates and corrections to LDAP chapter

---

DC-SLE-Micro-security
xml/MAIN.SLE-Micro.xml
xml/art_admin_slemicro_selinux.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Micro se linux

---

xml/art_installation-sleds.xml
xml/phrases-decl.ent

Integrated proofing corrections from VT.

Install Quick Proofing integration

---

xml/art_modules.xml

Integrated proofing corrections on Modules from VT.

Modules proofing integration

---

xml/ay_ask_user_values.xml
xml/ay_bootloader.xml
xml/ay_erb_templates.xml
xml/ay_networking.xml

Integrated proofing corrections on AutoYast from VT.

AutoYast proofing integration

---

xml/common_intro_lifecycle_support_i.xml
xml/deployment_expert_partitioner_overview.xml
xml/deployment_prep_aarch64_nsysreqs.xml
xml/deployment_prep_zseries_prep_io_auto_config.xml
xml/deployment_yast_installer.xml
xml/sle_update_background.xml
xml/yast2_sw_addon.xml

Integrated proofing corrections on Deployment from VT.

Deployment proofing integration

---

xml/sle_update_online.xml

Integrated proofing corrections on Upgrade from VT.

Upgrade proofing integration

---

xml/security_ldap_modules.xml

memberOf section was incomplete. This should better describe the process.
bsc#1196845
- SLE 12

improve memberOf section of 389 DS chapter

---

l10n/sles/zh-cn/xml/net_dhcp.xml
l10n/sles/zh-cn/xml/storage_filesystems.xml
l10n/sles/zh-tw/xml/storage_filesystems.xml

SEO link fixes_zh

---

xml/security_cryptctl.xml
xml/security_vpnserver.xml

Search for instances of exclusive language, such as blacklist/whitelist, master/slave, and replace with inclusive language
Jira SLE-22017
- SLE 12

change references to 'master' to more inclusive language

---

xml/art-nvidia-vgpu.xml

what title says
* bsc#1197548
- SLE 12

Install gcc alongside kernel (bsc#1197548)

---

xml/storage_filesystems.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Jhalackova doc 550

---

xml/selinux.xml

Fix sentence in selinux guide.

Fix sentence in selinux guide

---

xml/backup.xml

Update GNOME user guide: change describtion of how to back up user data with deja dub
- SLE 12

GNOME update deja dub

---

xml/security_ldap_sssd.xml

re Bugzilla #1196821
Jira #DOCTEAM-544
- SLE 12

Small corrections to the SSSD chapter in the Security Guide

---

xml/apps_firefox.xml

Changed description of how to enable ftp links in Firefox.
* bsc#1190667
- SLE 12

GNOME change ftp

---

xml/net_samba.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Jhalackova bsc#1190678

---

xml/storage_nvmeof.xml
xml/vt_best_practices.xml
xml/xm_vs_xl_links.xml

SEO fixes of broken links SLE15SP0

---

xml/security_ldap_active_directory_sync.xml
xml/security_preface.xml
xml/storage_nvmeof.xml
xml/vt_best_practices.xml
xml/xm_vs_xl_links.xml

SEO fixes of broken links SLE15SP2

---

xml/art_virtualization-best-practices.xml
xml/security_ldap_active_directory_sync.xml
xml/storage_nfs.xml
xml/storage_nvmeof.xml
xml/xm_vs_xl_links.xml

SEO fixes of broken links_SLE15SP3

---

xml/storage_nvmeof.xml
xml/vt_best_practices.xml
xml/xm_vs_xl_links.xml

Changes will be done for each branch separately so no backports needed.
- SLE 12

SEO fixes of broken links_SLE12SP5

---

xml/tuning_cgroups.xml

Resolves Jira SLE-22013
- SLE 12

Describe differences between cgroup APIs unified & hybrid in SLE 15 SP4

---

xml/tuning_cgroups.xml
xml/tuning_logfiles.xml
xml/tuning_taskscheduler.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Stylecheck for Tuning Guide

---

xml/tuning_power.xml

Tuning guide linkcheck

---

xml/selinux.xml

Small changes to SELinux description found during the SELinux guide review for SLE Micro.
* bsc#...
* jsc#SLE-...
- SLE 12

Added review made by Johannes for SLE Micro.

---

xml/apparmor_profiles_yast.xml
xml/apparmor_support.xml
xml/file_management.xml
xml/security_ldap_active_directory_sync.xml
xml/security_ldap_backups.xml
xml/security_ldap_replication.xml
xml/security_ssh.xml
xml/security_sysctl.xml
xml/security_xca.xml
xml/user_management.xml

Security guide stylecheck

---

xml/art_minimal-vm.xml

With single-HTML being deprecated as part of the new HTML layout, we need to fix the links.
* jsc#DOCTEAM-620
No backports as such, will check each maintenance branch individually.

Fix links  (single-html -> html)

---

xml/security_ssh.xml

continuing updates and improvements to the OpenSSH chapter
- SLE 12

corrections and cleanups to OpenSSH chapter in the Security Guide

---

l10n/sles/ja-jp/xml/storage_iscsi.xml

SEO fix broken link "coolsolution" for SLES 12 SP4 JA
Changes will be done for each version separately, so no backport necessary
- SLE 12

SEO fix coolsolution link

---

l10n/sles/de-de/xml/net_dhcp.xml

SEO fix broken links "DHCP" SLES 12 SP4 DE
Changes will be done for each version separately, so no backport necessary. 
* bsc#...
* jsc#SLE-...
- SLE 12

SEO fix DHCP link

---

l10n/sles/de-de/xml/net_dhcp.xml

Fix broken links in de trans files. No backports, no cherry-picking. 
* bsc#...
* jsc#SLE-...
- [x ] SLE 15 GA
- SLE 12

SEO fixes for SLE 15 SP0

---

l10n/sles/ja-jp/xml/adm_support.xml
l10n/sles/ja-jp/xml/net_dhcp.xml
l10n/sles/ja-jp/xml/storage_filesystems.xml
l10n/sles/ja-jp/xml/storage_nvmeof.xml

* bsc#...
* jsc#SLE-...
- SLE 12

SEO fixes of broken links SLE12SP4_JP

---

l10n/sles/zh-tw/xml/net_dhcp.xml
l10n/sles/zh-tw/xml/storage_filesystems.xml
l10n/sles/zh-tw/xml/storage_iscsi.xml
l10n/sles/zh-tw/xml/storage_nvmeof.xml

* bsc#...
* jsc#SLE-...
- SLE 12

SEO fixes of broken links SLE12SP4_ZH_TW

---

xml/rmt_install.xml

RMT Guide: proofdrop checks

---

l10n/sles/zh-cn/xml/net_dhcp.xml
l10n/sles/zh-cn/xml/storage_filesystems.xml
l10n/sles/zh-cn/xml/storage_iscsi.xml
l10n/sles/zh-cn/xml/storage_nvmeof.xml

* bsc#...
* jsc#SLE-...
- SLE 12

SEO fixes of broken links SLE12SP4_CN

---

xml/gpu_passthru.xml
xml/libvirt_configuration_virsh.xml
xml/libvirt_host.xml
xml/vt_cachemodes.xml
xml/vt_installation.xml
xml/xen2kvm.xml
xml/xm_vs_xl_links.xml

Virt guide proofdrop checks

---

l10n/sles/de-de/xml/net_nfs.xml
l10n/sles/ja-jp/xml/net_nfs.xml
l10n/sles/ja-jp/xml/storage_filesystems.xml
l10n/sles/ja-jp/xml/storage_iscsi.xml
l10n/sles/ja-jp/xml/storage_nvmeof.xml
l10n/sles/zh-cn/xml/net_nfs.xml
l10n/sles/zh-cn/xml/storage_filesystems.xml
l10n/sles/zh-cn/xml/storage_iscsi.xml
l10n/sles/zh-cn/xml/storage_nvmeof.xml
l10n/sles/zh-tw/xml/net_nfs.xml
l10n/sles/zh-tw/xml/storage_filesystems.xml
l10n/sles/zh-tw/xml/storage_iscsi.xml
l10n/sles/zh-tw/xml/storage_nvmeof.xml

SEO: fix broken links for l10n SLE 12 SP5
changes will be done in all branches separately so no backporting
- SLE 12

SEO fix links SLE 12 SP5 l10n

---

xml/art_amd-sev.xml

Update and improve the AMD SEV doc for SLE15 SP4.
* jsc#SLE-18834
- SLE 12

Improve sev doc

---

xml/adm_sudo.xml
xml/common_intro_lifecycle_support_i.xml
xml/grub2.xml
xml/net_proxy.xml
xml/net_yast.xml
xml/tuning_multikernel.xml
xml/ulp.xml
xml/updater_gnome.xml
xml/updater_gnome_sw.xml
xml/yast2_lang.xml
xml/yast2_printer.xml
xml/yast2_sw.xml
xml/yast2_sw_repo.xml
xml/yast2_userman.xml
xml/yast2_you.xml
xml/zseries_boot_new_kernel.xml
xml/zypper.xml

Integrated proofing corrections for SLES Administration Guide from VT.

SLES Administration Guide proofing integration

---

xml/common_intro_lifecycle_support_i.xml
xml/net_samba.xml
xml/storage_filesystems.xml
xml/storage_nvmeof.xml
xml/storage_uuids.xml

Integrated proofing corrections for SLES Storage Administration Guide from VT.

SLES Storage Administration Guide proofing integration

---

xml/virt_support.xml

Updated virtualization support for 15 SP4

---

xml/gnome_start.xml

Fix description GNOME basic
* bsc#1174735
* jsc#DOCTEAM-249
- SLE 12

fix bsc#1174735

---

doc-kit.conf
xml/book_container.xml
xml/containers-bci.xml
xml/generic-entities.ent

Add _Why BCI_ chapter, restructure content.
* bsc#...
* jsc#SLE-...
- SLE 12

Why BCI and restructure

---

xml/containers-basics.xml

Fix typo in Container Guide.
I don't know and didn't find.
- SLE 12

Fix typo in Container Guide

---

xml/containers-docker-installation.xml
xml/containers-docker-registry.xml
xml/containers-get.xml

Remove all mentions of Portus.
* bsc#...
* jsc#SLE-...
- SLE 12

Remove Portus

---

xml/generic-entities.ent
xml/security_ssh.xml
xml/sle_update_preparation.xml

expand SSH auth types, more information on key management

---

xml/security_ssh.xml

formatting and typo corrections

---

xml/art_amd-sev.xml

Integrated proofing corrections for the AMD-SEV Guide from VT.

AMD-SEV proofing integration

---

xml/rmt_install.xml

Integrated proofing corrections for the RMT Guide from VT.

RMT Guide proofing integration

---

xml/libvirt_configuration_virsh.xml
xml/vt_qemu_ga.xml

Integrated proofing corrections for the Virtualization Guide from VT.

Virtualization Guide proofing integration

---

xml/libvirt_connect.xml
xml/security_ssh.xml

continuing the update of the OpenSSH chapter of the Security And Hardening Guide
- SLE 12

clean up creating ssh keys section, small fixes and typos

---

xml/common_intro_feedback_i.xml
xml/containers-basics.xml
xml/containers-support.xml

Integrated proofing corrections for the Container Guide from VT.

Container Guide proofing integration

---

xml/hardening_pam_stack.xml
xml/security_ldap_backups.xml
xml/security_ldap_install.xml
xml/security_ldap_migrate_test.xml
xml/security_ldap_replication.xml
xml/security_ldap_users.xml
xml/security_ssh.xml
xml/security_sysctl.xml
xml/user_management.xml

Integrated proofing corrections for the Security and Hardening Guide from VT.

Security Guide proofing integration

---

l10n/sles/zh-cn/xml/adm_support.xml
l10n/sles/zh-tw/xml/adm_support.xml

* bsc#...
* jsc#SLE-...
- SLE 12

SEO fixes of broken links SLE12SP5_ZH

---

l10n/sles/ja-jp/xml/net_dhcp.xml
l10n/sles/ja-jp/xml/net_nfs.xml
l10n/sles/ja-jp/xml/storage_filesystems.xml
l10n/sles/ja-jp/xml/storage_nvmeof.xml

* bsc#...
* jsc#SLE-...
- SLE 12

SEO fixes of broken links SLE15SP1 JA

---

xml/deployment_postinstall_slemicro.xml

Installing KLP
* bsc#1200474
- SLE Micro
- SLE 12

Jhalackova bsc#1200474

---

l10n/sles/zh-cn/xml/net_nfs.xml
l10n/sles/zh-cn/xml/storage_nvmeof.xml
l10n/sles/zh-tw/xml/net_dhcp.xml
l10n/sles/zh-tw/xml/net_nfs.xml
l10n/sles/zh-tw/xml/storage_nvmeof.xml

SEO fixes of broken links SLE15SP0 ZH

---

xml/common_intro_feedback_i.xml

- according to our new HTML layout
- thanks to Julia for the proposals
* bsc#...
* jsc#SLE-...
- SLE 12

intros: adjust Bug report/Contributions

---

xml/art_admin_slemicro.xml

Adding PCP container description for SLE Micro
- SLE 12

Jhalackova pcp container

---

xml/adm_support.xml
xml/apparmor_profiles_yast.xml
xml/apparmor_support.xml
xml/art_sle_install_quick.xml
xml/gnome_crypto.xml
xml/gnome_custom.xml
xml/gnome_networking.xml
xml/gnome_use.xml
xml/libvirt_managing.xml
xml/libvirt_storage.xml
xml/net_bonding.xml
xml/network_scheme.xml
xml/security_ldap.xml
xml/smt_mirroring.xml
xml/snapper.xml
xml/storage_fcoe.xml
xml/storage_filesystems.xml
xml/storage_iscsi.xml
xml/storage_isns.xml
xml/storage_lvm.xml
xml/storage_raid.xml
xml/storage_raid10.xml
xml/storage_raidroot.xml
xml/systemd.xml
xml/vt_tools.xml
xml/yast2_lang.xml
xml/yast2_sound.xml
xml/yast2_sw.xml
xml/yast2_userman.xml

Added missing alternative texts for figures to improve SEO
jsc#DOCTEAM-579
- SLE 12

SEO add alt texts for SLES

---

xml/security_ssh.xml

Update OpenSSH chapter of the Security Guide, add new features including host key rotation and  host key verification
- SLE 12

more OpenSSH chapter updates

---

xml/storage_planning.xml

SEO fixes of broken links SLE12SP5 ZH

---

l10n/sles/zh-cn/xml/adm_support.xml
l10n/sles/zh-cn/xml/net_nfs.xml
l10n/sles/zh-tw/xml/net_nfs.xml
xml/storage_planning.xml

SEO fixes of broken links SLE12SP4 ZH

---

xml/ay_networking.xml

There are some errors in the AutoYaST networking section which this PR aims to fix.
- https://bugzilla.suse.com/show_bug.cgi?id=1201129
- SLE 12

AutoYaST: networking fixes

---

xml/security_ssh.xml

restore missing OpenSSH CA section, some small corrections

---

xml/storage_multipath.xml

The multipath chapter is strongly outdated
* bsc#1179182
* jsc#SLE-19638
- [x ] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*
- [ x] SLE 15 SP3/openSUSE Leap 15.3
- [ x] SLE 15 SP2/openSUSE Leap 15.2
- [ x] SLE 15 SP1
- [ x] SLE 15 GA
- SLE 12
- [x ] SLE 12 SP5
*Please do not merge: WIP, for now just to make the changes easily review-able*

[WIP] Mwilck/multipath 15.4

---

xml/containers-podman-overview.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Replace $USER by <replaceable>USER</replaceable>

---

l10n/sled/de-de/xml/apps_gimp.xml
l10n/sled/ja-jp/xml/apps_gimp.xml
l10n/sled/pt-br/xml/apps_gimp.xml
l10n/sled/zh-cn/xml/apps_gimp.xml
l10n/sled/zh-tw/xml/apps_gimp.xml
l10n/sles/de-de/xml/apps_gimp.xml
l10n/sles/ja-jp/xml/apps_gimp.xml
l10n/sles/ja-jp/xml/storage_nvmeof.xml
l10n/sles/pt-br/xml/apps_gimp.xml
l10n/sles/zh-cn/xml/apps_gimp.xml
l10n/sles/zh-cn/xml/storage_nvmeof.xml
l10n/sles/zh-cn/xml/vt_best_practices.xml
l10n/sles/zh-tw/xml/apps_gimp.xml
l10n/sles/zh-tw/xml/storage_nvmeof.xml
xml/apps_gimp.xml
xml/libvirt_networking.xml
xml/security_ldap_active_directory_sync.xml

SE fix broken links for SLE 15 SP2 for all languages.
Fixes will be done for each branch separately.
- SLE 12

SEO fix broken links

---

xml/security_polkit.xml

some punctuation and spelling corrections, correct title case to lowercase, add title and xml:id to procedure
- SLE 12

Proofread updated Polkit chapter

---

xml/chrony.xml

Added pool of SUSE NTP servers (bsc#1201007)

---

l10n/sles/de-de/xml/adm_support.xml

SEO fix link

---

en/xml/adm_support.xml
en/xml/net_dhcp.xml
en/xml/storage_iscsi.xml
en/xml/storage_nvmeof.xml
sled/de/xml/adm_support.xml
sled/ja/xml/adm_support.xml
sled/pt_br/xml/adm_support.xml
sled/zh_cn/xml/adm_support.xml
sled/zh_tw/xml/adm_support.xml
sles/de/xml/adm_support.xml
sles/de/xml/net_dhcp.xml
sles/ja/xml/adm_support.xml
sles/ja/xml/net_dhcp.xml
sles/ja/xml/storage_iscsi.xml
sles/ja/xml/storage_nvmeof.xml
sles/zh_cn/xml/adm_support.xml
sles/zh_cn/xml/net_dhcp.xml
sles/zh_cn/xml/storage_iscsi.xml
sles/zh_cn/xml/storage_nvmeof.xml
sles/zh_tw/xml/adm_support.xml
sles/zh_tw/xml/net_dhcp.xml
sles/zh_tw/xml/storage_iscsi.xml
sles/zh_tw/xml/storage_nvmeof.xml

SEO fix broken links trans branch 12 SP4
- SLE 12

SEO fix links trans Aug 09

---

xml/containers-get.xml

Fix BCI-157
* bsc#...
* jsc#SLE-...
- SLE 12

BCI labels

---

xml/art-nvidia-vgpu.xml

Applied updates to vGPU article to make it more precise (bsc#1202224)

---

xml/hardware_nvdimm.xml

Intel Optane has specific modes for its persistent memory model. This update reflects this.
* bsc#1201838
- SLE 12

Added tip on Intel Optane persistent memory (bsc#1201838)

---

xml/virt_logs.xml

Fix typo in command

---

xml/art-nvidia-vgpu.xml

Updated NVIDIA licensing details (bsc#1202656)

---

xml/art-nvidia-vgpu.xml

NVIDIA CUDA toolbox download change (bsc#1202659)

---

xml/book_security_slemicro.xml
xml/security_pam.xml
xml/slemicro_pam_login.xml

Adding MFA for SLE Micro
* bsc#...
* jsc#SLE-...
- SLE 12

Jhalackova pam

---

xml/book_security.xml
xml/security_fips.xml

Update FIPS chapter for FIPS 140-3 as discussed with Cert team last Friday.
* jsc#DOCTEAM-779
- SLE 12

Security Guide: FIPS chapter update

---

xml/storage_raidroot.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Jhalackova storage guide fix

---

xml/vnc.xml

Warn users about Wayland incompatibility with VNC sessions.
* bsc#1202038
- SLE 12

Add info about VNC+Wayland compatibility (bsc#1202038)

---

xml/book_security_slemicro.xml
xml/security_fips.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Jhalackova fips

---

xml/security_preface.xml

- based on feedback by Dennis
- SLE 12

Security Guide: rephrase sentence about hashes

---

xml/slemicro_security_selinux.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Jhalackova udica

---

xml/storage_lvm.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Jhalackova bsc#1184687

---

xml/slemicro_transactional_updates.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Jhalackova bsc#1203591

---

xml/ay_auto_installation.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Added OEMDRV label.

---

xml/storage_nvmeof.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Jhalackova bsc#1200746

---

xml/ay_auto_installation.xml
xml/ay_custom_user_scripts.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Added the repo URI scheme.

---

xml/book_admin_slemicro.xml
xml/slemicro_supportconfig.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Jhalackova adding supportconfig

---

xml/vnc.xml

Added a tip on Vinagre client and a self-signed certificate

---

xml/slemicro_pcp.xml
xml/slemicro_read-only_fs.xml
xml/slemicro_snapshots.xml
xml/slemicro_toolbox.xml
xml/slemicro_transactional_updates.xml
xml/ulp.xml

Adding abstracts to chapters.
* bsc#...
* jsc#...
- SLE 12

Jhalackova bsc#1207024

---

xml/xen_virtualization_vhost.xml

Added warning about harmless ISST driver messages (bsc#1205421)

---

xml/selinux.xml

Add two more modifications suggested by @jsegitz and remove/move additional text snippets afterwards.
* bsc#1205596(c#31)
*  jsc#DOCTEAM-856
- SLE 12

bugfix for selinux part2 (bsc#1205596)

---

xml/adm_shell.xml

Added tip on Bash config files order (bsc#1165697)

---

xml/deployment_images_description.xml
xml/deployment_images_ignition.xml

Jhalackova #docteam 809

---

xml/security_fips.xml

* bsc#...
* jsc#SLE-...
- SLE 12

Jhalackova fips micro

---

xml/virt_support.xml

New version of support statement
* bsc#1181280
- SLE 12

Updated RedHat & CentOS support status

---

xml/rmt_install.xml

* bsc#1202671
* jsc#...
- SLE 12

RMT: document new variables helm-chart

---

xml/virt_support.xml

Fixed QEMU support status

---

xml/art_admin_slemicro_cockpit.xml

Jhalackova nfs cockpit

---

l10n/sled/de-de/xml/fs_structure_i.xml
l10n/sles/de-de/xml/fs_structure_i.xml

Revert translations of <filename> contents
* bsc#1209880
* jsc#DOCTEAM-942
- SLE 12

revert filename translations

---

xml/ay_custom_user_scripts.xml
xml/ay_security_settings.xml
xml/ay_users_groups.xml

Integrated proofing corrections for the AutoYaST Guide from VT.

AutoYaST Guide proofing integration

---

xml/sle_update_background.xml
xml/sle_update_finish.xml
xml/sle_update_preparation.xml
xml/sle_update_upgrading.xml

Integrated proofing corrections for the Upgrade Guide from VT.

Upgrade Guide proofing integration

---

xml/art_amd-sev.xml

Style fixes to AMD-SEV article

---

xml/utilities.xml

Scope correct **Q** to **q** as per the top man page
* [Jira](https://jira.suse.com/browse/DOCTEAM-951)
- [x ] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
- [x ] SLE 15 SP4/openSUSE Leap 15.4
- [x ] SLE 15 SP3/openSUSE Leap 15.3
- [x ] SLE 15 SP2/openSUSE Leap 15.2
- [x ] SLE 15 SP1
- SLE 12
- [x ] SLE 12 SP5
- [x ] SLE 12 SP4

Docteam-951: corrects Q to q

---

xml/adm_sudo.xml

Added step to provide wheel grp (bsc#127981)

---

xml/security_ldap_ca.xml

Fix line break in screen.
* bsc#1207945.
* jsc#DOCTEAM-959
- SLE 12

LDAP CA: fix screen (bsc#1207945)

---

xml/ay_partitioning.xml

Fixes regarding AY RAID configuration

---

xml/net_basic.xml
xml/net_sync.xml
xml/printing.xml

Integrate proofing corrections for the Admin Guide from proofing drop 2
- SLE 12

Admin Guide: integrate proofing corrections

---

xml/art_minimal-vm.xml

Minimal VM Quick Start review before GMC.

Minimal VM Quick Start review

---

xml/art_raspberry-pi.xml

A language review of Raspberry Pi Quick Start before GMC.

Raspberry Pi Quick Start review

---

xml/art_modules.xml

SLED Modules and Extensions Quick Start review before GMC.

SLED Modules and Extensions Quick Start review

---

xml/art_installation-sleds.xml
xml/phrases-decl.ent

A language review of the SLES Installation Quick Start before GMC.

Installation Quick Start: review

---

xml/apps_totem.xml
xml/art_admin_slemicro_cockpit.xml
xml/art_installation-sleds.xml
xml/ay_apache_server.xml
xml/bootconcept.xml
xml/deployment_manual_installation.xml
xml/deployment_prep_x86_media.xml
xml/file_management.xml
xml/fuse.xml
xml/libvirt_connect.xml
xml/networkmanager.xml
xml/nm.xml
xml/powermanagement.xml
xml/security_certificatestore.xml
xml/security_cryptctl.xml
xml/security_ldap_active_directory_sync.xml
xml/security_ldap_replication.xml
xml/security_polkit.xml
xml/storage_isns.xml
xml/tuning_kprobes.xml
xml/tuning_logfiles.xml
xml/tuning_network.xml
xml/tuning_systemtap.xml
xml/xen_virtualization_basics.xml

Several spelling changes

---

xml/adm_shell.xml
xml/ay_control_file.xml
xml/backup.xml
xml/deployment_prep_zseries_prep_i.xml
xml/hardening_pam_stack.xml
xml/net_router.xml
xml/slemicro_pcp.xml
xml/tuning_ptp.xml
xml/tuning_taskscheduler.xml
xml/user_management.xml
xml/yast2_ncurses.xml
xml/zypper.xml

- Variable name correction for yast disk in xml/deployment_prep_zseries_prep_i.xml
- Parameter correction for kdump command  in xml/yast2_ncurses.xml
- Parameter correction for pam in xml/hardening_pam_stack.xml
- Typos in xml/adm_shell.xml
- Typos in xml/ay_control_file.xml
- Typos in xml/backup.xml
- Typo in xml/net_router.xml
- Typo in xml/slemicro_pcp.xml

Fixes and typos

---

xml/rmt_install.xml

Adding nginx and mariadb, they are listed as recommendation for the rmt-server package.
* bsc#1209676
- SLE 12

nginx and mariadb are installation requirements (bsc#1209676)

---

xml/security_ad_support.xml

[JSC#DOCTEAM-310](https://jira.suse.com/browse/DOCTEAM-310)
[BSC#1188688](https://bugzilla.suse.com/show_bug.cgi?id=1188688)
- SLE 12

adds the svg diagram

---

xml/adm_shell.xml
xml/storage_lvm.xml
xml/tuning_kprobes.xml
xml/tuning_logfiles.xml

Replaced http links to tldp.org with https

---

xml/uefi-httpboot-server.xml

Fixes the documentation bug [DOCTEAM-811](https://jira.suse.com/browse/DOCTEAM-811). The detailed findings behind the resolution is available in [this comment](https://jira.suse.com/browse/DOCTEAM-811?focusedCommentId=1266857&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1266857) and a supplemental screenshot is available in the comment below it.
**Note to reviewer**: For actual content change relevant for the bugfix, see the changes in the *lines 281-293*. The rest of the changes that you see are all XML formatting done by `daps`.
* [bsc#1205328](https://bugzilla.suse.com/show_bug.cgi?id=1205328)
- SLE 12
The doc team member merging your PR will …

Fix for the bug DOCTEAM-811

---

xml/security_fips.xml

FIPS: rephrase note, mention 15 SP4 specifically

---

xml/art_virtualization-best-practices.xml

Integrate proofing corrections for the Virtualization Best Practices Guide from proofing drop 3.
- SLE 12

Virtualization Best Practices Guide: integrate proofing corrections

---

xml/art_modules.xml

Integrate proofing corrections for the Modules and Extensions Quick Start Guide from proofing drop 3.
- SLE 12

Modules QS: integrate proofing corrections

---

xml/security_ad_support.xml
xml/security_cryptctl.xml
xml/security_nis.xml
xml/security_pcidss.xml
xml/security_polkit.xml
xml/security_ssh.xml

Integrate proofing corrections for the Security and Hardening Guide from proofing drop 3.
- SLE 12

Security and Hardening Guide: integrate proofing corrections

---

doc-kit.conf
xml/generic-entities.ent
xml/storage_nvmeof.xml

Fixed PED-4795.

---

xml/security_firewall.xml

Mention that YaST firewall module only modifies permanent settings. 
* bsc#1206320
* jsc#DOCTEAM-870
- SLE 12

firewall: add note (bsc#1206320)

---

xml/selinux.xml

Replace support with consulting for further assistance on the SELinux policy 
[DOCTEAM-661](https://jira.suse.com/browse/DOCTEAM-661)
- SLE 12

Security Guide: replaces support with consulting

---

xml/security_ldap_ca.xml

Doc improvements for Section 5.9
[Jira](https://jira.suse.com/browse/DOCTEAM-1008)
- SLE 12

BZ1212001: draft content

---

xml/security_ldap_ca.xml

BZ1212001: cherry pick of approved content

---

xml/selinux.xml

- [Jira](https://jira.suse.com/browse/DOCTEAM-1026)
- SLE 12

BZ1212702: adds the correct path

---

xml/xen_virtualization_vhost.xml

* bsc#1210855
- [] SLE 15 SP1
- SLE 12

Tboot not supported by Xen (bsc#1210855)

---

xml/.dir-locals.el
xml/adm_support.xml
xml/apps_libreoffice.xml
xml/ay_partitioning.xml
xml/libvirt_connect.xml
xml/networkmanager.xml
xml/nm.xml
xml/qemu_guest_installation.xml
xml/security_aide.xml
xml/storage_lvm.xml
xml/xm_vs_xl.xml

Fixed empty inlines

---

xml/klp.xml

Added note about uname command

---

xml/klp.xml

uname command not reflecting live patches

---

xml/user_management.xml

Corrects **unlocked accounts** section
[Jira](https://jira.suse.com/browse/DOCTEAM-395)
- SLE 12

BZ1191920: corrects unlocked accounts

---

xml/tuning_logfiles.xml

Revised content about X.org log files.
* https://bugzilla.suse.com/show_bug.cgi?id=1213570
* https://jira.suse.com/browse/DOCTEAM-1065
- SLE 12

Revised content about X.org log files

---

xml/yast2_gui.xml

Installed YAST modules may differ for GUI and non-GUI (bsc#1191369)

---

xml/virt_support.xml

Added vmware esxi 8 as a supported host (bsc#1213238)

---

xml/net_samba.xml

Jhalackova sle#11102

---

xml/yast2_userman.xml

Added important system groups (bsc#1211168)

---

xml/art_virtualization-best-practices.xml

* bsc#1210642
* jsc#...
- SLE 12

Virt Best Practices: add scsi persistent reservation on multipathed i/o

---

xml/yast2_sound.xml

Added warning about manually touching sound setup

---

l10n/sles/ar-ar/xml/security_ldap_docker_container.xml
l10n/sles/cs-cz/xml/security_ldap_docker_container.xml
l10n/sles/de-de/xml/security_ldap_docker_container.xml
l10n/sles/es-es/xml/security_ldap_docker_container.xml
l10n/sles/fr-fr/xml/security_ldap_docker_container.xml
l10n/sles/hu-hu/xml/security_ldap_docker_container.xml
l10n/sles/it-it/xml/security_ldap_docker_container.xml
l10n/sles/ja-jp/xml/security_ldap_docker_container.xml
l10n/sles/ko-kr/xml/security_ldap_docker_container.xml
l10n/sles/pl-pl/xml/security_ldap_docker_container.xml
l10n/sles/pt-br/xml/security_ldap_docker_container.xml
l10n/sles/ru-ru/xml/security_ldap_docker_container.xml
l10n/sles/zh-cn/xml/security_ldap_docker_container.xml
l10n/sles/zh-tw/xml/security_ldap_docker_container.xml
xml/vnc.xml

Removed vncserver from VNC docs

---

xml/systemd.xml

* bsc#1212777
* jsc#...
- SLE 12

Updated drop-in files section (bsc#1212777)

---

xml/book_tuning.xml
xml/tuning_dynamic_debug.xml

Short introduction to dynamic debug.
* bsc#https://bugzilla.suse.com/show_bug.cgi?id=1176726
* jira#https://jira.suse.com/browse/DOCTEAM-228
- SLE 12

Dynamic debug for the kernel

---

xml/art_admin_slemicro_podman.xml

Jhalackova adding skopeo

---

xml/system_repair.xml

Added extended info about Btrfs (bsc#1214914)

---

xml/suse_sw_packages.xml

Removed obsoleted cron file descriptions

---

l10n/sles/ja-jp/xml/suse_sw_packages.xml

Remove cron content for Japanese (see https://github.com/SUSE/doc-sle/commit/622cc381ffb92503697fb68f1c81e90f0429138a for English)
* bsc#1215608
- SLE 12

rm cron bsc#1215608

---

l10n/sles/ja-jp/xml/suse_sw_packages.xml

Remove cron content for Japanese (see https://github.com/SUSE/doc-sle/commit/622cc381ffb92503697fb68f1c81e90f0429138a for English)
* bsc#1215608
- SLE 12

rm cron bsc#1215608 ja

---

l10n/sles/ja-jp/xml/suse_sw_packages.xml

rm cron and resolve merge confl

---

xml/virt_support.xml

Suspend and hibernate modes are not supported on Xen host (bsc#1214405)

---

xml/security_ldap_migrate_test.xml

Correction of the existing pass through commands
[BZ1215568](https://bugzilla.suse.com/show_bug.cgi?id=1215568)
- SLE 12

DOCTEAM-1122:corrects the pass pass-through command

---

xml/ay_software.xml

Fixed BSC#1213801.

---

xml/ay_bootloader.xml

Jhalackova bsc#1215816

---

xml/physical_security.xml

Document USBGuard
[Jira](https://jira.suse.com/login.jsp?os_destination=%2Fbrowse%2FSLE-21378)
- SLE 12

[WIP]SLE-21378: adds USBGuard content

---

xml/ay_users_groups.xml

* bsc#1216762
* jsc#...
- SLE 12

Rephrased the password settings.

---

xml/apparmor_whatimmunize.xml
xml/audit_components.xml
xml/physical_security.xml
xml/security_ad_support.xml
xml/security_auth.xml
xml/security_kerberos.xml
xml/security_ssh.xml
xml/security_vpnserver.xml
xml/security_vpnserver_yast.xml
xml/slemicro_security_selinux.xml

The scope of this PR covers:
- where applicable remove usage of will and convert to present tense.
- Remove fluff words  
* bsc#...
* jsc#...
- SLE 12

Security guide: tense and fluff

---

xml/xen_administrating.xml

Remove 'High Availabity _Extension_' (found one issue in the Virt.  Guide). 
* jsc#DOCTEAM-1133
- SLE 12

HA Extension

---

xml/storage_filesystems.xml
xml/storage_raid.xml

Remove 'High Availabity _Extension_'. Stumbled across two related issues (after the recent update of the `&hasi;` entity). 
* jsc#DOCTEAM-1133
@lvicoun : Could you please backport to all supported maintenance branches of SLE & SLE Micro? Many thanks!

HA Extension and related fixes

---

xml/rmt_install.xml

* bsc#1216101
* bsc#1216193
- SLE 12

Minor updates to RMT on Kubernetes

---

xml/yast2_ncurses.xml

https://jira.suse.com/browse/DOCTEAM-984
- SLE 12

rm empty element main

---

xml/yast2_ncurses.xml

https://jira.suse.com/browse/DOCTEAM-984
- SLE 12

rm empty element SP5

---

xml/adm_support.xml
xml/apps_libreoffice.xml
xml/ay_partitioning.xml
xml/nm.xml
xml/qemu_guest_installation.xml
xml/security_aide.xml
xml/xm_vs_xl.xml
xml/yast2_ncurses.xml

https://jira.suse.com/browse/DOCTEAM-984
- SLE 12

rm empty elements SP4

---

xml/adm_support.xml
xml/apps_libreoffice.xml
xml/ay_partitioning.xml
xml/nm.xml
xml/qemu_guest_installation.xml
xml/security_aide.xml
xml/security_ssh.xml
xml/xm_vs_xl.xml
xml/yast2_ncurses.xml

https://jira.suse.com/browse/DOCTEAM-984
- SLE 12

rm empty elements SP3

---

xml/adm_support.xml
xml/apps_libreoffice.xml
xml/nm.xml
xml/qemu_guest_installation.xml
xml/security_aide.xml
xml/xm_vs_xl.xml

* https://jira.suse.com/browse/DOCTEAM-984
- SLE 12

remove empty line elements

---

xml/apps_libreoffice.xml

Remove old remarks and add links to LibreOffice help about certificates
* https://jira.suse.com/browse/DOCTEAM-1074
- SLE 12

rm old remarks add links for cert

---

doc-kit.conf
xml/art_minimal-vm.xml
xml/common_intro_available_doc.xml
xml/common_intro_convention.xml
xml/common_intro_feedback.xml
xml/generic-entities.ent
xml/rmt_install.xml
xml/software_management.xml

Apply doc-kit update and fix minvm entities
* bsc#...
* jsc#...
- SLE 12

Doc kit minvm update

---

xml/security_firewall.xml

[DOCTEAM-898](https://jira.suse.com/browse/DOCTEAM-898)
- SLE 12

[WIP]:removes the redundant statement

---

xml/security_firewall.xml

removes redundant statement

---

xml/security_firewall.xml

Removes redundant statement in the chapter intro
[DOCTEAM-898](https://jira.suse.com/browse/DOCTEAM-898)
- SLE 12

 removes redundant statement in the chap intro

---

xml/systemd.xml

Update systemd drop-ins

---

xml/snapper.xml

Better wording on rollback requirements

---

xml/security_fips.xml

Remove the word "sales rep"
[DOCTEAM-1258](https://jira.suse.com/browse/DOCTEAM-1258)
- SLE 12

Docteam-1258: Fixes the sales rep 

---

xml/security_fips.xml

removes sales rep

---

xml/rmt_install.xml

RMT: quote proxy credentials (bsc#1219109)

---

xml/adm_sudo.xml

Updated sudo chapter with smartdocs content

---

xml/systemd.xml

Added tip about using systemd in WSL (jsc#PED-309)

---

xml/security_fips.xml

To add steps to enable FIPs
[PED-6440](https://jira.suse.com/browse/PED-6440)
- SLE 12

[WIP]PED-6440:adds steps to enable fips

---

xml/security_fips.xml

To modify the imp notes and add steps to enable FIPs 
[PED-6440](https://jira.suse.com/browse/PED-6440)
- SLE 12

[WIP]PED-6440: note modification and steps to enable fips

---

xml/security_fips.xml

To add steps to enable FIPs
[PED-6440](https://jira.suse.com/browse/PED-6440)
- SLE 12

[WIP]PED-6440:steps to enable fips

---

xml/grub2.xml

Some grub Xen options are better explained (bsc#1219504)

---

xml/MAIN.SLE-Micro.xml
xml/MAIN.SLEDS.xml
xml/MAIN.opensuse.xml
xml/art-kubevirt.xml
xml/art-nvidia-vgpu.xml
xml/art_admin_slemicro_cockpit.xml
xml/art_admin_slemicro_podman.xml
xml/art_admin_slemicro_selinux.xml
xml/art_amd-sev.xml
xml/art_installation-sleds.xml
xml/art_minimal-vm.xml
xml/art_modules.xml
xml/art_raspberry-pi.xml
xml/art_virtualization-best-practices.xml
xml/book_admin_slemicro.xml
xml/book_administration.xml
xml/book_autoyast.xml
xml/book_deployment.xml
xml/book_deployment_slemicro.xml
xml/book_gnome-user.xml
xml/book_reference-opensuse.xml
xml/book_rmt.xml
xml/book_security.xml
xml/book_security_slemicro.xml
xml/book_startup-opensuse.xml
xml/book_storage.xml
xml/book_tuning.xml
xml/book_upgrade.xml
xml/book_upgrade_slemicro.xml
xml/book_virtualization.xml

Adding metadata to SLE:
* `<meta name="task">`
* `<meta name="series">`
* Set version to `5.2`
* Add the ITS namespace in root element
* n/a
- SLE 12

Add metadata for SLE

---

xml/ay_partitioning.xml

Description of new AY option
https://jira.suse.com/browse/PED-6407
For SLE (SLE-15-SP6), TW
- SLE 12

Documentation for general/storage/proposal lvm_vg_reuse AY option

---

xml/ay_ask_user_values.xml

Fix for BSC#1217131.

---

xml/rmt_mirroring.xml

RMT sync and mirroring timers elaborated (bsc#1220076)

---

xml/art_installation-sleds.xml

Integrate proofing corrections for the Installation QS Guide from proofing drop 1.
- SLE 12

Installation Quick Start: integrate proofing corrections

---

xml/hardening_pam_stack.xml

Corrects the PAM configuration path
[DOCTEAM-1364](https://jira.suse.com/browse/DOCTEAM-1364)
- SLE 12

DOCTEAM-1364: adds the common-password file

---

xml/art_admin_slemicro_podman.xml
xml/book_autoyast.xml
xml/book_deployment_slemicro.xml
xml/book_security_slemicro.xml
xml/book_upgrade_slemicro.xml

Adding metadata for 5.4.
* bsc#...
* jsc#...
- SLE 12

Jhalackova 5.4 metadata

---

xml/art_admin_slemicro_podman.xml
xml/book_autoyast.xml
xml/book_deployment_slemicro.xml
xml/book_upgrade_slemicro.xml

Adding metadata for docs built from this repository.

Added metadata for docs building from doc-sle.

---

xml/art_admin_slemicro_cockpit.xml
xml/art_admin_slemicro_podman.xml
xml/art_admin_slemicro_selinux.xml
xml/book_admin_slemicro.xml
xml/book_autoyast.xml
xml/book_deployment_slemicro.xml
xml/book_security_slemicro.xml
xml/book_upgrade_slemicro.xml

Adding metadata.
* bsc#...
* jsc#...
- SLE 12

Jhalackova 5.3 metadata

---

xml/art_admin_slemicro.xml
xml/art_admin_slemicro_podman.xml
xml/art_admin_slemicro_selinux.xml
xml/book_autoyast.xml
xml/book_deployment_slemicro.xml

Added metadata to SLE Micro 5.1

---

xml/art_admin_slemicro.xml
xml/art_admin_slemicro_podman.xml
xml/art_admin_slemicro_selinux.xml
xml/book_autoyast.xml
xml/book_deployment_slemicro.xml
xml/book_upgrade_slemicro.xml

Added metadata.
* bsc#...
* jsc#...
- SLE 12

Added metadata.

---

xml/update-alternatives.xml

No custom alternatives for python3 (bsc#1221913)

---

xml/storage_filesystems.xml

Adding a basic info about tmpfs.
* https://bugzilla.suse.com/show_bug.cgi?id=1223129
- SLE 12

Added tmpfs.

---

xml/yast2_userman.xml

Removed secondary group YaST mentions (bsc#1222873)

---

xml/rmt_migrate_from_smt.xml

Updated feature comparison table (bsc#1222686)

---

xml/virt_support.xml

Updated virtualization support info for 15 SP6

---

xml/storage_nfs.xml

Integrate proofing corrections for the Storage Guide from proofing drop 2.
- SLE 12

Storage Guide: Integrate proofing corrections

---

xml/art_installation-sleds.xml
xml/deployment_yast_installer.xml
xml/phrases-decl.ent

Add final fixes for the Installation Quick Starts SLES and SLED.
- SLE 12

Installation QS: final fixes

---

xml/art_modules.xml

Add final fixes for the Modules and Extensions Quick Starts SLES and SLED.
- SLE 12

Modules and Extensions QS: final fixes

---

xml/x11.xml

Change the path
*[DOCTEAM-1373](https://jira.suse.com/browse/DOCTEAM-1373)
- SLE 12

[WIP] - Changed the file path as per the description

---

xml/security_ldap_modules.xml
xml/security_ldap_replication.xml

Remove officially when supported is used.
[DOCTEAM-1375](https://jira.suse.com/browse/DOCTEAM-1375)
- SLE 12

[WIP]DOCTEAM-1375:removes officially

---

xml/ay_configuration_management.xml
xml/deployment_boot_parameters.xml

Created a seperate branch from maintenance to resolve merge conflicts
* bsc#...
* jsc#...
- SLE 12

DOCTEAM-1375: removes officially

---

xml/deployment_prep_zseries.xml

Removes the word "officially"
[DOCTEAM-1375](https://jira.suse.com/browse/DOCTEAM-1375)
- SLE 12

[WIP]DOCTEAM-1375:removes officially: removes officially

---

xml/ay_configuration_management.xml

DOCTEAM-1375:missed an instance from PR1717

---

xml/ay_configuration_management.xml

removes officially

---

xml/xen_virtualization_vhost.xml

Fixed GRUB cmdline specification (bsc#1223261)

---

xml/ulp.xml

Added tip on automating libpulp handling (bsc#1223429)

---

xml/qemu_monitor.xml
xml/xen_xmtoxl.xml

Ref: PR1718 merge conflicts  
* bsc#...
* jsc#...
- SLE 12

part of merge conflicts resolve

---

xml/ay_security_settings.xml

Added available values, changed the default.
* bsc#...
* jsc#...
- SLE 12

Fix for BSC#1223089

---

xml/storage_filesystems.xml

Fixed BSC#1218116.

---

xml/adm_shell.xml
xml/adm_wbem.xml
xml/apache2.xml
xml/fuse.xml
xml/net_basic.xml
xml/net_sync.xml
xml/net_wicked.xml
xml/printing.xml
xml/snapper.xml
xml/yast2_sw.xml
xml/yast2_userman.xml

Applied comments on Admin Guide

---

xml/art_virtualization-best-practices.xml

Integrate proofing corrections for the Virtualization Best Practices from proofing drop 3.
- SLE 12

Virtualization Best Practices: integrate proofing corrections

---

xml/aarch64_inst_problem.xml

Adding how to workaround installation problem.
* bsc#1226285
- SLE 12

Added a fix for BSC#1226285.

---

xml/tuning_systemtap.xml

Corrected URL of SystemTap language reference
* bsc#...
* jsc#...
- SLE 12

Corrected URL of SystemTap language reference

---

xml/storage_filesystems.xml

Added using the modprobe command to mount a file system.
* bsc#...
* jsc#...
- SLE 12

Fix for BSC#1218070.

---

xml/bootconcept.xml

Added a new use-case for recreating initramfs

---

xml/virt_support.xml

Updated virt support status in 15SP5

---

xml/security_ldap_migrate_test.xml

Corrects the typo in the command
[DOCTEAM-1470](https://jira.suse.com/browse/DOCTEAM-1470)
- SLE 12

[WIP]DOCTEAM-1470: corrects typo in command

---

xml/selinux.xml

Corrects the existing command 
[DOCTEAM-1496](https://jira.suse.com/browse/DOCTEAM-1496)
- SLE 12

DOCTEAM-1496:corrects the existing command

---

xml/net_teaming.xml

[DOCTEAM-1549](https://jira.suse.com/browse/DOCTEAM-1549)
- SLE 12

corrects port truncating

---

xml/art_virtualization-best-practices.xml

Warn users about security implications of KSM
* bsc#1219054
- SLE 12
(I marked all that are within active lifetime.)

Virtualization Best Practices: Warn about KSM side channels

---

xml/book_gnome-user.xml

Change assignee for dm:bugtracker
* [DOCTEAM-1596](https://jira.suse.com/browse/DOCTEAM-1596)
- SLE 12
PR reviewer only: Have all backports been applied?

GNOME change bugtracker assignee

---

xml/vt_guestfs.xml

we do not provide this binding
* bsc#...
* jsc#...
- SLE 12

remove PHP binding

---

xml/ulp.xml

[DOCTEAM-1546](https://jira.suse.com/browse/DOCTEAM-1546)
- SLE 12

adds latest openssl version

---

images/src/svg/acls_map_mini.svg

Modify the minimal ACL illustration according to DOCTEAM-1544
* bsc#1229234
* jsc#1544
- SLE 12

Fix DOCTEAM-1544

---

xml/audit_components.xml

The config file needs to be modified.
[DOCTEAM-1686](https://jira.suse.com/browse/DOCTEAM-1686)
- SLE 12

DOCTEAM-1686: change value in a config file

---

xml/security_firewall.xml

Change the command example to external zone
[DOCTEAM-1644](https://jira.suse.com/browse/DOCTEAM-1644)
- SLE 12

DOCTEAM-1644: external zone

---

xml/storage_nfs.xml

Fix for BSC#1231542

---

xml/deployment_manual_installation.xml
xml/storage_lvm.xml

Fixed BSC#1236848

---

xml/ulp.xml

DOCTEAM-1712: remove sp version

---

xml/ulp.xml

DOCTEAM-1712: removes sp version

---

xml/ulp.xml

DOCTEAM-1648: change the rm name

---

xml/deployment_prep_zseries_prep_secure_boot.xml

Update of IBMZ boot related stuff.
* bsc#...
* jsc#...
- SLE 12

Fix for BSC#1237387

---

xml/net_config_files.xml
xml/net_yast.xml

DOCTEAM-1721: HOSTNAME replaced with hostname

---

xml/security_ldap_active_directory_sync.xml
xml/security_ldap_migrate_test.xml
xml/security_ldap_replication.xml

DOCTEAM-1702: adds element to keep diagram together

---

l10n/micro/de-de/images/src/svg/partitioning-keep1.svg
l10n/micro/de-de/images/src/svg/rules_flow.svg
l10n/micro/ja-jp/images/src/svg/partitioning-keep1.svg
l10n/micro/ja-jp/images/src/svg/rules_flow.svg
l10n/micro/ja-jp/xml/deployment_boot_parameters.xml
l10n/micro/ja-jp/xml/deployment_images_procedure.xml
l10n/micro/ja-jp/xml/deployment_manual_installation.xml
l10n/micro/ja-jp/xml/deployment_prep_aarch64_boot.xml
l10n/micro/ja-jp/xml/deployment_prep_x86_boot.xml
l10n/micro/ja-jp/xml/deployment_prep_zseries_prep_i.xml
l10n/micro/ja-jp/xml/deployment_remote.xml
l10n/micro/ja-jp/xml/deployment_selfinstall_procedure.xml
l10n/micro/ja-jp/xml/planning.xml
l10n/micro/zh-cn/images/src/svg/partitioning-keep1.svg
l10n/micro/zh-cn/images/src/svg/rules_flow.svg
xml/networkmanager.xml

* Correct validation errors for: de-de, ja-jp, zh-cn
* Remove SVG images for de-de, ja-jp, and zh-cn which are not referenced in XML

Correct validation errors for SLE Micro 5.3

---

l10n/micro/ja-jp/xml/common_intro_typografie_i.xml
l10n/micro/ja-jp/xml/deployment_boot_parameters.xml
l10n/micro/ja-jp/xml/deployment_manual_installation.xml
l10n/micro/ja-jp/xml/deployment_prep_zseries_prep_i.xml
l10n/micro/ja-jp/xml/deployment_remote.xml
l10n/micro/ja-jp/xml/planning.xml
xml/networkmanager.xml
xml/storage_lvm.xml

* Correct validation errors for: de-de, ja-jp, zh-cn
* No missing or duplicated images found

Correct validation errors for SLE Micro 5.2

---

l10n/micro/ja-jp/xml/common_intro_typografie_i.xml
l10n/micro/ja-jp/xml/deployment_boot_parameters.xml
l10n/micro/ja-jp/xml/deployment_manual_installation.xml
l10n/micro/ja-jp/xml/deployment_prep_aarch64_boot.xml
l10n/micro/ja-jp/xml/deployment_prep_x86_boot.xml
l10n/micro/ja-jp/xml/deployment_prep_zseries_prep_i.xml
l10n/micro/ja-jp/xml/deployment_remote.xml
l10n/micro/ja-jp/xml/planning.xml
l10n/micro/zh-cn/xml/deployment_prep_zseries_prep_i.xml
xml/networkmanager.xml
xml/storage_lvm.xml

* Correct validation errors for: de-de, ja-jp, zh-cn
* No missing or duplicated images found

Correct validation errors for SLE Micro 5.1

---

xml/art-kubevirt.xml
xml/art-nvidia-vgpu.xml
xml/art_amd-sev.xml
xml/art_modules.xml
xml/art_raspberry-pi.xml
xml/art_virtualization-best-practices.xml
xml/book_administration.xml
xml/book_gnome-user.xml
xml/book_rmt.xml
xml/book_security.xml
xml/book_storage.xml
xml/book_tuning.xml
xml/book_virtualization.xml

Fix metadata: `<meta name="task" its:translate="no">`. This was erroneously set to "yes" in some deliverables.

for tasks: its -> no

---

xml/sle_update_online.xml

Integrate proofing corrections for the Upgrade Guide from the proofing drop.
* bsc#...
* jsc#...
- SLE 12

Upgrade Guide: integrate proofing corrections

---

xml/ay_control_file.xml
xml/ay_partitioning.xml

Integrate proofing corrections for the AutoYast Guide from the proofing drop.
* bsc#...
* jsc#...
- SLE 12

AutoYast Guide: integrate proofing corrections

---

xml/deployment_boot_parameters.xml
xml/deployment_expert_partitioner_encryption.xml
xml/deployment_prep_zseries_prep_secure_boot.xml
xml/deployment_yast_installer.xml
xml/phrases-decl.ent

Integrate proofing corrections for the Deployment Guide from the proofing drop.
* bsc#...
* jsc#...
- SLE 12

Deployment Guide: integrate proofing corrections

---

xml/security_fips.xml

[DOCTEAM-1794](https://jira.suse.com/browse/DOCTEAM-1794)
- SLE 12

[WIP]DOCTEAM-1794: adds relevant note for fips

---

xml/chrony.xml

Integrate proofing corrections for the Administration Guide from the proofing drop.

Administration Guide: integrate proofing corrections

---

xml/security_ldap_docker_container.xml

[DOCTEAM-1839]()https://jira.suse.com/browse/DOCTEAM-1839
- SLE 12

DOCTEAM-1839: adds correct path

---

xml/security_kerberos.xml

[DOCTEAM-1836](https://jira.suse.com/browse/DOCTEAM-1836)
- SLE 12

DOCTEAM-1836: adds path

---

xml/grub2.xml

[DOCTEAM-1830](https://jira.suse.com/browse/DOCTEAM-1830)
- SLE 12

DOCTEAM-1830: corrects hd

---

xml/grub2.xml

[DOCTEAM-1832](https://jira.suse.com/browse/DOCTEAM-1832)
- SLE 12

DOCTEAM-1832: grub2

---

xml/grub2.xml

docteam1830 :hd

---

xml/uefi.xml

[PED-12543](https://jira.suse.com/browse/PED-12543)
- SLE 12

PED-12543: adds a sub chap for revocation list

---

xml/libvirt_managing.xml

Document save image formats and new parallel save/restore support
* jsc#PED-12599
- SLE 12

Parallel save restore

---

xml/virt_support.xml

Update support for Guest and Host with SP7, as the table format is not trivial not sure the layout will be fine, please check. Also add some information about CoCo and SP7.
* bsc#...
* jsc#...
- SLE 12

Update support for Guest and Host with SP7, also CoCo info udpated

---

xml/rmt_install.xml

broken link

---

xml/virt_support.xml

add Windows 2025
Update the list of supported windows server
This is for SLE15SP7.
None
- [ X] SLE 15 SP7/openSUSE Leap 15.7 *(current `main`, no backport necessary)*
The doc team member merging your PR will take care of the following tasks and will tick the boxes if done.

Update virt_support.xml windows support
