SUSE/doc-sle

xml/vt_docker_quick.xml

Make it clear we are going to support only the Docker images built via the Docker build system.
Ping @eotchi and @taroth21

Docker quickstart: clarify supportability of Docker images

---

xml/vt_best_practices.xml

Add a sub-section about autoballooning and setting Domain-0 memory
to the Memory and Pages section.

vt-best-practices: Add a section describing Xen autoballooning

---

DC-SLES-amazon-ecs
xml/art_sle_amazon_ecs.xml

This article describes how to use the ECS image provided by the
public cloud development team in Amazon's container service.
Thanks to toms for migrating my db4 sources to db5

Added article about Amazon EC2 Container Service

---

xml/vt_docker_quick.xml

The Portus section has been improved in order to contain all the latest
documentation. This way, customers will be able to have Portus up and ready for
usage.
Ping @eotchi, @taroth21, @flavio and @jordimassaguerpla
Signed-off-by: Miquel Sabaté Solà <msabate@suse.com>

Updated the Docker quickstart to improve the Portus section

---

xml/ay_bigfile.xml

`haspcmcia` is not used since SLE 12 (including 'SP0'). Should I create a PR also against `develop` branch?
Thanks!

Remove haspcmcia as it's not used by AutoYaST anymore

---

xml/sle_update_migration.xml

Changed reference from YaST->System to YaST-Software
I just tested the Online Migration module, and it was under Software, not System.

Small grammar correction

---

xml/ay_bigfile.xml

* Adapt 'config' to the new 'copy_config' name.
* Fix 'device'.

Update importing ssh keys/configuration attributes

---

xml/sle_update_upgrading.xml

This adds a note about the new check for free space in YaST during SP installation and also removes some whitespace.
The reorganization of the "General Preparations" section caused some id changes. Is that ok?

feature/fate317784: Implement a check and warning to make sure we don't start a Service Pack migration with insufficient disk space

---

xml/apache2.xml

The first sentence could be understood as if the sysconfig file were the apache configuration before.

Clarify configuration location of apache2 instance

---

xml/vt_best_practices.xml

Ongoing work to certify SAP HANA on KVM revealed some shortcomings
in the NUMA related content of the Virtualization Best Practices
Guide. This rather large change attempts to clarify and restructure
the NUMA related information.

VT Best Practices: NUMA related improvements

---

xml/ay_bigfile.xml

Fixes some typos in the `self_update_url` documentation.
Thanks!

Fix typos in the self_update_url documentation

---

xml/ay_bigfile.xml

- fixed language -> languages (secondary languages)
- adjusted example for languages (it did not make sense to have en_GB for both pripary and secondary language)
- added note about fixing unknown language by replacing with the default one en_US (bsc#991001)
The profile still validates using `daps`.

Adjusted `Language` option

---

xml/vt_guestfs.xml

Here are a bunch of changes for SLES12 SP2 reflecting the libguestfs upgrade.

VT: fixed guestfs documentation after update

---

xml/ay_bigfile.xml

This PR was started to document the new [fate#319471](https://fate.suse.com/319471) feature in AutoYaST. However, I've ended up rewriting the whole users section. Now `<groups>`, `<login_settings>` and `<user_defaults>` elements are documented. Moreover several missing options in the `<users>` group have been added.
You can check the result in [w3.suse.de](https://w3.suse.de/~igonzalezsosa/autoyast/handbook/configuration.html#Configuration.Security.users_and_groups).
But I need the review from some docu-team member, please.

Rewrite AutoYaST users section

---

xml/ay_bigfile.xml
xml/inst_yast2.xml

Changes included in this PR:
* Add installer self-update information to the deployment guide
* Remove a duplicated section regarding SUSE registration in the AutoYaST guide.
* Update self-update information in AutoYaST guide.
You can check the final result here:
* [AutoYaST guide](https://w3.suse.de/~igonzalezsosa/doc-sle/autoyast-self-update/)
* [Deployment guide](https://w3.suse.de/~igonzalezsosa/doc-sle/book.sle.deployment/cha.inst.html#sec.i.yast2.self_update): [self_update boot parameter](https://w3.suse.de/~igonzalezsosa/doc-sle/book.sle.deployment/cha.inst.html#sec.i.yast.start.parameters.self_update) and [the process](https://w3.suse.de/~igonzalezsosa/doc-sle/book.sle.deployment/cha.inst.html#sec.i.yast2.self_update).
YaST documentation has been updated to include information …

Add self-update documentation

---

xml/vt_tools.xml

Since SLES 12SP2, USB devices can be automatically redirected by
virt-manager or virt-viewer. Add notes on how to disable this feature
on these tools.

VT: add a note to disable USB auto-redirection

---

xml/ay_bigfile.xml

- Obviously it's 1000MB instead
- Found by a random scanning through the docs
- See section https://www.suse.com/documentation/sles-12/singlehtml/book_autoyast/book_autoyast.html#ay.auto_partitioning for the previous version

Fixed "100MB == 1 Gigabyte"

---

xml/ay_bigfile.xml

Subvolumes handling in AutoYaST has been improved, as described [in this gist](https://gist.github.com/imobachgs/edb139cd85656dfaaa0ef97c28f51ae2#improved-autoyast-btrfs-subvolumes-handling). This PR adds documentation about those changes.
These changes are not shipped by default in SLE 12 SP2. Is `develop` the right branch to merge those changes?

Update Btrfs subvolumes information in AutoYaST

---

xml/inst_yast2.xml

Made it clear that self_update for YaST is a boot parameter. The link for further details does not make that fact clear immediately.

stated that self_update is a boot parameter

---

xml/deployment_prep_zseries.xml
xml/sle_update_upgrading.xml

All update paths for zSystems require a special kernel parameter. Added a note in the "Upgrading SUSE Linux Enterprise" chapter and added the parameter in the parmfile section.
https://bugzilla.suse.com/show_bug.cgi?id=1010771&GoAheadAndLogIn=1

zSystem requires Upgrade=1 parameter for upgrade

---

xml/storage_fcoe.xml
xml/storage_iscsi.xml

/usr and /var are not supported mount points for iSCSI and FCoE
https://bugzilla.suse.com/show_bug.cgi?id=1010297
uses text from https://bugzilla.suse.com/show_bug.cgi?id=1012335#c28

Mount Points with FCoE or iSCSI

---

images/src/svg/upgrade-paths.svg
xml/sle_update_upgrading.xml

... as requested by BSC#1016470
* uses SUSE color palette
* no image border

Figure showing available Upgrade Paths to SLE 12 SP2

---

xml/sle_update_upgrading.xml

The docu was still "describing" the update to SP1 instead of SP2.
Fix for https://bugzilla.novell.com/show_bug.cgi?id=1016464

Updates are now referencing SLE12 SP2 instead of SP1, bsc#1016464

---

xml/libvirt_overview.xml

Provide a more accurate description of why xendomains and libvirtd
conflict, including a simple example.

libvirt: clarify description of xendomains and libvirtd conflict

---

xml/vt_best_practices.xml

The Virtualization Best Practices doc has a mis-identified
qcow2 image parameter. The string 12-cache-size (twelve)
should instead read l2-cache-size (ell two, as in level 2).
Signed-off-by: Bruce Rogers <brogers@suse.com>

Fix mis-identified parameter for qcow2 images

---

xml/vt_best_practices.xml

The patch provides a few corrections to section "4.5 CPUs". It
also adds a new subsection describing migration considerations for
selecting a virtual CPU model and features.
This documentation improvement is part of the solution for
bsc#1006997.

VT best practice: Improve vCPU section

---

xml/deployment_docupdates.xml
xml/inst_yast2.xml

Based on comment #16 of FATE#320750

Z requires NPIV enabled for automatic LUN scanning, fate#320750

---

xml/vt_best_practices.xml

Section 3.2 recommends using qemu-system-x86_64 over qemu-system-i386.
This is a fine recommendation for KVM, but the opposite is true for
Xen. Clarify the section by adding notes about the preferred qemu
binary for both KVM and Xen.
Note: This change is the result of user comment in bugzilla
https://bugzilla.suse.com/show_bug.cgi?id=1037985#c4

vt best practices: Clarify note about qemu binary

---

xml/ay_bigfile.xml

* Add documentation for enable_snapshots.
* Add missing RAID types.
* Fix a typo.

Small AutoYaST documentation fixes

---

xml/vt_best_practices.xml

Add description of setting Domain-0 minimum and maximum memory
allocations using the dom0_mem parameter.

VT best practices: improve description of dom0_mem parameter

---

xml/docker_building_images.xml
xml/vt_docker_quick.xml

Do not use the zypper's `gpg-auto-import-keys` flag when installing software, this is unneeded and causes security issues.
Fixes bsc#1048279
Signed-off-by: Flavio Castelli <fcastelli@suse.com>

Fix all the docker build instructions

---

xml/libvirt_configuration.xml

Add a section to the libvirt documentation on using macvtap
to share a host network interface.

vt-doc: Add section on using macvtap

---

.travis.yml

I think, after all, validating with remarks is useless:
* I created a remark in an illegal position and tried to validate with
and without remarks -> validation failed both times.
* I created a remark in a position where the document would be invalid
if not for the remark -> it validated both times.
Sorry for arguing for validation with and without --remarks. Doesn't
seem to make any difference. Not even sure what the parameter --remarks
is good for when validating, ultimately.

Stop validating with --remarks

---

xml/libvirt_configuration.xml

Section "14.10.2 Adding a PCI Device with virsh" of the VT doc
contains example XML for host device passthrough that is not
quite right. The 'function' part of a PCI address is restricted
to one digit with a range of 0-7. The libvirt RNG defines a
pciFunc type as
<define name="pciFunc">
<choice>
<data type="string">
<param name="pattern">(0x)?[0-7]</param>
</data>
<data type="int">
<param name="minInclusive">0</param>
<param name="maxInclusive">7</param>
</data>
</choice>
</define>
In the example XML the function part of the address contains
the value '0x00', which does not validate against the above
schema. This simple patch fixes the example by changing the
value to '0x0'.

vt-doc: fix PCI address in hostdev passthrough example

---

xml/vt_best_practices.xml

Add a section about tuning the fs.aio-max-nr setting when
running large numbers of virtual machines. For more details see
https://bugzilla.novell.com/show_bug.cgi?id=1067729

VT best practices: Add section describing aio-max-nr

---

xml/kvm_support_status.xml
xml/libvirt_managing.xml
xml/qemu_running_vms_qemukvm.xml

This PR contains the changes from #164 and a fix of the indentation.

vt-doc: replace obsolete data-plane with IOThreads

---

xml/hardening.xml

- an attempt to make some statements more precise
- grub does not really access the BIOS to determine how to boot the
host, it's rather the other way around
- introduced a differentation between admin and boot passwords
- hint about boot device limitation, which is often the more interesting
approach than a general boot password

hardening guide: reworked BIOS section

---

xml/hardening.xml

- use zypper examples instead of rpm examples. zypper respects
dependencies and gives a better overview in many cases.
- added a warning about careless removal of packages
- minor grammar changes

hardening guide: reworked the "removing unnecessary packages" section

---

xml/hardening.xml

- completely overhauled the paragraphs, better separating the "before
login", "after login" and terminal/graphical banner topics.
- adjusted the GDM example to match the SLE15 situation
- added references to the upstream manuals

hardening guide: reworked banner section

---

xml/xen_virtualization_vhost.xml

As noted by one of the SE's, the text regarding Xen dom0 memory
management in section 18.2 is a bit outdated. Update the examples
and improve the content.

vt-doc: Improve text describing Xen dom0 memory management

---

xml/ay_bigfile.xml

Interactively, it works like this: (bsc#1075551)
>    When registering SLES4SAP, the same registration code as for the base product needs to be re-entered for the HA extension, which is part of the subscription.
>
>    The installer should assure that for these modules registration code is not asked again.
>    The idea is: Try to register non-free extensions with the same product as base system and only ask for those for which registration does not succeed.
But for the autoinstallation, we require to explicitly state the registration code. This docs change clarifies that.
Related:
- https://github.com/yast/yast-registration/pull/352
- https://bugzilla.suse.com/show_bug.cgi?id=1075551

Registering an extension with its base product registration code

---

xml/security_firewall.xml

I've added a section to the firewall documentation to explain the new approach to handling rpcbind based protocols like NFS and NIS with firewalld.

Firewall rpcbind based protocols

---

xml/vt_best_practices.xml

The existing example for creating a baseline virtual CPU across a
cluster of hosts is not quite right. All host capabilties should be
collected and provided to cpu-baseline, not just the <cpu> blocks
from the various hosts.

vt-best-practice: Fix cpu-baseline example

---

xml/ay_bigfile.xml

Prompted by https://bugzilla.suse.com/show_bug.cgi?id=1083622
YaST Scrum card: https://trello.com/c/esxuIcTv
I wanted to document the CDATA trick to distinguish between a missing element and an empty string.
Then I found out that the docs gets attributes quite wrong so I fixed that.

Document CDATA; clarify config:type.

---

xml/smt_mirroring.xml

There is no org-dropdown on the top-right of SCC anymore. We moved the org-selection to the sidebar on the left quite a while ago :arrow_upper_left: 
I discovered this while looking for something else.
And since I don't have the overview in which other pieces of documentation this step might occur (and since you don't have _Issues_ enabled on this repo ... why, btw?) I open this PR more as a tracking issue to get it fixed in all the places.
Plus, now I'm wondering what else around SCC UI docs might be outdated since we are changing things relativly frequent.
The thing I was actually looking for was, btw, the steps you describe for finding the "Organization (Mirroring) Credentials" in SCC, since I have an open PR (suse/happy-customer#3676) to move them somewhere else and this would need …

Update SMT docs according to new SCC web UI layout

---

xml/libvirt_managing.xml

In a cluster of VM hosts participating in migration, the UID of
qemu user and GID of qemu, kvm, and libvirt groups need to be the
same value. Add a note about the requirement in the "Migration
Requirements" section of the VT doc.
While at it, remove the bogus commment about migrating between Intel
and AMD hosts.
Signed-off-by: Jim Fehlig <jfehlig@suse.com>

vt doc: add a note about user and group ID requirements

---

xml/rmt_client.xml

To configure the installer to use a registration proxy, the FQDN of SMT/RMT is enough. There's no need to append `/connect/`, since the SUSEConnect library takes care of that on its own. In fact, SUSEConnect does not handle paths, and even if `fqdn/connect` is given as the regurl, it will only use `fqdn`, and ignore the path. Giving a path can cause a bug when de-registering a system (bsc#954451).

Remove `/connect/` from SMT URL

---

xml/art_sles_rpi_quick.xml

Reflect SLE15 support of new Model B+ as well as SLE15 having gcc7 now.

Update Quickstart guide for SLE15

---

xml/ay_bigfile.xml

Extend services manager documentation regarding [socket based
activated](https://github.com/yast/yast-services-manager/pull/165) services.

Support for on-demand activated services

---

xml/ay_bigfile.xml

This small PR adds some missing words in the AutoYaST Registration Server section.

Fix typo in autoyast system registration section

---

xml/ay_bigfile.xml

This PR contains the following changes:
* Add the `CD_DMMULTIPATH` to the type attribute
TODO:
Once confirmed, cherry-picking to

Fix bsc#1069992: add missing CD_DMMULTIPATH

---

xml/ay_bigfile.xml

This PR contains:
* a procedure which describes the upgrade process without mentioning the `autoyast` variable
* Add a "missing" line into table.
@imobachgs If there anything else is needed, let me know. Thanks!

Fix bsc#1047650, describe /root/autoupg.xml

---

xml/ay_bigfile.xml

File Name: ay_bigfile.xml
ID: Configuration.Security.groups
XML Example didn't create groups.
Example 4.47: Group Configuration the group tag needs to be of type list. 
Otherwise no groups are created.
Check all items that apply.

group tag needs to be of type list

---

xml/hardware_nvdimm.xml

The (belated) technical review from jthumshirn@suse.de of the NVDIMM section in the SLE15 Admin Guide requested several alterations that also affect SLE12 SP4.
Amendment: replace "filesystem" with "file system" throughout, as per pre-existing edited version and style guide.
Check items that apply.

Nvdimm fix

---

xml/docker_docupdates.xml
xml/docker_registry.xml

In particular, I've added a couple of lines that should address some of
the confusions that our customers have reported.
Fixes SUSE/doc-caasp#115
Bugzilla entry: https://bugzilla.suse.com/show_bug.cgi?id=1109636

portus: expanded the section on Portus

---

xml/ay_bigfile.xml

Bugzilla #1081197
A backport to SLES15 GA is needed.

fixed typos

---

xml/deployment_yast_installer.xml

- Document a Self-Update temporary repository which might be used in some cases during installation.
- The reason is that in some cases there might be used extra `SelfUpdate0` repository during installation and this might be confusing for the users. Let's make it clear.
- This is related to bug https://bugzilla.suse.com/show_bug.cgi?id=1101016
- This change is valid only for SLE15-SP1/Leap 15.1

Document a Self-Update temporary repository

---

xml/ay_bigfile.xml

Working against develop for easier back-porting (I did it against SLE12 SP4 last time, and messed it up.) 
I also noticed a missing parenthesis in the preceding paragraph, and fixed that and the wording around it.
Move the slash in the closing <self_update> tag into the correct position. As per:
https://bugzilla.suse.com/show_bug.cgi?id=1119551

Re-implement fix for BSC #1119551,

---

xml/virt_support.xml

Section "7.1 Supported VM Guests " is missing recently released
distros.
Add recently released distros to the list of supported guests in Virtualization Guide.
- [ x] Minor edit without associated FATE/Bugzilla: no Doc Update required
- [ x] To maintenance/SLE12SP3
- [ x] To maintenance/SLE15SP0

vt doc: Add SLES12 SP4 and SLES15 as supported guests

---

xml/docker_building_images.xml
xml/docker_dockerizing_application.xml

Fixed instructions for SLES 12 SP4, see  [bsc#1122029](https://bugzilla.suse.com/show_bug.cgi?id=1122029).
Pre-built Docker images of SLES are only available via Zypper up to `sles12sp2-docker-image` using
`sudo zypper in sles12sp2-docker-image`
For newer versions, `docker pull` is needed:
`docker pull registry.suse.com/suse/sles12sp4`

Fix bsc#1122029

---

xml/ay_12_migrate_15.xml
xml/ay_bigfile.xml

Oxygen complains about links from the appendix back to the main document, but DAPS validates it and it works fine in the HTML version. So I am removing my "work in progress" comment -- I think that this is good to go.

Removing duplication between main AY article & appendix. (BSC#1104637)

---

xml/ay_bigfile.xml

Minor fix to old style RAID1 example.

AutoYaST: minor fix to old style RAID1 example

---

xml/ay_bigfile.xml

Purpose is to make it explicit that syntax is not shared with autoyast
I have also formatted the name as a command where it is not capitalised or in a title, and made some minor copy edits, including addressing earlier remarks.

Reword linuxrc coverage (BSC#1110431)

---

xml/ay_bigfile.xml

This PR adds information about setting up a Bcache device using
AutoYaST. It is related to fate#325346.
Relevant PRs:
* https://github.com/yast/yast-storage-ng/pull/867
* https://github.com/yast/yast-autoinstallation/pull/497
* https://github.com/yast/yast-schema/pull/50
No.

Add a Bcache section to the AutoYaST handbook

---

xml/storage_nvmeof.xml

resolves https://bugzilla.suse.com/show_bug.cgi?id=1120512 and https://bugzilla.suse.com/show_bug.cgi?id=1132388
Trello: https://trello.com/c/20lJPLKw/593-bug-sle12sp4-nvme-native-multipathing-is-not-enabled-by-default-on-sle12
- [ x] To maintenance/SLE12SP3

NVME multipathing is not enabled by default

---

images/src/svg/new-maintenance-model+ltss.svg
images/src/svg/new-maintenance-model.svg

These images still referenced the 11/12 transition, 12/15 seems more appropriate
This image may need its upgrade paths corrected still, please review:

Update for maintenance model images (WIP)

---

xml/ay_bigfile.xml

- Setting the AutoYaST `product_dir` is a bit complicated for multi product media (like the Package DVD), added more details
- Related to https://bugzilla.suse.com/show_bug.cgi?id=1133406#c7
(No backport required, IMHO SLE15-SP1 or SP2 is enough.)

More details for the AutoYaST "product_dir"

---

xml/sle_update_online.xml

Remove step 3 about to uninstall the packages `yast2-branding-openSUSE` & `yast2-branding-openSUSE-Oxygen`
*Are backports required?* 
maintenance/SLE15SP0 is not needed.

Fix bsc#1133376: Migrate from openSUSE -> SLES

---

xml/deployment_firstboot.xml

QA has started to test YaST Firstboot without any configuration. They just triggered the module with the example configuration provided at `/etc/YaST2/firstboot.xml`. That _template_ contained two enabled steps asking for the license, which produced a lot of confusion among the testers.
So, apart from [performing the necessary changes to have a more reasonable template](https://github.com/yast/yast-firstboot/pull/67), we would like to adjust a little bit the available documentation to slightly encourage the user to configure the `firstboot.xml` control file before using it. 
In other words, this PR try to clarify that provided `firstboot.xml` is just a template.
* https://bugzilla.suse.com/show_bug.cgi?id=1131301
* https://bugzilla.suse.com/show_bug.cgi?id=1131327
* Check all items that …

Update documentation about YaST Firstboot

---

xml/deployment_firstboot.xml

The same that https://github.com/SUSE/doc-sle/pull/434 for `maintenance/SLE-12-SP1`
> ... adjust a little bit the available documentation to slightly encourage the user to configure the `firstboot.xml` control file before using it.

Update firstboot documentation sle12sp1

---

xml/ay_bigfile.xml

…  from deployment guide
SLE 15 introduced a Unified Installer that could install SLES, SLED, SLE_HPC and SLES_SAP all from the same media. SLE 15.1 adds 4 more products including 3 SUMA variants. This commit adds the new short product names to the AY docs.

Update product list in AutoYaST docs to match SLE 15.1 product list

---

xml/suse_l10n.xml

This PR contains the following changes to fix bsc#1119247:
* Mention `localectl` & `/etc/locale.conf`
* Migrated some parts from the release notes
* Adjusted two misaligned screens

Fix bsc#1119247: localectl & /etc/locale.conf

---

xml/deployment_installserver.xml
xml/rmt_install.xml

Added warnings to the RMT guide and the Installation Server § of the Deployment Guide that these 2 functions clash with one another and a single server cannot host both at once.
In response to https://bugzilla.suse.com/show_bug.cgi?id=1136474
****

Added warnings re clash between RMT & Installation server (bsc#1136474)

---

xml/entity-decl.ent
xml/planning.xml

As per @cjschroder's suggestion
Add entities for the products added in bsc#1123063
My previous additions of the new products to the lists in the Deployment Guide did not use entities, as this was the first reference to the new products that can be installed from the Unified Installer. Carla suggested "doing it right" and so I have taken the entities used in the SUMA (AsciiDoc) docs.

Add entities for SUMA Retail and SUMA Proxy

---

xml/art_amd-sev.xml

On the distros where we support AMD SEV, the kernel has been fixed and
virtio-blk disks are now usable with SEV guests. See bsc#1120008 for
more details. Remove the limitation from the AMD SEV article.

AMD SEV article: remove virtio-blk limitation

---

xml/ay_bigfile.xml

- Registering the SLES system is not enough to have access to the system updates,
the updates for `kernel-default` and other system packages are released via the Basesystem module
- So we should recommend to at least register the Basesystem module by default
- Related to https://bugzilla.suse.com/show_bug.cgi?id=1141039
Not necessary.
Feel free to adapt to your style guide and improve the wording. :grinning:

AY Registration - recommend registering the Basesystem module

---

xml/ay_bigfile.xml

With the new add_on_others section in add-ons the user can defined manually any repo which
will be added while the installation.
no. Only Head.

new tag in add-on section ... add_on_others

---

xml/deployment_pxe.xml

PXE/autoyast will fail on SLES 15.x when there are no
free IP addresses in DHCP, even with static assignments
per network client, because of RFC 2132 and RFC 4361
client ID conflicts. solution: send RFC 2132 IDs
- [ x] To maintenance/SLE15SP1
- [x ] To maintenance/SLE15SP0

PXE/autoyast install fails, jira SLE-8071

---

xml/ay_bigfile.xml

Add note to clarify that `crypt_key` is needed when reusing an existing encrypted device.

Add crypt_key note

---

xml/art_amd-sev.xml

The <policy> example in SEV guest XML has bit 2 set, which states that
SEV-ES is required. SEV-ES is not supported on SLE12 SP4 or SLE15 SP1.
Remove that bit from the policy example since it wont work and is
confusing to users.
Fixes: https://bugzilla.suse.com/show_bug.cgi?id=1141095
This fix should be added to any AMD SEV article that is published for SLE12 >= SP4 and SLE15 >= SP1.

AMD SEV article: Fix policy example

---

xml/deployment_prep_aarch64.xml
xml/deployment_prep_aarch64_raspi.xml
xml/entity-decl.ent

Addresses JIRA SLE-4393, SLE-4592, SLE-4262
Add a new subsection under the ARM § of the Deployment Guide. It describes the features and limitations of SLE on RasPi. It links to existing SUSE and RPi Foundation documentation to describe how to deploy from a pre-installed image, how to do an installation from USB media, and some of the significant differences and limitations of the RPi platform.

1st draft of new RPi sub§ under AArch64

---

README.adoc

Updating the README with regards to the recent changes (including the switch from `develop` to `master` as default branch). 
@cjschroder @cwickert @lproven @tomschr @fsundermeyer
This is just for your information.

README: update 'develop' -> 'master'

---

xml/ay_bigfile.xml
xml/deployment_yast_installer.xml

Add a note to the documentation that with the quarterly released media the self-update is not possible (input by jsrain via mail).

yast self-upd disabled for QU

---

xml/sle_update_online.xml

Addresses jsc#SLE-6049 'zypper migration detect SUMA client and present fail message'.
Need to check if the note in the docs applies to both 'zypper migration' and 'yast online migration' (or only to 'zypper migration' as listed in jsc#SLE-6049). 
Also not sure if this doc change needs to be 'backported' to SLE 15 and higher.

online upgrade: add note about SuMa clients

---

xml/ay_12_migrate_15.xml

- Fixes missing `<interface>` attributes
- https://bugzilla.suse.com/show_bug.cgi?id=1153243

Fixed AY firewall example (bsc#1153243)

---

xml/hardware_nvdimm.xml

Add very brief troubleshooting guide for identifying faulty NVDIMMs using the new version of ``ndctl``.
- [] To maintenance/SLE15SP0

Addresses JIRA SLE-5607: add NVDIMM troubleshooting steps

---

xml/tuning_cgroups.xml

Users may encounter former limits not applying to new environments, hence add explanations about limit setting. Also few minor fixes when being around.

Cgroup resource limits

---

xml/common_intro_available_doc_i.xml
xml/common_intro_feedback_i.xml

adjust the 'Feedback' section:
* title 'Feedback' -> 'Providing Feedback'
* correctly profile for openSUSE/SLES/SLED
* modify support-related snippet (with service requests)
* merge Bugzilla info 
* add how to contribute via GH
adjust  'available docs' section:
- remove sentence about docs in installed system
- add that latest updates are available in English version

Update common intros

---

xml/ay_bigfile.xml

The intention of this PR is to clarify how multipath scenarios are handled through AutoYaST. In SLE 15 it is just an alias of `CT_DISK`. See #495 for the SLE 12 documentation update.
I am not sure whether I am opening the PR against the correct branch. Sorry if I did it wrong.

AutoYaST: add some clarification about multipath scenarios

---

xml/book_security.xml
xml/kvm_appendix.xml
xml/libvirt_connect.xml
xml/qemu_running_vms_qemukvm.xml
xml/security_auth.xml
xml/security_vpnserver.xml

The current situation about the YaST CA module is unsatisfying. We need to remove any text which refers to the `security_yast2_ca.xml` file.

Remove Occurances of YaST CA module

---

xml/storage_multipath.xml

The table for prio_args options was not working; this is cleaner and easier to read.
- [x ] To maintenance/SLE15SP1
- [ x] To maintenance/SLE15SP0
- [ x] To maintenance/SLE12SP5
- [ x] To maintenance/SLE12SP4
- [ x] To maintenance/SLE12SP3

Replace ugly table with nice clean variablelist

---

xml/ay_bigfile.xml

The `uuid` property in a `<partition>` section of AutoYaST should only be specified when the user wants to find a certain partition or logical volume to reuse it. It was never intended to be used to enforce a particular UUID for newly created filesystems.
That was not that clear in the documentation that is [available here](https://documentation.suse.com/sles/15-SP1/single-html/SLES-autoyast/). That fact manages to confuse even some YaST developers. All that ended in the introduction of [bug#1148477](https://bugzilla.suse.com/show_bug.cgi?id=1148477)
This pull request should clarify how the uuid property is used.
*Are backports required?* Good question. We are fixing the bug for SLE-15-SP1 and for the upcoming releases. That means the [documentation available for …

AutoYaST: clarify usage of uuid (bsc#1148477)

---

xml/hardware_nvdimm.xml

Specify that SLE supports NVDIMMs on x86-64 and POWER. (Explicitly it is POWER64 but POWER32 is no longer supported at all AFAIK.)
https://bugzilla.suse.com/show_bug.cgi?id=1129957
Thanks to @sknorr for reminding me.

Add mention of which archs support NVDIMM (BSC #1129957)

---

xml/ay_bigfile.xml

Starting in SLE 15 SP2, it is possible to select the encryption method in AutoYaST. To implement such a feature, a new `crypt_method` element has been introduced. Moreover, `crypt_fs` is now deprecated, although it is still supported for the time being.
See https://jira.suse.com/browse/SLE-7376.

Document crypt_method element

---

xml/entity-decl.ent
xml/libvirt_configuration_virsh.xml

Since SLE 12, it is possible to add additional 'heads' to a virtual graphics card to emulate
the video output on multiple monitors. This PR introduces steps to help customers with the setup.

Configuring dual head using libvirt (bsc#1155894)

---

xml/virt_support.xml

resolves bsc#1152949, applies to SLE12SP3/4/5
Update the list of hypervisor hosts that support SLE12SP4 as a guest
- [x ] To maintenance/SLE12SP4
- [x ] To maintenance/SLE12SP3

Update list of supported KVM/Xen hosts for SLE12SP4

---

xml/ay_bigfile.xml

Fix misleading example for autoyast parameter as xml parameter is mandatory.
https://bugzilla.suse.com/show_bug.cgi?id=1143260
all maintained code streams are affected.

fix example for param list (bsc#1143260)

---

xml/libvirt_configuration_virsh.xml
xml/qemu_host_installation.xml

This PR introduces a procedure to configure multiqueue virtio-net via libvirt's virsh.
It also includes XML formatting fixes for relevant fiels.

Configuring multiqueue virtio-net in vorsh (bsc#1129856)

---

xml/ay_bigfile.xml

It is not clear that the AutoYaST `enable_snapshots` can be only applied to Btrfs file systems that are mounted as root (/).
To be honest, I am not sure whether it is clear enough.

AY: Clarify that enable_snapshots only applies to root Btrfs

---

xml/storage_iscsi.xml

This pull request adds a new chapter that covers basic targetcli usage (https://bugzilla.suse.com/show_bug.cgi?id=1153354)

Add a chapter covering the targetcli tool

---

xml/art_sle_modules_quick.xml

* Update guide structure to make sure that the listings of Modules & Extensions appear as an item in the TOC
* Avoid section title with "... explained" because that does not sound like technical docs but like a magazine article
* Update deps of RT module, so we can close jsc#SLE-4304

Update Module Guide

---

xml/ay_bigfile.xml

This PR describes how the partitioning works in AutoYaST. It describes the three different approaches (automatic, guided and expert partitioning) and how you can implement them.
Additionally, it removes the section about `<general><storage>` because:
* `start_multipath` is now documented in the section about multipath,
* `proposal` is now documented in the (new) guided proposal section,
* and `btrfs_set_default_subvolume_name` is not supported anymore.

AutoYaST: improve description of how partitioning works

---

xml/vt_best_practices.xml

The introduction of the "Assigning CPUs" section was just strongly
discouraging CPU overcommit, without much explanation of why this was
the case.
Add some hints about that, and also include some basic advice on how to
decide whether overcommitting may or not be sustainable.
Add the indication to absolutely avoid overcommitting by more than 8
times the number of CPUs. This, right now, comes from a mix of common
sense and experience, but it should be good to have tests that actually
check whether "8 times" is really the best limit.
Signed-off-by: Dario Faggioli <dfaggioli@suse.com>
- I have run `daps -d DC-foobar validate`
- I don't know how to run this through the Travis CI (or does it happen automatically?)
- This commit has gone through some internal review within the Virtualization …

vt_best_practices: reword the CPU assignment/overcommit section

---

xml/virt_support.xml

KVM support statement for ARM64 was missing. This update solves it and
closely specifies supported CPU families.

Tbazant kvm on arm64 bsc#1140138

---

xml/docker_building_images.xml

There is slight difference in the functionality of container-suseconnect on systems that are using RMT/SMT instead of SCC. Add a note about that to the containers guide
For details see also: SUSE/container-suseconnect#37
I am not entirely sure if I got the markup right so feel free to correct that if needed.

docker: Add clarifications about image building when connected to rmt

---

xml/qemu_host_installation.xml
xml/vt_installation.xml

When installing virtualization hypervisors and related tools from YAST,
the module description was not always accurate and installing the `yast2-vm` package was omitted.

Aligned yast2-vm module scope (bsc#1138740)

---

xml/ay_bigfile.xml

Mention that, for compatibility reasons, setting the `partition_nr` to `0` is still supported but deprecated. It applies to SLE 15 based versions.

AutoYaST: Add a note about the old way of using the whole disk

---

xml/sle_update_offline.xml

This update describes why and how to check for changed system-wide
configuration files after the upgrade of RPM packages.

Check for rpmnew and rpmsave files after upgrade (bsc#1155552)

---

xml/ay_bigfile.xml

When referring to multipath devices, it is possible to use any of its paths. Related to https://github.com/yast/yast-storage-ng/pull/1011. Just for SLE 15 SP2.

AutoYaST: Clarify how to refer to multipath devices

---

xml/art_sle_install_quick.xml
xml/deployment_expert_partitioner.xml
xml/deployment_yast_installer.xml

This adds a Warning to the partitioning section of the Quick Install guide with a note about binary/decimal units, as per https://bugzilla.suse.com/show_bug.cgi?id=1155315 
If the working/formatting looks OK then I will insert the same warning in the various other partitioning section.

Add warning to partitioning § describing GB/GiB difference (BSC#1155315)

---

xml/ay_bigfile.xml

SLE 12 documentation does not explain how to use a whole disk (no partitions) as a file system (or as an LVM PV or RAID member). For SLE 15, this feature has been changed and properly documented.

SLE 12 SP5: Using the whole disk as file system in AutoYaST

---

xml/smt_mirroring.xml

Addresses https://bugzilla.suse.com/show_bug.cgi?id=1158682
Fixes a typo in the repo architecture name.

Change "sle-12_x86_64" to "sle-12-x86_64" (BSC#1158682)

---

xml/rmt_migrate_from_smt.xml

RMT import procedure included 2 steps that could be easily merged into 1 step with the same functionality. This update improves that.

Joined 2 clumsy procedure steps into 1 (bsc#1137710)

---

xml/tuning_cgroups.xml

The resource limit section was improved in the following points:
* MemoryAccounting and CPUAccounting options are 'implied' instead of 'required'
* added a note about unified control group hierarchy for selected options + reference how to enable it

Updates to cgroups resource limits (bsc#1132382)

---

xml/rmt_install.xml

Opening firwalld ports is now automated in the YaST RMT module.

Opening firewalld ports using the YaST RMT module (jsc#SLE-4560)

---

xml/rmt_client.xml
xml/rmt_mirroring.xml

If custom repositories do not have a parent product, you cannot register them on the client machines with `SUSEConnect`. This update describes manual steps to add them using the `zypper ar ...` command

Registering stand-alone custom RMT repos on client hosts

---

xml/rmt_install.xml

RMT server service can be propagated/discovered through SLP.
This update describes steps to accomplish it.

Add RMT support for SLP discovery

---

xml/rmt_config_files.xml

Upcoming versions of RMT do have new configuration options.
@tbazant I tought right now might be a good time to add this as well, since it looks like you are working on the RMT documentation.

Add low_speed_limit and low_speed_time to RMT configuration section

---

xml/security_pam.xml

I can’t test how this renders, but now there is a space between -- and MODULE in command example. This should give more explicit command look.
Making the command look correct for readers of the documentation.
I’ve checked only SLED 15-SP1 documentation. Probably also master should be fixed.

Fix command output

---

xml/deployment_yast_installer.xml

This update adds a statement  about VROC support as a RAID volume

Added VROC support as supported RAID volume (bsc#1163804)

---

xml/storage_raid-leds.xml

LEDMON project moved from Sourceforge to Github, this update reflects that.

Updated LEDMON project URL (bsc#1163799)

---

xml/storage_filesystems.xml

duperemove can link duplicate blocks on Btrfs. This updated fixes the information that it should not be used on a large group of files.

'duperemove' can operate on large number of files (jsc#sle-11375)

---

.gitignore
xml/net_wicked.xml

While `ip link set down` deactivates a NIC, `ip link set carrier off' dosconnects it from the network completely. This update adds that new command to the docs.

Disconnecting NIC from network (jsc#SLE-10888)

---

xml/libvirt_managing.xml

Some customers may want to migrate virtual machines running on a
LTSS host to a host running the latest service pack within a major
SLE release, e.g. SLES12 SP2 to SLES12 SP5. Add a note to the
supported migration scenarios that SUSE strives to support such
scenarios but recommends on-site testing.
Partial fix for https://bugzilla.suse.com/show_bug.cgi?id=1164744
- [ x] To maintenance/SLE15SP1
- [ x] To maintenance/SLE15SP0
- [x ] To maintenance/SLE12SP5
- [ x] To maintenance/SLE12SP4

vt doc: Add a note about LTSS in migration scenarios

---

xml/book_sles_docker.xml
xml/docker_building_images.xml
xml/docker_containers.xml
xml/docker_dockerizing_application.xml
xml/docker_installation.xml
xml/docker_overview.xml
xml/docker_registry.xml

Bugfix/bsc#1096276 addresses long-standing bug requesting that our docs link to the upstream documentation on the interactions between Docker containers and the system firewall. Also did a copy-edit on the Docker chapter while I was in there.

Bug 1096276 - Docs: docker: document how to re-enable IP packet forwarding

---

xml/snapper.xml
xml/transactional_updates.xml

--from' options
Resolve Jira #SLE-7372. SLES 15 SP2 only.
New options for creating Snapper and transactional-update snapshots from selected snapshots, rather than the default root filesystem. Also allow stacking changes in transactional-update without rebooting.
no

Document new 'transactional-update --continue' and 'snapper create

---

xml/art_sle_install_quick.xml
xml/ay_12_migrate_15.xml
xml/deployment_boot_parameters.xml
xml/deployment_customize_installation_image.xml
xml/deployment_expert_partitioner_overview.xml
xml/deployment_installserver.xml
xml/deployment_kernelupdate.xml
xml/deployment_mksusecd.xml
xml/deployment_prep_aarch64_media.xml
xml/deployment_prep_x86_media.xml
xml/deployment_prep_zseries_info_i.xml
xml/deployment_prep_zseries_prep_i.xml
xml/deployment_prep_zseries_requirements.xml
xml/deployment_remote.xml
xml/deployment_troubleshooting.xml
xml/entity-decl.ent
xml/mobile.xml
xml/opensuse_update.xml
xml/planning.xml
xml/x86_inst_problem.xml
xml/yast2_sw_addon_osuse.xml
xml/yast2_sw_repo.xml

SLE15SP2 full installation media 1 does not fit on a 2-layer DVD any more.
This update adds the &usbflashdrive; where applicable alongside the legacy DVD as an installation media.

SLE15Sp2 ISO1 too big for DVD (bsc#1167156)

---

xml/ay_networking.xml

Starting in SLE 15 SP2, it is preferred to use a colon to separate channel IDs for s390 devices. The old format, using a space, is still supported. We found a problem dealing with chanids while fixing [bsc#1163149](https://bugzilla.suse.com/show_bug.cgi?id=1163149).
Thanks!

AutoYaST: prefer colon to space to separate chanids

---

xml/ay_configuration_management.xml

Clarifies the layout of the TAR archive you can provide to AutoYaST via the `states_url` element (related to [bsc#1168080](https://bugzilla.suse.com/show_bug.cgi?id=1168080)).
Thanks!

AutoYaST: fix the layout description of the states tarball

---

xml/deployment_pxe.xml

initrd  file sits in boot/{ARCHITECTURE}/loader  directory   not the boot/x86_64/{ARCHITECTURE} directory
in fact /boot/x86_64/{ARCHITECTURE} doesn't exist...
correcting the file location for initrd and also the typo of x86_64/{ARCHITECTURE}
- could not submit a BUG - link gave error (You don't have permission to access "http://www.microfocus.com/LAGBroker?" on this server.)
- don't know if this needs to be backported to other docs
- [ X ] To maintenance/SLE15SP0

fixed location of initrd file

---

xml/apparmor_support.xml
xml/tuning_tracing.xml

This update removes remains of rc<service> scripts that SUSE products used to control systemd services

Remove rc<service> controls of systemd services (jsc#SLE-11624)

---

xml/art_sles_rpi_quick.xml

Explain how to install `bluez` (jsc#SLE-3245).
Update the section to cover Raspberry Pi 4 Model B (jsc#SLE-7276), too.
SLE15-SP1 was in the same situation of not having `bluez` pre-installed. However, Raspberry Pi 4 is new in SLE15-SP2. Missing entities may complicate the backport.

rpi: Update Bluetooth instructions

---

xml/tuning_storagescheduler.xml
xml/tuning_systemresources.xml

Signed-off-by: Andreas Herrmann <aherrmann@suse.com>
Legacy block layer was removed in newer kernels. Remove references and adapt
tuning guide accordingly.

tuning, io: Adaption due to removal of legacy block layer

---

xml/hardware_nvdimm.xml

The translation team have queried what "will be unrolled" means referring to a sector write. I have reworded the paragraph, shortened a long sentence, to clarify the meaning and bring it closer to the common "roll back" (or "rollback") usage.

Reword para about BTT to clarify meaning of rolling back a write op

---

xml/hardening.xml

This update fixes a rule to unmount removable devices without root password prompt.

Unmount removable devices (bsc#1079637)

---

xml/hardening.xml
xml/vt_best_practices.xml
xml/xen_virtualization_vhost.xml

This update reflects that memory auto-balooning is disabled by default since 15 SP1

Auto-balooning disabled by default (jsc#SLE-4267)

---

xml/common_intro_lifecycle_support_i.xml
xml/storage_iscsi.xml
xml/storage_lvm.xml
xml/storage_multipath.xml
xml/storage_nvmeof.xml
xml/storage_raid-leds.xml

Incorporate Dublin's requested changes to the Storage Guide.
2 important notes:
• I found additional uses of "commend" in place of "command" and fixed them. I also fixed some missing punctuation.
• I reformatted the storage_multipath.xml file as the formatting was strange. I also fixed a set of broken ranges with mismatched parentheses: (1-10], (10-20] etc. I have also found this typo in the Debian and Ubuntu docs; I think nobody dared to question it.

Add proofreading changes from Dublin to SLE Storage Guide

---

xml/rmt_rmt-cli.xml

The 'rmt-cli export repos' command runs on online RMT instead of offline. This update fixes that.

'rmt-cli export repos' runs on online RMT

---

xml/nm.xml

NM connection editor is no longer installed by default in SLE15SP2. This update includes a hint
to install it manually in case you need it.

NM connection editor not installed by default (bsc#1169867)

---

xml/art_opensuse_install_quick.xml

The "Ports" tab (aarch64 and ppc64le) of https://software.opensuse.org/distributions/leap page has a link to the openSUSE Startup Guide in the "Documentation" section.  It would be helpful for ARM and Power users, if the Startup Guide would link to the Portals where the user actually can find info.

Add pointer to ARM and Power portals

---

xml/smt_client.xml
xml/smt_mirroring.xml

This update describes steps to change the namespace of an SMT client

Re-register SMT client after changing namespace (bsc#1034676)

---

xml/ay_general_options.xml
xml/deployment_customize_installation_image.xml
xml/deployment_image.xml
xml/deployment_mksusecd.xml
xml/deployment_prep_aarch64_media.xml
xml/deployment_prep_aarch64_raspi.xml
xml/deployment_prep_power.xml
xml/deployment_prep_x86_media.xml
xml/deployment_prep_zseries_info_i.xml
xml/deployment_prep_zseries_prep_i.xml
xml/deployment_prep_zseries_requirements.xml
xml/deployment_pxe.xml
xml/deployment_troubleshooting.xml
xml/deployment_yast_installer.xml
xml/planning.xml
xml/updater_gnome.xml

Integrate all the changes requested by Dublin proofreading of the DepGuide.
One is possibly controversial: we are not sure if "DHCPv6 DHCP Unique Identifier" is necessary. It seems tautological. As requested, I have removed the 2nd occurrence to leave it as "DHCPv6 Unique Identifier". If the longer version is required because it is formally correct, it is trivial to reverse.

Integrate Dublin proofing changes to Deployment Guide

---

xml/xen_host_network.xml

As SUSEFirewall is not among SLE15's any longer, this update tries to translate its configuration to firewalld rules

SuSEFirewall2 config to firewalld for Host-Based Routing in Xen

---

xml/virt_support.xml

This update updates the virtualization support for VMhosts and VMguests.

Virtualization support (jsc#SLE-10325)

---

xml/libvirt_networking.xml

Add a warning about enabling forwarding in the VM host when enabling
a libvirt virtual network. While at it, make some small improvements
in the description of libvirt's virtual networks.
- [x ] To maintenance/SLE15SP1
- [x ] To maintenance/SLE12SP5

vt doc: Improve libvirt network section

---

xml/ay_partitioning.xml

This PR adds information about how to configure a multi-device Btrfs drive in AutoYaST.
(This is new functionality in SLE 15 SP2, which is why this change has been on hold since July 2019. It was in openSUSE long ago.)
Relevant links:
* https://trello.com/c/FsEzGg70/975-3-multi-device-btrfs-support-in-autoyast
* https://jira.suse.de/browse/SLE-3877
I have reformatted @joseivanlopez' text from https://github.com/SUSE/doc-sle/pull/443
Changes from PR #443:
* inserted into the same position in the new, multi-file AutoYast guide
* fixed indentation in the example
* removed `raid5` and `raid6` as per @ancorgs's comment as they are not yet supported

Import @joseivanlopez' Multi-device Btrfs § from PR 443 (JIRA SLE-3877)

---

xml/rmt_config_files.xml

This modification adds a reference describing the "noproxy" option for RMT, as discussed in https://github.com/SUSE/rmt/issues/491 .
This functionality was added by the corresponding pull request in the Typhoeus module: https://github.com/typhoeus/typhoeus/pull/642

issue rmt#491: updating the documentation with new option noproxy

---

xml/docker_building_images.xml

Building in "pay-as-you-go" or "on-demand" instances will require
addtional preparations, because of some specialities in the update
infrastructure. Add a note about that.

docker: add notes about building in on-demand cloud instances

---

xml/rmt_install.xml

Some customers would like to use a custom CA certificate to set up their RMT servers. With this note, we can help point them in the right direction without detailing a process for custom certificates.
No

Added a note about certificate location for RMT

---

xml/libvirt_managing.xml

Fixed https://bugzilla.suse.com/show_bug.cgi?id=1173887
which is due to https://bugzilla.suse.com/show_bug.cgi?id=1170728
This is an L3 customer bug report. 

Add warning to avoid `ntpd -x` when live migrating (BSC #1173877)

---

xml/apparmor_profiles_man.xml
xml/apparmor_repositories.xml

* Update path of AppArmor extra profiles. The extra profiles were moved to /usr/share/apparmor/extra-profiles/ in AppArmor 2.9 (= long ago), see boo#713647
* Drop reference to the AppArmor remote profile repository. It was switched off years ago, and is unlikely to come back.
(AFAIK SLE12 still has AppArmor 2.8.x which uses the old path. However, you might want to drop the mention of the online profile repo in the SLE12 documentation.)

Update path of AppArmor extra profiles

---

xml/xen_config_options.xml

The granularity of vCPUs scheduling in Xen can be specified at boot time

vCPU scheduling (jsc#SLE-10167)

---

xml/tuning_systemresources.xml

Signed-off-by: Andreas Herrmann <aherrmann@suse.com>
Bring tuning guide in sync with what's in maintenance/SLE12SP4 branch.
The reference to BFQ is missing in section about ionice.
This change should be applied to maintenance branches for
SLE15SP1, SLE15SP0, and SLE12SP5.
Branches SLE12SP4 and SLE15SP2 are not affected.

tuning_systemresources: ionice: Refer to BFQ for blk-mq

---

xml/net_samba.xml

The SLE15+ docs have errors regarding mounting SMB1 shares.
no

fix errors regarding mounting SMB1 shares

---

xml/tuning_cgroups.xml

Sync kernel documentation references with kernel version actually used.
n/a
No, this fix is for SLE15SP1 and SLE12SP5.
SLE15SP2 and newer require a slightly different update.
I'll send a separate PR for this.

tuning_cgroups: Fixed references to kernel documentation

---

xml/grub2_yast_i.xml

Added MBR Protective options section to 12.3.1 Boot Loader Location and Boot Code Options
Adding MBR Protective options explanation to that as it's missing
https://bugzilla.opensuse.org/show_bug.cgi?id=1175638

Added MBR Protective options section

---

xml/storage_filesystems.xml

zstd documentation is missing from the Btrfs compression section.
It can be used with SLES 15sp1+.

Btrfs zstd

---

xml/hardening.xml

This adds two new sections to the SLE hardening guide that originate from the SAP HANA hardening guide. The topics aren't specific to SAP. A customer complained about lacking aspects in these two sections. The concerns have been addressed and the content updated and adjusted to the more general audience of the SLE hardening guide.
* bsc#1174501
No

hardening guide: incorporate topics from SAP HANA hardening guide

---

xml/art_jeos_quickstart.xml

Adding "systemd-coredump disabled" in https://susedoc.github.io/doc-sle/master/single-html/SLES-jeos/#sec-jeos-sles-diff
* bsc#1158546
affect all JeOS 15 SPx

Adding "systemd-coredump disabled"

---

xml/art_sle_modules_quick.xml

Fixes bsc-1171085
Better description of L3 support for packages in modules
* bsc#1171085

Update L3 support info

---

xml/storage_filesystems.xml

Increase XFS filesystem max size from 8 to 16 EiB
* bsc#1171801

Increased XFS filesystem max size to 16 EiB (bsc#1171801)

---

xml/rmt_install.xml
xml/rmt_migrate_from_smt.xml

Symlinked directories for storing repo content in RMT were not accurately documented
* bsc#1176516
- [z] This PR applies to older releases as well.

Fixed path for RMT repo locations (bsc#1176516)

---

xml/ay_general_options.xml

The `<partition_alignment>` element [was dropped in SLE 15 GA](https://documentation.suse.com/sles/15-SP2/html/SLES-all/appendix-ay-12vs15.html#sec-ay-12vs15-partitioning-aligning). However, it is still included in an example.

AY: partition_alignment element is drop

---

xml/entity-decl.ent
xml/rmt_migrate_from_smt.xml

Added a tip and example of URL translation for custom repositories on RMT server
* bsc#1176528

Custom repositories translate differently with RMT (bsc#1176528)

---

xml/tuning_kexec.xml

kdump service needs to be restarted after doing manual changes to the documentation. this update duplicates that information to be abvailable where manual changes to config file is mentioned
* bsc#1176838

Duplicated note about restarting kdump service (bsc#1176838)

---

xml/security_ldap.xml

Add useful piece of info from a mail thread with William.

LDAP: how to check 389-ds instance name

---

xml/ay_create_control_file.xml

Just a warning about having sensitive information in the `autoinst.xml` file.
* [bsc#1174202](https://bugzilla.suse.com/show_bug.cgi?id=1174202)

Add a warning about profile permissions

---

xml/ay_custom_user_scripts.xml

Make clear that init-scripts are different from the rest of script types and, therefore, most of the elements are not supported.
* bsc#1176991

Make clear that init-scripts are different from the rest

---

xml/ay_introduction.xml
xml/ay_networking.xml

A regular installation of SUSE Linux Enterprise Server 15 SP2 is performed in a single stage. The auto-installation process, however, has been historically divided in two stages. 
The idea is, that, since SLE-15-SP3, the AutoYaST network configuration, by default, will be done during the `first stage`. This PBI tries to update and extend the current documentation according to the new behavior.
- https://github.com/yast/yast-network/blob/master/doc/autoinstallation.md
- https://bugzilla.suse.com/show_bug.cgi?id=1171922

AutoYaST network configuration updates

---

xml/ay_12_migrate_15.xml
xml/ay_firewall.xml

Examples regarding `start_firewall` and `enable_firewall` are wrong because the `config:type` is missing, which causes the profile to be invalid. The fix should be applied to all SLE 15 based versions documentation.
* [bsc#1176595](https://bugzilla.suse.com/show_bug.cgi?id=1176595)

Fix {enable,start}_firewall config types

---

xml/ay_create_control_file.xml

During validation, now AutoYaST ignores unknown top-level sections. See [bsc#1177173](https://bugzilla.suse.com/show_bug.cgi?id=1177173) for the rationale.
* bsc#1177173

AY: document the new behaviour during validation

---

xml/ay_12_migrate_15.xml
xml/ay_partitioning.xml

The `is_lvm_vg` element was dropped in SLE 15 but we did not mention this fact in the documentation.

"is_lvm_vg" must be replaced by using "type"

---

xml/sle_update_online.xml

LTSS is now available in SLE15SP0, but not newer releases
LTSS must be disabled for upgrades to succeed
* bsc#...
* jsc#SLE-...
| [ x] 15 SP0  | [ ] 

Update SLE15SP0 upgrade to include correct LTSS instructions

---

xml/storage_multipath.xml

To not lose changes made from dracut emergency shell, you need to mount and chroot the system root file system.
Rendered version attached (section 17.15.2)
[sec-multipath-trouble_color_en.pdf](https://github.com/SUSE/doc-sle/files/5465239/sec-multipath-trouble_color_en.pdf)
* bsc#1171581
| [x] 12 SP4  | [ ] 
| [x] 12 SP3  | [ ] 

Described accessing / partition from emergency shell (bsc#1171581)

---

xml/storage_lvm.xml

`lvmetad` was removed from SLE, therefore it needs to be removed from the Storage Guide as well
* bsc#1177006

Removed section on lvmetad (bsc#1177006)

---

xml/book_sle_virtualization.xml
xml/xen2kvm.xml

the xen2kvm guide was previously wrongly moved to an appendix, now targeting it to the correct place in libvirt

Moving xen2kvm to libvirt part

---

xml/storage_filesystems.xml

Columns were 4 instead of 2 (missing rows)

Fix table issue in storage_filesystems.xml

---

xml/audit_components.xml

re https://bugzilla.suse.com/show_bug.cgi?id=1178819
Explain that disabling audit doesn't disable all auditing
| [ x] 15 SP1  | [ ] 
| [x ] 15 SP0  | [ ] 

Describe auditctl -e 0 option in Security Guide

---

xml/security_ldap.xml

This expands and clarifies the steps for creating a new 389ds server instance
for testing, and setting up administration access
See sections 6.3, 6.3.1, and 6.3.2. (PDF attached)
https://jira.suse.com/browse/SLE-16707
https://jira.suse.com/browse/SLE-14732
| [x ] 15 SP1  | [ ] 
| [ x] 15 SP0  | [ ] 
| [ ] 12 SP2  | [ ] 
[cha-security-ldap_color_en.pdf](https://github.com/SUSE/doc-sle/files/5 …

Create sections on setting up a testing instance for 389ds

---

xml/yast2_sw.xml

This fixes a minor typo in the documentation.
No.
| [x] 12 SP4  | [ ] 

yast2_sw: Fix typo (fromq -> from)

---

xml/vt_best_practices.xml

cfq and bfq are both available in earlier releases
https://bugzilla.suse.com/show_bug.cgi?id=1178938
Update Virtualization Best Practices guide with the correct scheduler for SLE 15 SP2 and up

bfq I/O path is the only option for SLE15 SP2 and up

---

xml/ay_partitioning.xml

This PR adds information about setting Btrfs quotas. The code is merged and this PR is ready for review.
Thanks!
Related to: https://github.com/yast/yast-storage-ng/pull/1186.
* jsc#SLE-7742

Add information about setting Btrfs quotas

---

xml/ay_partitioning.xml

Part of ongoing work to convert tables in the AutoYaST Guide to variablelists,
because they render awkwardly in PDF
https://trello.com/c/zMJy4Uqz/151-restructure-autoyast-guide-fix-wide-tables
* bsc#...
* jsc#SLE-...

Convert table to variablelist

---

xml/ay_bootloader.xml
xml/ay_control_file.xml

* Mention that "control file" and "profile" refers to the same thing. Is `<empashis>` the correct tag in this situation?
* Fix the `secure_boot` example.

AutoYaST: "control file" and "profile" are equivalent

---

xml/book_sles_containers.xml
xml/common_intro_target_audience_i.xml
xml/containers-basics.xml
xml/containers-build-tools.xml
xml/containers-buildah-overview.xml
xml/containers-docker-building-images.xml
xml/containers-docker-containerize-app.xml
xml/containers-docker-installation.xml
xml/containers-docker-overview.xml
xml/containers-docker-registry.xml
xml/containers-docker-use.xml
xml/containers-get.xml
xml/containers-intro.xml
xml/containers-orchestration.xml
xml/containers-podman-overview.xml
xml/containers-support.xml
xml/containers-terminology.xml
xml/containers-troubleshoot.xml

* This is the elevnenth PR in a series of 14 PRs
The first column is to be filled by the requester, the second column is to be …

Update Container Guide to sentence case (WIP)

---

xml/tuning_cgroups.xml
xml/tuning_memory.xml
xml/tuning_power.xml
xml/tuning_storagescheduler.xml
xml/tuning_systemresources.xml
xml/tuning_taskscheduler.xml

Mostly names that should be capitalized:
Transparent HugePage
https://www.kernel.org/doc/html/latest/admin-guide/mm/transhuge.html
C-states and P-states
https://software.intel.com/content/www/us/en/develop/blogs/c-states-and-p-states-are-very-different.html
Budget Fair Queueing
https://www.kernel.org/doc/html/latest/block/bfq-iosched.html
X Window System
http://www.opengroup.org/desktop/x/
Completely Fair Scheduler
https://www.kernel.org/doc/html/latest/scheduler/sched-design-CFS.html
Review changes in titles to sentence case. A few corrections that are mostly names that should be capitalized a certain way …

Corrections to title case corrections

---

xml/security_ldap.xml

also some cleanups re creating new 389ds instances

Clarifications and cleanups to managing users and groups

---

xml/book_sle_tuning.xml
xml/tuning_cgroups.xml
xml/tuning_how.xml
xml/tuning_intro.xml
xml/tuning_kexec.xml
xml/tuning_kprobes.xml
xml/tuning_logfiles.xml
xml/tuning_memory.xml
xml/tuning_network.xml
xml/tuning_numactl.xml
xml/tuning_oprofile.xml
xml/tuning_perf.xml
xml/tuning_power.xml
xml/tuning_ptp.xml
xml/tuning_storagescheduler.xml
xml/tuning_systemd_coredump.xml
xml/tuning_systemresources.xml
xml/tuning_systemtap.xml
xml/tuning_taskscheduler.xml
xml/tuning_tracing.xml
xml/utilities.xml

* This is the fifth PR in a series of 14 PRs
The first column is to be filled by the requester, the second column is to be filled by …

Update Tuning Guide to sentence case (WIP)

---

xml/art_amd-sev.xml
xml/art_jeos_quickstart.xml
xml/art_sle_install_quick.xml
xml/art_sle_modules_quick.xml
xml/art_sles_rpi_quick.xml
xml/common_copyright_quick.xml

* This is the seventh PR in a series of 14 PRs
The first column is to be filled by the requester, the second column is to be filled …

Update Quick Start Guides to sentence case (WIP)

---

xml/rmt_backup.xml
xml/rmt_certificates.xml
xml/rmt_client.xml
xml/rmt_config_files.xml
xml/rmt_install.xml
xml/rmt_migrate_from_smt.xml
xml/rmt_mirroring.xml
xml/rmt_overview.xml
xml/rmt_rmt-cli.xml
xml/rmt_systemd.xml
xml/rmt_tools.xml

* This is the twelfth PR in a series of 14 PRs
The first column is to be filled by the requester, the second column is to be filled …

Update RMT Guide to sentence case (WIP)

---

xml/book_sles_storage.xml
xml/storage_degraded_raid.xml
xml/storage_fcoe.xml
xml/storage_filesystems.xml
xml/storage_fs-resizing.xml
xml/storage_intro.xml
xml/storage_iscsi.xml
xml/storage_isns.xml
xml/storage_lvm-snapshots.xml
xml/storage_lvm.xml
xml/storage_mdadm-resize.xml
xml/storage_multipath.xml
xml/storage_multitier-caching.xml
xml/storage_nfs-acl.xml
xml/storage_nvmeof.xml
xml/storage_raid-leds.xml
xml/storage_raid.xml
xml/storage_raid10.xml
xml/storage_raidroot.xml
xml/storage_uuids.xml

* This is the ninth PR in a series of 14 PRs
The first column is to be filled by the requester, the second column is to be filled by …

Update Storage Guide to sentence case

---

xml/art_opensuse_install_quick.xml
xml/book_opensuse_reference.xml
xml/book_opensuse_startup.xml
xml/common_intro_source_code_i.xml
xml/mobile.xml
xml/newbie_bash.xml
xml/newbie_bash_commands_i.xml
xml/newbie_perm_i.xml
xml/opensuse_reference_intro.xml
xml/opensuse_startup_intro.xml
xml/opensuse_update.xml
xml/yast2_sw_addon_osuse.xml
xml/zypper_upgrade.xml

* This is the thirteenth PR in a series of 14 PRs
The first column is to be filled by the requester, the second column is to be …

Update openSUSE guides to sentence case (WIP)

---

xml/ay_create_control_file.xml
xml/ay_dynamic_profiles.xml
xml/ay_erb_templates.xml
xml/ay_pre_scripts.xml
xml/book_autoyast.xml

This PR adds some sections about AutoYaST capabilities to generate dynamic profiles. In SP3 we have added support for "ERB Templates" and a new command to check whether a profile is correct or not (`check-profile`).
As usually, I am open to any change, as I am not even sure about the organization of the contents.
* [bsc#1175735](https://bugzilla.suse.com/show_bug.cgi?id=1175735)

AutoYaST Support for Dynamic Profiles

---

xml/apps_brasero.xml
xml/apps_ekiga.xml
xml/apps_evolution.xml
xml/apps_firefox.xml
xml/apps_gimp.xml
xml/apps_librecalc.xml
xml/apps_libreoffice.xml
xml/apps_librevarious.xml
xml/apps_librewriter.xml
xml/apps_pidgin.xml
xml/apps_totem.xml
xml/backup.xml
xml/book_gnomeuser.xml
xml/gnome_accessibility.xml
xml/gnome_crypto.xml
xml/gnome_custom.xml
xml/gnome_networking.xml
xml/gnome_print.xml
xml/gnome_start.xml
xml/gnome_use.xml
xml/gnomeuser_intro.xml
xml/help_user.xml

* This is the third PR in a series of 14 PRs
The first column is to be filled by the requester, the second column is to be filled by …

Update GNOME User Guide to sentence case (WIP)

---

xml/book_sle_upgrade.xml
xml/sle_update_background.xml
xml/sle_update_backporting.xml
xml/sle_update_offline.xml
xml/sle_update_online.xml
xml/sle_update_preparation.xml
xml/sle_update_upgrading.xml
xml/upgrade_intro.xml

* This is the sixth PR in a series of 14 PRs
The first column is to be filled by the requester, the second column is to be filled by …

Update Upgrade Guide to sentence case (WIP)

---

xml/libvirt_configuration_gui.xml
xml/libvirt_configuration_virsh.xml

See https://bugzilla.suse.com/show_bug.cgi?id=1175218 for details.
Signed-off-by: Jim Fehlig <jfehlig@suse.com>
Improve documentation around device hotplug.
* bsc#1175218

vt-doc: Add note about PCI topology for QEMU Q35 machines

---

xml/libvirt_connect.xml

Our docs still described enabling secure libvirtd connection the old traditional way instead of systemd one.
This update fixes it.
* bsc#1180527
| [x] 12 SP4  | [ ] 
| [x] 12 SP3  | [ ] 

Enable TLS for libvirtd the systemd way (bsc#1180527)

---

xml/ay_networking.xml

Add the `lladdr`element to the interfaces list as it was missing there although it is mentioned by the s390 device documentation (https://doc.opensuse.org/projects/autoyast/#CreateProfile-Network-s390)
* https://bugzilla.suse.com/show_bug.cgi?id=1179876
| [X] 15 SP3  | (`master` only)   

Document the 'lladdr' element (AY networking section)

---

xml/klp.xml

While looking at https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-klp.html I noticed a few glitches. Most importantly, the maintenance branch for 15 SP2 contained fixed version numbers for 15 SP3.
I inserted entities to avoid this and fixed two minor things I spotted along the way (long code lines in PDF, a duplicated punctuation mark). Please backport the fixes to the appropriate older doc versions, too.  
| ----------  | …

Small fixes for KLP

---

xml/ay_bootloader.xml
xml/ay_kernel_dumps.xml
xml/ay_linuxrc_options.xml

When adapting my Autoyast configuration for SLES 15,
I run into some issues
as some items in the documentation are either incomplete or even wrong.
This PR fixes this.
I guess this is wrong for all releases. However, nobody will start an auto-installation on old releases. So no fix is required there. Even 15 SP2 is optional.
| [X] 15 SP3  | (`master` only)   
| [X] 15 SP2  | [ ] 

Extend/fixes the description of some Autoyast parameter

---

xml/common_intro_available_doc_i.xml

Reorganize and shorten info about available documentation. 

intro about available docs: reorg as discussed in SLE writers sync

---

xml/ay_intro.xml
xml/book_autoyast.xml
xml/book_sles_containers.xml
xml/book_sles_rmt.xml
xml/containers-intro.xml
xml/deployment_intro.xml
xml/gnomeuser_intro.xml
xml/kvm_intro.xml
xml/rmt_intro.xml
xml/rmt_overview.xml
xml/security_intro.xml
xml/sle_admin_intro.xml
xml/storage_intro.xml
xml/tuning_intro.xml
xml/upgrade_intro.xml

Streamlining the book introductions. Removed the info about the book structure (as this can be seen from the TOCs), added missing intros to two books and made sure each book has an abstract. 

Streamlining the book introductions 

---

xml/book_sle_deployment.xml
xml/deployment_prep_zseries_prep_i.xml
xml/deployment_yast_installer.xml
xml/planning.xml
xml/snapper.xml
xml/tuning_multikernel.xml

Part 1… up to page 100
Integrating Dublin proofreading changes into the SLE Deployment Guide
Note, some of the changes have also touched on chapters in the Tuning Guide, the Admin Guide, the Snapper guide and others, because sections of these are included or referenced in the Dep Guide.
In the Snapper guide, I found that automated transition to sentence case had removed the capital S from "Snapper" in many titles, so I have manually fixed this for consistency. 
Thus, although all these errors were **found** in proofing the DepGuide, not all the changes are in the DepGuide.
The last change is p75. I have stopped before p105:
> Tip: Using additional drives with ~s~ecure ~b~oot
That is where to continue from.
The first column is to be filled by the requester, the second column is to be …

Integrating proofreading changes into Deployment (& other) guides

---

xml/deployment_boot_parameters.xml
xml/deployment_expert_partitioner_overview.xml
xml/deployment_firstboot.xml
xml/deployment_installserver.xml
xml/deployment_pxe.xml
xml/deployment_troubleshooting.xml
xml/deployment_yast_installer.xml
xml/tuning_multikernel.xml
xml/uefi-httpboot-server.xml
xml/yast2_userman.xml

Covers the remaining proofing corrections from p.100-309), see https://github.com/SUSE/doc-sle/pull/792 for the first part.

Depl. Guide: remaining proofing corrections

---

xml/ay_ftp_server.xml

wide tables do not render well. Using convert-table2variablelist.xsl
in DAPS to make the conversion https://github.com/openSUSE/daps
Thank you Thomas Schraitle!
* bsc#...
* jsc#SLE-...

convert large tables in AY Guide to lists

---

xml/ay_apache_server.xml
xml/ay_ask_user_values.xml
xml/ay_audit_framework.xml
xml/ay_custom_user_scripts.xml
xml/ay_nis_server.xml
xml/ay_samba_server.xml
xml/ay_squid_server.xml
xml/ay_users_groups.xml
xml/ay_windows_domain_client.xml

wide tables do not render well. Using convert-table2variablelist.xsl
in DAPS to make the conversion https://github.com/openSUSE/daps
Thank you Thomas Schraitle!

wide tables in AY Guide do not render well

---

xml/security_ldap.xml

How to manage LDAP modules, some minor corrections

Add section to LDAP guide how to manage modules

---

xml/ay_kernel_dumps.xml
xml/ay_partitioning.xml
xml/ay_rules_classes.xml

some tables are too large and do not render well in HTML
or PDF

Convert too-large tables in AY Guide to variablelists

---

xml/ay_apache_server.xml
xml/ay_ask_user_values.xml
xml/ay_custom_user_scripts.xml
xml/ay_users_groups.xml

some tables are too large and do not render well in HTML
or PDF, converted with wondrous stylesheet by Thomas Schraitle
| [ x] 15 SP2  | [ ]

 Convert too-large tables in AY Guide to variablelists

---

xml/ay_kernel_dumps.xml
xml/ay_rules_classes.xml

some tables are too large and do not render well in HTML
or PDF, converted with wondrous stylesheet by Thomas Schraitle

Final conversion of large tables to lists for AY Guide

---

xml/rmt_mirroring.xml

User needs to enable newly added custom repos attached to a product.
* jsc#DOCTEAM-57

Enable custom repo attached to a product (jsc#DOCTEAM-57)

---

xml/book_tuning.xml
xml/entity-decl.ent
xml/tuning_sapconf.xml
xml/tuning_storagescheduler.xml

Move sapconf section of SLES4SAP to the SLE Tuning Guide
sapconf is for preparing SLES installations to add SAP applications.
saptune is for SLES4SAP.
https://jira.suse.com/browse/SLE-15940

  Move sapconf section of SLES4SAP to the SLE Tuning Guide

---

xml/net_sync.xml

Fix a typo.
* bsc#...
* jsc#SLE-...
| [x] 12 SP5  | [ ]
| [x] 12 SP4  | [ ]
| [x] 12 SP3  | [ ]

typo in net_sync.xml

---

xml/libvirt_configuration_virsh.xml

* bsc#1180139
* jsc#DOCTEAM-66
| [x] 12 SP5  | [ ]
| [x] 12 SP4  | [ ]

Fixed typo in QEMU config path (bsc#1180139)

---

xml/ay_rules_classes.xml

https://jira.suse.com/browse/DOCTEAM-67
| [ x] 15 SP1  | [ ]

final conversion of wide tables to variablelists for SLE15SP1

---

xml/ay_bootloader.xml
xml/ay_control_file.xml
xml/ay_networking.xml

This PR adds documentation for some elements that were missing in the AutoYaST guide. I have tried to organize them in different commits, so it is easy to review and even backport them.
* 1a9e644: add "update_nvram" (**new in SLE 15 SP3**).
* 197257f: add "virt_bridge_proposal" (**new in SLE 15 SP3**).
* 797c3aa: explaining that it is possible to use `t` instead of `config:type` (**new in SLE 15 SP3**).
* 309b4b0: drop the `domain` element from an example. It was deprecated a few releases ago, but we forgot to update the example. **Backport to SP2 if possible**.
* 73d5d16 and 8d30ce6: the introduction of the networking section was somehow confusing. Some elements were not documented while others were just mentioned in the examples. I am not 100% happy with the new text, but I think it is …

AutoYaST: add missing elements

---

xml/ay_networking.xml

cherry-pick 73d5d16 and 8d30ce6b from main, see
https://github.com/SUSE/doc-sle/pull/824
backport updates in Main to SLE15SP2

Ay backports

---

xml/ay_registration_extensions.xml

Remove link to unmaintained Github page, SUSEConnect --list-extensions
is the authoritative source
https://jira.suse.com/browse/DOCTEAM-151
https://bugzilla.suse.com/show_bug.cgi?id=1185014

Clarify SLES extensions lookup

---

xml/ay_auto_installation.xml
xml/ay_bootloader.xml
xml/ay_dynamic_profiles.xml
xml/ay_networking.xml
xml/ay_partitioning.xml

Some last minute corrections before the May 5 proofing drop

A few style corrections to the AY Guide before proofing drop

---

xml/art_raspberry-pi.xml

When building an HTML version of the guide, I noticed additional whitespaces in the text after some links, stemming from whitespaces before the closing tag of the link elements in the source code (did not see this in the SP2 version of the code).
In a separate commit, I also removed the SP-related info from the link pointing to the product documentation on d.s.c - for reasons, see commit message. 
| [ ] 12 SP5 …

Raspberry Pi Quick: fix some URLs

---

xml/art_jeos.xml

When building an HTML version of the guide, I noticed additional whitespaces in the text after some links, stemming from whitespaces before the closing tag of the link elements in the source code (did not see this in the SP2 version of the code).
In a separate commit, I also removed the SP-related info from the link pointing to the product documentation on d.s.c - for reasons, see commit message.
| [ ] 12 SP5 …

JeOS Quick: fix some URLs

---

xml/ay_partitioning.xml

resolves Jira https://jira.suse.com/browse/DOCTEAM-171 and
BSC #https://bugzilla.suse.com/show_bug.cgi?id=1185231
| [x ] 15 SP1  | [ ]
| [x ] 15 SP0  | [ ]

Document missing zFCP options, wwpn and fcp_lun, in AY Guide

---

xml/apps_evolution.xml
xml/apps_firefox.xml
xml/apps_libreoffice.xml
xml/apps_librevarious.xml
xml/apps_librewriter.xml
xml/common_intro_lifecycle_support_i.xml
xml/gnome_custom.xml
xml/gnome_use.xml

First batch of proofing corrections are for the smallest PDF: the GNOME Guide.
I have made a few additional corrections as well, e.g. "Seelct" -> "Select".
* bsc#...
* jsc#SLE-...
| [ ] 15 SP4  |*(no backport necessary)*
| [ ] 15 SP3  | [ ]

Incorporate proofing corrections from Dublin for GNOME Guide

---

xml/autofs.xml
xml/net_samba.xml
xml/storage_fcoe.xml
xml/storage_filesystems.xml
xml/storage_iscsi.xml
xml/storage_lvm.xml
xml/storage_multipath.xml
xml/storage_nfs.xml
xml/storage_nvmeof.xml
xml/storage_raid.xml
xml/storage_raid_troubleshooting.xml
xml/storage_raidroot.xml

Integrate Dublin proofreading suggestions into the Storage Guide.
Note: I have made some additional changes, including rewords to the introductory material in the Samba chapter, as this was badly confused and included some incorrect information.
* bsc#...
* jsc#SLE-...
| [ ] 15 SP4  |*(no backport necessary)*
| [ ] 15 SP3  | [ ]

Integrate proofing corrections to 15.3 storage guide

---

xml/libvirt_guest_installation.xml

PXE boot option was removed from VMM. This update describes how to configure it manually.
* bsc#1185327
* jsc#DOCTEAM-172
| [x] 15 SP4  |*(no backport necessary)*
| [x] 15 SP3  | [ ]

Manual PXE boot when installing new VM (bsc#1185327)

---

.github/PULL_REQUEST_TEMPLATE.md

* make check boxes work/display again in GitHub UI
* separate PR creator & PR reviewer sections of backport table
* add hint that 15 SP4-only content must not be merged yet
* kick out 12 SP2, which is now unsupported
* explicitly mention supported openSUSE Leap versions
* bsc#...
* jsc#SLE-...
| [x] 15 SP4  |*(no backport necessary)*
| [x] 15 SP3  | [ ]
When you are opening …

PR template: Make check boxes work again & other minor updates

---

xml/libvirt_configuration_virsh.xml

This update describes how to use host's crypto adapters inside guest VM.
Rendered version is here
[virsh-kvm-zseries-crypto_color_en.pdf](https://github.com/SUSE/doc-sle/files/6614734/virsh-kvm-zseries-crypto_color_en.pdf)
* jsc#SLE-4578
* jsc#DOCTEAM-41
- SLE 12

Guest-dedicated Crypto Adapters passthru (jsc#SLE-4578)

---

xml/yast2_ftp.xml

Five years ago, yast2-ftp-server was [adapted to use RSA certificates](https://github.com/yast/yast-ftp-server/pull/18). Unfortunately, we did not update the interface. This problem was revealed by [bsc#1183786](https://bugzilla.suse.com/show_bug.cgi?id=1183786) and @dgdavid noticed that we needed to update the docs too.
We fixed the label in all versions (starting in SLE 12 SP5).
Thanks!
* [bsc#1183786](https://bugzilla.suse.com/show_bug.cgi?id=1183786)
- SLE 12

FTP server uses RSA certificates

---

xml/zypper_upgrade.xml

Info about upgrading with `zypper dup` added.
* bsc#1183681
* jsc#DOCTEAM-180
- SLE 12

info for upgrading with zypper dup added bsc#1183681

---

xml/rmt_migrate_from_smt.xml

SMT/RMT feature comparison table was outdated, this update fixes that.
Rendered PDF is here: 
[sec-rmt-migrate-notes_color_en.pdf](https://github.com/SUSE/doc-sle/files/6662139/sec-rmt-migrate-notes_color_en.pdf)
- SLE 12

Updated table of SMT vs RMT features

---

xml/libvirt_configuration_gui.xml
xml/libvirt_configuration_virsh.xml
xml/libvirt_connect.xml
xml/libvirt_guest_installation.xml
xml/libvirt_host.xml
xml/libvirt_management_vagrant.xml
xml/pv2fv.xml
xml/qemu_host_installation.xml
xml/qemu_monitor.xml
xml/qemu_running_vms_qemukvm.xml
xml/virt_support.xml
xml/vt_guestfs.xml
xml/vt_io.xml
xml/vt_qemu_ga.xml
xml/vt_qemu_tpm.xml
xml/vt_scenarios.xml
xml/xen2kvm.xml
xml/xen_config_options.xml
xml/xen_virtualization_manage.xml

Integrate Dublin proofreading connections into the Virtualization Guide. 
One file had no soft line-wrapping, so I have reformatted it with `daps-xmlformat -i`. I did this in a separate commit; I hope this helps.
* bsc#...
* jsc#SLE-...
- SLE 12

Proofing corrections to Virtualization Guide

---

xml/ay_networking.xml

Document the new AutoYaST profile element (**backend**) in the **networking** section. This option will be available **only** in TW / SLE-15-SP4 since yast2-network-4.4.9.
- Implemented by https://github.com/yast/yast-network/pull/1215
* https://bugzilla.suse.com/show_bug.cgi?id=1183886
| [x ] 15 SP4  | *(no backport necessary)*
| [ ] 15 SP3  | [ ]

Document the new backend element in the networking section

---

xml/ay_ask_user_values.xml

We have introduced some changes regarding the `<ask-list>` element in AutoYaST for SLE 15 SP4. This PR documents the new behavior.
Thanks!
* [bsc#1185704](https://bugzilla.opensuse.org/show_bug.cgi?id=1185704)
* https://github.com/yast/yast-autoinstallation/pull/754

AutoYaST: improve <ask-list> description

---

xml/ay_configuration_installation_options.xml
xml/ay_networking.xml
xml/ay_proxy.xml

The proxy documentation is currently under the networking section which leads to errors expecting the resource to be also under the networking resource.
This PR tries to make it a little bit clearer.
There are some fixes about the behavior that will be available in SLE-15-SP3 through a maintenance update.
* https://bugzilla.suse.com/show_bug.cgi?id=1185016
* Related to (https://github.com/SUSE/doc-sle/pull/752)
- SLE 12

AutoYaST: make proxy settings more clear

---

xml/ay_users_groups.xml

The YaST Team is rewriting AutoYaST user management to rely more on useradd, since the diversion between how YaST and useradd do things has brought many problems (see bug reports and Jira entries below).
During that effort we found three problems with the `<user_defaults>` section of the profile:
- The documentation states the section is used to set the configuration values at `/etc/defaults/useradd`. But that's not fully accurate since, in fact, the UMASK parameter should not be written there but somewhere in the `login.defs` directory.
- The "groups" and "no_groups" attributes has been useless since SLE-12.
- Modifying the SKEL parameter of useradd may not be a good idea, so we have decided we should stop doing it.
1) These two attributes define the value to write in …

Obsolete user defaults

---

xml/art_installation-sleds.xml
xml/art_modules.xml
xml/deployment_yast_installer.xml
xml/storage_filesystems.xml
xml/virt_support.xml
xml/xen_administrating.xml
xml/yast2_sw_addon.xml

Update outdated links.
@taroth21 Some items were using the `/sles-15/` URLs. Rather conveniently, we broke many of these URLs with the ID updates :/
- SLE 12

Update dsc/RN links across docs

---

xml/ay_erb_templates.xml

ERB lines should end wiht `%>`.
* Related to [bsc#1187684](https://bugzilla.suse.com/show_bug.cgi?id=1187684)
- SLE 12

AutoYaST: minor fixes regarding ERB mark-up

---

xml/book_security.xml
xml/security_ldap_install.xml
xml/security_ldap_modules.xml
xml/security_ldap_users.xml

* add <replaceable>password</replaceable> placeholders
* add systemctl restart
* clarify language in module management, improve examples
* other small corrections
- SLE 12

Several small fixes in 389 Directory Server

---

xml/ay_partitioning.xml

resolves BSC #1186218, Jira #DOCTEAM-189
- SLE 12

Expand list of partition_ids for AutoYaST partitioning

---

xml/ay_networking.xml

With **network-ng** we modified not only the **UI** but also some of the **AutoYaST** options which are now deprecated like the use of the netmask.
This **PR** tries to extend the current documentation about the different attributes as well as providing a routing example in its corresponding section.
* https://bugzilla.suse.com/show_bug.cgi?id=1184460
* https://jira.suse.com/browse/PM-219 (somehow related)
- SLE 12

AutoYast: Extend routing documentation and examples

---

xml/ay_create_control_file.xml

Since we released SUSE 15 SP3 (and openSUSE Leap 15.3) we are receiving quite some bug reports about profile validation that AutoYaST performs at runtime. It is usually caused by wrong profiles, but we have also detected some bugs in the schema.
Although we mentioned in the release notes [that the check can be disabled](https://www.suse.com/releasenotes/x86_64/SUSE-SLES/15-SP3/#bsc-1173091), that information is not present in the manual. So this PR addresses this problem.
Thanks!
* [bsc#1188153](https://bugzilla.suse.com/show_bug.cgi?id=1188153) among others.
- SLE 12
When opening a PR, do …

AutoYaST: how to disable the runtime validation

---

xml/selinux.xml

this needs more work; for now, incorrect sections are removed
The SELinux section of the Security and Hardening Guide is outdated and incorrect. This PR removes the incorrect sections. Updates will come in future commits.
- SLE 12

Starting corrections for SELinux section of Security and Hardening Guide

---

xml/book_security.xml
xml/security_fips.xml
xml/security_ssh.xml

re Jira DOCTEAM-149, bsc #1164019
Document enabling FIPS 140-2, and limitations 
- SLE 12

Add FIPS 140-2 chapter to Security and Hardening Guide

---

xml/inst_yast2.xml

When installing in a PowerPC machine, YaST re-uses an existing PReP partition. Generally, that PReP partition is the first partition on the disk, otherwise there could be booting trouble.
This PR is for adding a note in order to explain what to do when the partition proposal wants to re-use a PReP partition which is not placed at the beginning of the disk. 
NOTE: this explanation is only needed for SLE-12 family. In SLE-15, this is properly managed by the new storage stack (yast2-storage-ng). 
* https://bugzilla.suse.com/show_bug.cgi?id=1188214
- SLE 12
When opening a PR, do *not* set the …

Add section about PPC partitioning

---

xml/ay_nis_client.xml

According to [bsc#1176391](https://bugzilla.suse.com/show_bug.cgi?id=1176391) the `nis_by_dhcp` option is not supported anymore. Actually, the AutoYaST validation will complain about it. So just drop this element. The bad news is that a few backports are needed.
* [bsc#1176391](https://bugzilla.suse.com/show_bug.cgi?id=1176391)
- SLE 12

AutoYaST: remove the nis_by_dhp element

---

xml/ay_control_file.xml

Add some clarification about how to set `config:type` attributes in an AutoYaST profile.
* [bsc#1187719](https://bugzilla.suse.com/show_bug.cgi?id=1187719)
- SLE 12

AutoYaST: Extend config:type explanation

---

xml/libvirt_configuration_virsh.xml

Similar to PR#935, improve the virsh CPU and memory sections of the VT guide. Add notes about special configuration needed for large CPU and memory VMs.
* bsc#1188751
- SLE 12

virsh cpu and mem fixes

---

xml/virt_support.xml

https://bugzilla.suse.com/show_bug.cgi?id=1188751
Increase max supported vCPUs for KVM guests to 288.
* bsc#1188751
- SLE 12

vt-limits: Increase max vCPUs to 288

---

xml/entity-decl.ent
xml/security_ldap.xml
xml/security_ldap_backups.xml
xml/security_ldap_directory_tree.xml
xml/security_ldap_firewall.xml
xml/security_ldap_install.xml
xml/security_ldap_kerberos_ad_yast.xml
xml/security_ldap_migrate_test.xml
xml/security_ldap_modules.xml
xml/security_ldap_sssd.xml
xml/security_ldap_users.xml

Hi @cjschroder -- this PR tries to correct a few things within the LDAP chapter. I've ultimately refrained from making this exhaustive though (because time). I would like to make sure this PR doesn't break any eggs to make the omelette though.
A few things in the chapter are imo inconsistent with SUSE style:
* Collecting multiple commands within a screen is something that I don't think is normally done in SUSE docs. I've tried to reduce those occurrences but I didn't want to rewrite the entire chapter. (Afaik this is not an explicit style rule [sadly].)
* Using things that look like actual values rather than a generic placeholder within replaceables (such as `ldap1` rather than `INSTANCE_NAME` in this chapter). (While the capitalization is a style rule, the rule to use a generic …

Improve style of LDAP section

---

xml/tuning_storagescheduler.xml

Leap 15.3 does not have /lib/udev directory anymore. It is /usr/lib/udev now
Fix wrong path in documentation
No. Should I create some?
- SLE 12

Leap 15.3 does not have /lib/udev anymore

---

xml/yast2_keymouse.xml

This used to be `/etc/sysconfig/keyboard`, but not any more. Save people looking by documenting it.
No
- [x ] SLE 15 SP4/openSUSE Leap 15.4 *(current `main`, no backport necessary)*

Document where yast stores keyboard settings

---

xml/security_firewall.xml

re bsc #1171945, Jira DOCTEAM-229, SLE 15 and up
- SLE 12

Add mention of YaST firewalld module to Security Guide

---

xml/ay_networking.xml

Resolves BSC #1188874, Jira DOCTEAM-319
- SLE 12

Clarify that DNS section of YaST takes host name, not FQDN

---

xml/audit_components.xml

record types and event fields in /var/log/audit
resolves BSC #1187485 and Jira DOCTEAM-310.
Applies to SLE 15*
- SLE 12

Add references to 'Understanding Linux audit' that explain

---

xml/libvirt_guest_installation.xml

The virt-install example for Xen (Example 8.2 in the Virtualization Guide)
does not work as is. PV is the default machine type for Xen, but PV guests
cannot boot from cdrom. HVM guests can boot from cdrom, so change the
example to create an HVM guest.
While at it, update the examples to install SLE15 SP2 instead of an old
distro like SLED12.
Fix virt-install example in the virtualization guide
* bsc#1189234
- SLE 12

vt-doc: Fix virt-install example for Xen

---

xml/ay_general_options.xml

Remove unneeded references to the `cio_ignore` element. These examples do not bring any value.
* [bsc#1188168](https://bugzilla.suse.com/show_bug.cgi?id=1188168)
- SLE 12

Remove uneeded cio_ignore examples

---

xml/ay_networking.xml

The `<aliases>` section is missing from the AutoYaST documentation. This PR adds the description and a simple example.
An issue is still pending. As you can see, the elements in that section are case-sensitive. We have improved the implementation and starting with `yast2-network` 4.2.104 (SP2), and 4.3.75 (SP3), and 4.4.25 (SP4) that's not the case anymore. So I am unsure about how to express this information. Maybe the user does not need to know so many details and we could simply remove the notice from the SP4 documentation (it will not be case sensitive from the beginning).
* [bsc#1190739](https://bugzilla.suse.com/show_bug.cgi?id=1190739)
- SLE 12
The doc team member merging …

AutoYaST: describe the <aliases> section

---

xml/ay_firewall.xml

This PR fixes an example regarding the `<enable_firewall/>` element. The correct way to specify the type is `config:type="boolean"`, as mentioned in the original bug report.
* [bsc#1189137](https://bugzilla.suse.com/show_bug.cgi?id=1189137)
- SLE 12

Fix the <enable_firewall/> example

---

xml/containers-docker-installation.xml
xml/entity-decl.ent
xml/klp.xml
xml/rmt_migrate_from_smt.xml
xml/security_ldap.xml
xml/security_xca.xml
xml/selinux.xml

update release number entities for SLE 15 SP4
- SLE 12

update product release number entities for SLE 15 SP4

---

xml/ay_users_groups.xml

In the [new yast2-users code relying on "shadow" commands](https://github.com/yast/yast-users/pull/349) support for group passwords [has been dropped](https://github.com/yast/yast-users/pull/353) due to its _"inherent security problem" nature_.
Thus, `group_password` and `encrypted` group attributes will be neither exported nor imported.
* [jsc#SLE-21447](https://jira.suse.com/browse/SLE-21447)
- SLE 12

AutoYaST: drop no longer supported group attributes

---

xml/file_management.xml

This PR migrates the chapter 'Modify permissions on certain system files' from the OS Hardening Guide for SAP HANA to the SLES Security & Hardening Guide.
* https://bugzilla.suse.com/show_bug.cgi?id=1176622
- SLE 12

Migrate chapter 'Modify permissions on certain system files' to SLES Hardening Guide

---

xml/ay_auto_installation.xml

re jira#SLE-21833
How to disable SSL verification for HTTPS installation paths
Reviewers, see attached PDF
[invoking-autoinst_color_en.pdf](https://github.com/SUSE/doc-sle/files/7514678/invoking-autoinst_color_en.pdf)
- SLE 12

Document ssl_verify option for AutoYaST

---

xml/ay_ntp_client.xml

Fix the `ntp-server` section examples in the AutoYaST documentation. Additionally, I took the opportunity to improve the indentation for consistency with other examples.
Unfortunately, this change applies to all SLE 15 systems, so you might need to do some backporting work. Sorry for that.
* [bsc#1188349](https://bugzilla.suse.com/show_bug.cgi?id=1188349)
- SLE 12

Fix the `ntp-server` section examples

---

sled/ar/xml/MAIN.SLEDS.xml
sled/cs/xml/MAIN.SLEDS.xml
sled/de/xml/MAIN.SLEDS.xml
sled/es/xml/MAIN.SLEDS.xml
sled/fr/xml/MAIN.SLEDS.xml
sled/hu/xml/MAIN.SLEDS.xml
sled/it/xml/MAIN.SLEDS.xml
sled/ja/xml/MAIN.SLEDS.xml
sled/ko/xml/MAIN.SLEDS.xml
sled/pl/xml/MAIN.SLEDS.xml
sled/pt_br/xml/MAIN.SLEDS.xml
sled/ru/xml/MAIN.SLEDS.xml
sled/zh_cn/xml/MAIN.SLEDS.xml
sled/zh_tw/xml/MAIN.SLEDS.xml
sles/ar/xml/MAIN.SLEDS.xml
sles/cs/xml/MAIN.SLEDS.xml
sles/de/xml/MAIN.SLEDS.xml
sles/es/xml/MAIN.SLEDS.xml
sles/fr/xml/MAIN.SLEDS.xml
sles/hu/xml/MAIN.SLEDS.xml
sles/it/xml/MAIN.SLEDS.xml
sles/ja/xml/MAIN.SLEDS.xml
sles/ko/xml/MAIN.SLEDS.xml
sles/pl/xml/MAIN.SLEDS.xml
sles/pt_br/xml/MAIN.SLEDS.xml
sles/ru/xml/MAIN.SLEDS.xml
sles/zh_cn/xml/MAIN.SLEDS.xml
sles/zh_tw/xml/MAIN.SLEDS.xml

dm:editurls tag removed for all languages of SLE15 SP1.
Will be done for each branch version separately therefore no backports needed

SEO: remove editurls_trans_SLE15SP1

---

xml/vt_installation.xml

This update fixes network issues when using ESX as a guest hypervisor
* bsc#1179596
- SLE 12

VMWare ESX as a guest hypervisor (bsc#1179596)

---

xml/file_management.xml

This PR migrates the chapter 'Change home directory permissions from 775 to 700' from the SAP HANA Hardening Guide to the SLE Security & Hardening Guide (BSC#1176621)
https://bugzilla.suse.com/show_bug.cgi?id=1176621
- SLE 12

Migrate chapter 'Change home directory permissions from 755 to 700' from SAP HANA Hardening Guide to SLE Security & Hardening Guide (BSC#1176621)

---

xml/book_security.xml
xml/security_cron_at.xml

This PR migrates two chapters from the SAP HANA Hardening Guide to the SLE Security & Hardening Guide.
* [BSC#1176613: Migrate chapter 'Implement cron.allow' from OS Hardening Guide for SAP HANA to SLES Hardening Guide](https://bugzilla.suse.com/show_bug.cgi?id=1176613)
* [BSC#1176614: Migrate chapter 'Implement at.allow' from OS Hardening Guide for SAP HANA to SLES Hardening Guide](https://bugzilla.suse.com/show_bug.cgi?id=1176614)
- SLE 12

Security & Hardening Guide: New chapter about restricting cron and at

---

l10n/sled/de-de/xml/MAIN.SLEDS.xml
l10n/sled/zh-cn/xml/MAIN.SLEDS.xml
l10n/sles/de-de/xml/MAIN.SLEDS.xml
l10n/sles/es-es/xml/MAIN.SLEDS.xml
l10n/sles/fr-fr/xml/MAIN.SLEDS.xml
l10n/sles/it-it/xml/MAIN.SLEDS.xml
l10n/sles/ja-jp/xml/MAIN.SLEDS.xml
l10n/sles/ko-kr/xml/MAIN.SLEDS.xml
l10n/sles/pt-br/xml/MAIN.SLEDS.xml
l10n/sles/zh-cn/xml/MAIN.SLEDS.xml
l10n/sles/zh-cn/xml/art_jeos_quickstart.xml
l10n/sles/zh-cn/xml/art_pcidss.xml
l10n/sles/zh-cn/xml/art_sles_rpi_quick.xml
l10n/sles/zh-tw/xml/MAIN.SLEDS.xml

dm:editurls tag removed for all languages of SLE 15 SP2.
Will be done for each branch version separately therefore no backports needed

SEO: remove editurls from l10n SLE15SP2

---

xml/libvirt_management_vagrant.xml

We no longer ship SLED vagrant boxes.
- SLE 12

Remove mention of SLED

---

xml/net_sdn.xml

Removed non-existent link and killed single item itemized list.
- SLE 12

Removed obsolete link pointing to non-existent SDN whitepaper

---

xml/qemu_running_vms_qemukvm.xml

Aligned prompts to use `sudo` + make preconditions to run qemu on ARM64 architecture more clear.
Rendered PDF is attached 
[cha-qemu-running-basic_color_en.pdf](https://github.com/SUSE/doc-sle/files/7562656/cha-qemu-running-basic_color_en.pdf)
- SLE 12

aligned prompts to sudo an added recommendations for ARM64 arcjitecture

---

xml/ay_erb_templates.xml
xml/ay_rules_classes.xml

We have introduced a new **AutoYaST rules schema element** for detecting a **EFI boot** as well as a **ERB template helper** which needs to be documented.
More information can be found here https://jira.suse.com/browse/SLE-20219 or in the implementation [PR](https://github.com/yast/yast-autoinstallation/pull/808) itself
* [jsc#SLE-18819](https://jira.suse.com/browse/SLE-18819)
- SLE 12

AutoYaST: Add helpers for detecting EFI boot (jsc#SLE-18819)

---

xml/newbie_bash.xml

Since I'm not native English speaker and  mostly is used the term "wild card" in the document I send this PR to fix that. I prefer the term "wildcard".
Fix consistency using the term "wild card" over "wildcard"
* bsc#...
* jsc#SLE-...
- SLE 12

consistency using the wild card concept

---

xml/entity-decl.ent
xml/libvirt_guest_installation.xml
xml/vt_installation.xml
xml/vt_io.xml
xml/vt_scenarios.xml

This update improves UEFI mentionings in respect to the ARM architecture
* jsc#SLE-15822
- SLE 12

UEFI Secure Boot improvements for ARM (jsc#SLE-15822)

---

xml/vt_cachemodes.xml

virt-disk-cache.png is missing, causing validation failures. I commented out the <figure/> reference in vt_cachemodes.xml
@tbazant see https://github.com/SUSE/doc-sle/pull/1023
- SLE 12

Commented out reference to missing figure virt-disk-cache.png

---

xml/vt_cachemodes.xml

Validation fails with "Fatal error: The following images are missing:
virt-disk-cache". Commenting out the <figure/> stanza clears the error.
@sknorr @tbazant I reverted my revert, and got the same errors. Created a new branch to test, still the same error. Commented out the ditaa figure stanza, no validation errors.
- SLE 12

testing validation failures

---

xml/virt_support.xml

There is a space for improvements in the Xen limits specifications. This update tries to squeeze this space :-)
Rendered PDF is attached 
[cha-virt-support_color_en.pdf](https://github.com/SUSE/doc-sle/files/7588399/cha-virt-support_color_en.pdf)
* bsc#1192256
- SLE 12

Xen limits improvements

---

xml/zypper.xml

Resolves Jira SLE-8906
- SLE 12

Document new automatic patch retraction, which removes buggy patches with no user intervention

---

l10n/sled/ar-ar/images/src/png/yast2_retracted_patches.png
l10n/sled/cs-cz/images/src/png/yast2_retracted_patches.png
l10n/sled/de-de/images/src/png/yast2_retracted_patches.png
l10n/sled/es-es/images/src/png/yast2_retracted_patches.png
l10n/sled/fr-fr/images/src/png/yast2_retracted_patches.png
l10n/sled/hu-hu/images/src/png/yast2_retracted_patches.png
l10n/sled/it-it/images/src/png/yast2_retracted_patches.png
l10n/sled/ja-jp/images/src/png/yast2_retracted_patches.png
l10n/sled/ko-kr/images/src/png/yast2_retracted_patches.png
l10n/sled/pl-pl/images/src/png/yast2_retracted_patches.png
l10n/sled/pt-br/images/src/png/yast2_retracted_patches.png
l10n/sled/ru-ru/images/src/png/yast2_retracted_patches.png
l10n/sled/zh-cn/images/src/png/yast2_retracted_patches.png
l10n/sled/zh-tw/images/src/png/yast2_retracted_patches.png
l10n/sles/ar-ar/images/src/png/yast2_retracted_patches.png
l10n/sles/cs-cz/images/src/png/yast2_retracted_patches.png
l10n/sles/de-de/images/src/png/yast2_retracted_patches.png
l10n/sles/es-es/images/src/png/yast2_retracted_patches.png
l10n/sles/fr-fr/images/src/png/yast2_retracted_patches.png
l10n/sles/hu-hu/images/src/png/yast2_retracted_patches.png
l10n/sles/it-it/images/src/png/yast2_retracted_patches.png
l10n/sles/ja-jp/images/src/png/yast2_retracted_patches.png
l10n/sles/ko-kr/images/src/png/yast2_retracted_patches.png
l10n/sles/pl-pl/images/src/png/yast2_retracted_patches.png
l10n/sles/pt-br/images/src/png/yast2_retracted_patches.png
l10n/sles/ru-ru/images/src/png/yast2_retracted_patches.png
l10n/sles/zh-cn/images/src/png/yast2_retracted_patches.png
l10n/sles/zh-tw/images/src/png/yast2_retracted_patches.png

add l10n links for new image file yast2_retracted_patches.png

---

xml/libvirt_managing.xml

SLES 15 SP4 has changed the behavior of live guest migrations. KVM hosts need to be adjusted so tthat the migration suceeds.
Rendered PDF of the section is attached 
[sec-libvirt-admin-migrate_color_en.pdf](https://github.com/SUSE/doc-sle/files/7762825/sec-libvirt-admin-migrate_color_en.pdf)
* bsc#1191511
- SLE 12

Set vm.unprivileged userfaultfd to 1 when doing a live migration (bsc#1191511)

---

xml/vt_installation.xml

This update fixes wrong value used for the `nested` parameter.
* bsc#1194040
- SLE 12

Replaced 'Y' with '1' for the KVM's 'nested' boot parameter (bsc#1194040)

---

xml/storage_multipath.xml
xml/storage_nvmeof.xml

Add note about using `iostat` in NVMe multipath setups.
* bsc#1194343: 1194343 - iostat and multipath nvme setups 
* related: bsc#1193785
- SLE 12

add note (bsc#1194343, bsc#1193785)

---

xml/tuning_taskscheduler.xml

The documentation says make -j NO_CPUS will benefit from this setting  off.. this may have been the case 7 or 8 years ago when it was added, but in 2016 make was changed to use vfork everywhere.. later make was modified to execute jobs using posix_spawn. both ways are always child_first (the calling process is suspended) 
So this example is at least out of date or at most never quite true.

remove misleading or no longer valid example

---

xml/ay_bootloader.xml

Document new keys in autoyast bootloader to set up password protected boot.
https://jira.suse.com/browse/SLE-20928
- SLE 12

Bootloader password autoyast

---

xml/ay_bootloader.xml

Correct build errors by adding profiling to new `<phrase/>`
- SLE 12

add profiling to <phrase/>

---

xml/libvirt_managing.xml

To allow post-copy migration with a KVM host kernel >= 5.11, the
vm.unprivileged_userfaultfd sysctl setting must be set to 1.
libvirt 8.0.0 and newer provide a /usr/lib/sysctl.d/ file for this.
Mention it in the existing note about vm.unprivileged_userfaultfd.
* bsc#1191511
- SLE 12

vt-doc: Mention unprivileged_userfaultfd setting provided by libvirt

---

xml/snapper.xml

A small fix in an unclear documentation.
* bsc#bsc#1194030
- SLE 12

Timeline snapshots are enabled by default (bsc#1194030)

---

xml/net_yast.xml

This update fixes a misleading info about routing  metric priority
Closes bsc#1187740
- SLE 12

Lowest metric has highest routing priority (bsc#1187740)

---

xml/ay_security_settings.xml

It has been requested to unify the way **Selinux** or **AppArmor** are selected / configured during the installation
In order to choose which **Linux Security Module** should be used by default we have added a new section **lsm** to the installation control file <s>as well as we have added almost the same options to the security **AutoYaST** schema. The default **LSM** will be set by the **select** tag falling back to **apparmor** in case of missing.</s>
<s>This PR tries to document the new section and the different options</s>
**Note** It has been decided to only allow to select the desired **Major Linux Security Module** to be activated after the installation and the **SELinux Mode** in case of selected (see https://github.com/yast/yast-security/pull/123).
* jsc#SLE-22069
When opening a …

Replaced AY Security SElinux settings by LSM settings

---

xml/vt_installation.xml

Render PDF is attached
[sec-vt-installation-ovmf_color_en.pdf](https://github.com/SUSE/doc-sle/files/7993544/sec-vt-installation-ovmf_color_en.pdf)
* jsc#SLE-21134
- SLE 12

Updated description of  OVMF firmware packages (jsc#SLE-21134)

---

xml/virt_support.xml

Win guests fail to reboot without VP drivers. This update informs about that.
* bsc#1194621
- SLE 12

Added note about Win guests reboot (bsc#1194621)

---

xml/bootconcept.xml

This update fixes misleading info about creating initrd with dracut
- SLE 12

Changed explanation for creating initrd with dracut

---

xml/containers-get.xml
xml/containers-support.xml

SLE BCI support for Managed Kubernetes Services in the Public Cloud
* bsc#...
* jsc#SLE-...
- SLE 12

Add BCI on Pub Cloud note

---

xml/art_raspberry-pi.xml

Rename all occurrences of JeOS to Minimal Image. Keep jeos-firstboot.
* bsc#...
* jsc#SLE-...
- SLE 12

JeOS to Minimal Image rename

---

xml/security_ldap_install.xml

resolves Jira SLE-21385
This will be backported to SLE 12 SP3, after the changes appears in the maintenance update repos.
See the epic at Jira SLE-20068.
- SLE 12

New capability for sudoers.ldap: user negation now works

---

xml/ay_general_options.xml
xml/deployment_yast_installer.xml
xml/installation-opensuse.xml

On customer request by mail:
* adding information on where toi get openSUSE
* removing annotations on quarterly updates for openSUSE
* in addition, removed lone sect
Applies to.
Lep 15.3 backpüort needs to be done.

Added getting openSUSE; got rid of lone sect1

---

xml/docker_docupdates.xml
xml/storage_filesystems.xml
xml/storage_iscsi.xml
xml/tuning_kexec.xml

SEO squad: Fixing and replacing broken links. All branches will be handled separately, therefore no backports.
- SLE 12
- [x ] SLE 12 SP4

SEO fix: Broken link replacements in SLE12SP4

---

xml/smt_install.xml
xml/storage_filesystems.xml
xml/storage_iscsi.xml
xml/tuning_kexec.xml

SEO squad: Fix/replace/remove broken links. All branches done separately, therefore no backports.
- SLE 12
- [x ] SLE 12 SP5

SEO fix: broken link replacements in SLE12SP5

---

xml/ay_software.xml

Clarify that the addons from a registration server must be defined in the `suse_register` section.
- Related to https://bugzilla.suse.com/show_bug.cgi?id=1196600
This is a minor change, just to clarify the current situation, no back port is needed.
- SLE 12

A note about addons from SMT/RMT/SCC

---

xml/art_sle_modules_quick.xml
xml/security_preface.xml
xml/storage_filesystems.xml
xml/tuning_kexec.xml
xml/tuning_systemtap.xml

A total of seven links were removed or updated (SES, CVE, storage etc.) due to product updates and/or discontinuance.
Changes will be done for each branch separately, so no backport.
- SLE 12

SEO remove SES links

---

xml/containers-docker-building-images.xml

See https://bugzilla.suse.com/show_bug.cgi?id=1195546 for details
Document the need to add RMT ca certificate into the container if RMT certificate is self-signed
No
- [X ] SLE 15 SP3/openSUSE Leap 15.3
- SLE 12

Document the need to add RMT ca certificate

---

xml/art_amd-sev.xml

Add information about SEV ES to the AMD SEV doc. Also add a section describing how to install SEV(-ES) VMs with virt-install.
PDF is attached 
[article-amd-sev_color_en.pdf](https://github.com/SUSE/doc-sle/files/8303029/article-amd-sev_color_en.pdf)
* bsc#1196806
- SLE 12

Add info about SEV-ES to the SEV doc

---

xml/common_intro_feedback_i.xml

Introduction para for contributing to documentation for foreign languages changed. As 'Edit source' is no longer available for other languages then English.
Changes also need to be done in the other product repos.
* jsc#DOCTEAM-409
- SLE 12
- SLE 11

DOCTEAM-409 contribution para changed

---

doc-kit.conf
xml/generic-entities.ent
xml/zypper.xml

SUSEConnect got rewritten to be self-contained and slightly affects `search-packages` subcommand of zypper
* jsc#SLE-22621
- SLE 12

Minor update to zypper description and output (jsc#SLE-22621)

---

xml/apache2.xml
xml/apache2_yast_i.xml
xml/product-entities.ent

Some info in the Apache chapter is outdated, this update tries to align it.
!!!IMPORTANT: check the &php-version; entity after backporting
Fixes https://bugzilla.suse.com/show_bug.cgi?id=1177654
- SLE 12

Update of Apache (+PHP) chapter (bsc#1177654)

---

xml/rmt_mirroring.xml

Describe missing step of setting up the disconnected RMT, and point to the "skip" button. 
* https://suse.slack.com/archives/C02AYV7UJSD/p1648626093379629
- SLE 12
I'd like to apply it also to all other versions. 

Extend manual for disconnected RMT setup

---

xml/art_virtualization-best-practices.xml

This section was part of the deployment guide originally, but belonged here.
- SLE 12

Added new section on CPU removal

---

xml/common_intro_feedback_i.xml

update README.adoc URL from https://github.com/SUSE/doc-sle/blob/master/README.adoc to https://github.com/SUSE/doc-sle/blob/main/README.adoc
Jira #SLE-22017
- SLE 12

change URL from master/ to main/

---

xml/ay_general_options.xml
xml/deployment_yast_installer.xml

and in AutoYast profiles.
Resolves jsc#DOCTEAM-470 'Self-update section' Deployment Guide
jsc#DOCTEAM-470
- SLE 12

relurl now supported for self_update parameter on install media

---

xml/book_virtualization.xml
xml/virt_help.xml
xml/virt_logs.xml

The beginnings of a troubleshooting section for the Virtualization
Guide. More info can be added later, for example items sepcific to
Xen and KVM.Describe the overall goals of this pull request.
!!!!!NOTE: when backporting to 15 SP3, update the external link to supportconfig in the Admin guide!!!!!
- SLE 12

vt-doc: Add a Troubleshooting section

---

xml/art_sles_rpi_quick.xml

In SLES 15 SP2, `bluez` was moved to Base System module.
Therefore the Desktop Applications module no longer needs to be added by users.
Update (simplify) instructions for using Bluetooth on Raspberry Pi on SLES 15 SP2 (only).
Originally part of author's pending `rpi-x11` queue.
Unknown.
- SLE 12

rpi: Update bluez instructions for SLES 15 SP2

---

xml/ay_bootloader.xml

Adds explanation how hibernation is handled as part of kernel parameters.
Related pull request with explanation: https://github.com/yast/yast-bootloader/pull/666/
Please note that for SP3 and SP4 parts will work only if installer self update is enabled as it is not in default insts-sys.
And the part that won't work is detection if device will exist. So invalid device is just applied without self-update.
* https://bugzilla.suse.com/show_bug.cgi?id=1187690
* https://bugzilla.suse.com/show_bug.cgi?id=1197192
- SLE 12

add explanation about hibernation handling in autoyast bootloader

---

xml/grub2.xml

GRIB bootloader can be manually configured to provide authorization to specific boot menu entries.
This update provides an example of such configuration.
* jsc#SLE-14813
- SLE 12

Added section on GRUB authorization (jsc#SLE-14813)

---

xml/tuning_cgroups.xml

Very rough draft to capture (replacement PR of #1150):
- simple(r) IO control setup with systemd,
- prerequisites of such setups and mainly
- expectations when configuring IO control.
* bsc#1195915
* bsc#1175160
* jsc#SLE-22013 (loosely related)
- SLE 12
It also assumes systemd version >v243 (and ideally needs some more
backports both into systemd and kernel to work good enough in described
scenarios).

Tuning Guide: Rework section about IO control with cgroups

---

xml/deployment_yast_installer.xml
xml/libvirt_guest_installation.xml

The new GeekoDoc release found some validation errors. This PR will fix them.
- SLE 12

Fix validation errors from GeekoDoc 2.1.1

---

xml/storage_filesystems.xml

As raised by Andreas Taschner, GRUB2 has carried support for lzo and
zstd compressed files on Btrfs for some time, via upstream GRUB2 commits
095f077e6d and 3861286486 respectively.
Signed-off-by: David Disseldorp <ddiss@suse.de>
- SLE 12

storage_filesystems: remove obsolete GRUB2 Btrfs compression note

---

xml/art_raspberry-pi.xml

This is an amendment to https://github.com/SUSE/doc-sle/pull/1161
to replace some deprecated commands.
* jsc#SLE-17223
* bsc#1193693
- SLE 12

Replace deprecated hci… commands for RPi bluetooth

---

xml/security_ldap_sssd.xml

Corrections to the dsidm command to create a sssd.conf template, and to the 
example sssd.conf file.
Jira DOCTEAM-544.
- SLE 12

corrections to sssd.conf in LDAP chapter

---

l10n/sles/zh-cn/xml/libvirt_guest_installation.xml
xml/libvirt_guest_installation.xml
xml/security_ldap.xml
xml/security_ldap_install.xml
xml/security_ldap_kerberos_ad_yast.xml
xml/security_ldap_modules.xml
xml/security_ldap_sssd.xml

SP2 does not support migration from OpenLdap
re: bugzilla #1196821
* bsc#...
* jsc#SLE-...
- SLE 12

synchronize SLE 15 SP2 with newer releases. The only difference is

---

l10n/sles/ar-ar/xml/security_fips.xml
l10n/sles/cs-cz/xml/security_fips.xml
l10n/sles/de-de/xml/security_fips.xml
l10n/sles/es-es/xml/security_fips.xml
l10n/sles/fr-fr/xml/security_fips.xml
l10n/sles/hu-hu/xml/security_fips.xml
l10n/sles/it-it/xml/security_fips.xml
l10n/sles/ja-jp/xml/security_fips.xml
l10n/sles/ko-kr/xml/security_fips.xml
l10n/sles/pl-pl/xml/security_fips.xml
l10n/sles/pt-br/xml/security_fips.xml
l10n/sles/ru-ru/xml/security_fips.xml
l10n/sles/zh-cn/xml/security_fips.xml
l10n/sles/zh-tw/xml/security_fips.xml
xml/book_security.xml
xml/entity-decl.ent
xml/security_fips.xml

Backport FIPS section of Security and Hardening Guide from codestream 15
jira #DOCTEAM-580
- SLE 12

Add FIPS section to Security and Hardening Guide

---

xml/apps_firefox.xml

Added a note that Firefox does not support clicking on ftp links by default anymore.
* bsc#1190667
- SLE 12

add note on ftp links firefox (bsc#1190667)

---

xml/yast2_ftp.xml

New version of vsftpd does not support older versions of TLS protocol by default. One needs to manually update the configuration file to enable the old behaviour.
* jsc#SLE-21818
- SLE 12

Added note about not supporting older TLS protocol (jsc#SLE-21818)

---

xml/apps_firefox.xml
xml/apps_libreoffice.xml
xml/apps_librevarious.xml
xml/backup.xml
xml/gnome_accessibility.xml
xml/gnome_custom.xml
xml/gnome_networking.xml
xml/gnome_use.xml

Corrections from final checks for GNOME user guide (SLES/SLED/openSUSE)
- spellcheck
- linkcheck (no issues)
- stylecheck
- SLE 12

GNOME user guide:spellcheck

---

xml/security_preface.xml
xml/storage_nvmeof.xml
xml/vt_best_practices.xml
xml/xm_vs_xl_links.xml

SEO fixes of broken links SLE15SP1

---

xml/net_nfs.xml
xml/storage_nvmeof.xml
xml/vt_best_practices.xml

SEO fixes of broken links_SLE12SP3

---

xml/storage_nvmeof.xml
xml/vt_best_practices.xml

SEO fixes of broken links_SLE12SP4

---

l10n/sles/de-de/xml/net_dhcp.xml

SEO fixes in de translations for SLE15SP1. No backports, no cherry-picking.
* bsc#...
* jsc#SLE-...
- [x ] SLE 15 SP1
- SLE 12

SEO fixes for de in SLE15 SP1

---

xml/selinux.xml

SEO fixes of broken links SLE12SP3_JA

---

xml/art_virtualization-best-practices.xml

According to https://bugzilla.suse.com/show_bug.cgi?id=1195441, this section is unneeded.
* bsc#1195441
- SLE 12

Removed unnecessary 'Xenstrore in tmpfs' section from Virt BP

---

xml/snapper.xml

Currently, booting Xen kernel from a Btrfs snapshot fails. This update referres to a relevant support article.
* bsc#1196834
- SLE 12

Booting Xen from snapshot fails (bsc#1196834)

---

DC-SLE-container-guide
xml/containers-basics.xml
xml/containers-docker-installation.xml

Preparing the Container Guide for a stand-alone build, so it can be published in a separate category on d.s.c. Long term plan (SLE 15 SP5) is to move it out of the set to doc-unversioned (caution: will break existing localized builds). Therefore this change should not be mereged into any maintenance branch.
* created a new DC-file for a stand-alone version of the guide
* replaced internal xfres with external links

Preparing a stand-alone version of the Container Guide

---

xml/gpu_passthru.xml

The related modules are already in the kernel.
* bsc#1200003
- SLE 12

No need to add the vfio-pci in a loadabale list (bsc#1200003)

---

xml/containers-bci.xml

The `com.suse.techpreview` label does not exist anymore, it has been replaced with `com.suse.supportlevel`
- SLE 12

Fix techpreview label error

---

xml/storage_uuids.xml

I changed the mount of a local ntfs /root filesystem to the mount of a correctly specified remote system. This better reflects the exemplified usage.
* bsc#...
* jsc#SLE-...
- SLE 12

Changed example in the _netdev section

---

xml/ulp.xml

Libpulp 0.2.0 changed a few things about how livepatch files are
distributed. This PR updates the information in this document to reflect those
changes.
Signed-off-by: Giuliano Belinassi <gbelinassi@suse.de>

Update ULP section with information from libpulp 0.2.0 (jsc#SLE-20214)

---

xml/libvirt_managing.xml

https://bugzilla.suse.com/show_bug.cgi?id=1199991
- SLE 12

Care for syncing VM time after restore (bsc#1199991)

---

xml/art_admin_slemicro_podman.xml
xml/containers-buildah-overview.xml
xml/containers-podman-overview.xml

The currently present usermod calls do not add enough subuids & subgids for
containers with files owned by the nobody user (see for instance
https://bugzilla.suse.com/show_bug.cgi?id=1199178). This commit makes the
usermod calls consistent with the defaults of useradd
* [bsc#1199178](https://bugzilla.suse.com/show_bug.cgi?id=1199178)
- SLE 12

Update usermod calls to include enough subuids/subgids

---

l10n/sles/de-de/xml/net_nfs.xml
l10n/sles/zh-cn/xml/net_nfs.xml

SEO fixes of broken links SLE15SP0 DE

---

l10n/sles/zh-cn/xml/net_nfs.xml
xml/apps_gimp.xml

SEO fixes of broken links SLE15SP0 EN

---

l10n/sles/de-de/xml/net_nfs.xml

SEO fixes of broken links SLE15SP1 DE

---

xml/ay_country_settings.xml

Just fixing the path of file containing a list of entries available for setting up a keyboard layout.
Accordingly to documentation, file used to be in:
/usr/share/YaST2/data/keyboards.rb
Checked that in openSUSE 15.3 it is in:
/usr/share/YaST2/lib/y2keyboard/keyboards.rb
* bsc#...
* jsc#SLE-...
- SLE 12

New location for list of keyboard layouts

---

l10n/sles/ja-jp/xml/adm_support.xml

SEO fixes of broken links SLE12SP5 JA

---

xml/apps_gimp.xml

SEO fixes of broken links SLE12SP5 EN

---

l10n/sles/de-de/xml/net_nfs.xml

SEO fixes of broken links SLE12SP4 DE

---

l10n/sles/ja-jp/xml/adm_support.xml
l10n/sles/ja-jp/xml/net_nfs.xml

SEO fixes of broken links SLE12SP4 JA

---

xml/ay_users_groups.xml

The current description of the user_password setting in autoyast guide claims that a exclamation mark will generate a random password. This is only true if and only if encrypted value is set to false.
If you set an exclamation mark as value in user_password and encrypted is true, you get a account with locked password.
This is a nice feature and should be clarified in the documentation.
Since this is my first PR to sle-doc, feel free to correct me, e.g if I marked the wrong checkboxed below and I only used main as target branch.
I tested this with SLES12 SP5, SLES15 SP3 and SLES15 SP4.
- SLE 12 …

AY guide: Behaviour of ! in user_password depends on encrypted setting.

---

xml/tuning_taskscheduler.xml

Added missing space between argument and value.

grep -v"domain" --> grep -v "domain"

---

xml/tuning_tracing.xml

Corrected grammar. Countable nouns (more/fewer) vs uncountable (more/less)

"less errors" => "fewer errors"

---

l10n/sles/zh-cn/xml/xm_vs_xl_links.xml

SEO fixes of broken links SLE15SP3 ZH

---

l10n/sles/zh-cn/xml/security_preface.xml

SEO fixes of broken links SLE15SP2 ZH

---

xml/vt_cachemodes.xml

Removed superfluous article in sentence.

can use a one of the following => can use one of the following

---

xml/vt_cachemodes.xml

Corrected grammar: third person does, not do.

guest do not => guest does not

---

xml/ulp.xml

Just updated the file suffix to *.ulp
* bsc#1200859
- SLE 12

Fixed suffix to .ulp (bsc#1200859)

---

xml/rmt_rmt-cli.xml

`rmt-cli` take the new `systems purge` subcommand. This update reflects that
* bsc#1202752
- SLE 12

Added 'systems purge' subcommand (bsc#1202752)

---

xml/apps_libreoffice.xml

The new Libre Office version 7.3 will be released soon for SLE 15 SP4/SP3 and SLE 12 SP5. 
The order and description of how to customize LO has changed.
* jsc#SLE-24442
- SLE 12

change customize LO

---

xml/storage_fcoe.xml
xml/storage_filesystems.xml
xml/storage_fs-resizing.xml
xml/storage_iscsi.xml
xml/storage_isns.xml
xml/storage_lvm-snapshots.xml
xml/storage_lvm.xml
xml/storage_mdadm-resize.xml
xml/storage_multipath.xml
xml/storage_raid10.xml

Updated 'terminal console' to 'terminal' in all instances of the Storage Guide per [issue #178](https://github.com/SUSE/doc-styleguide/issues/178)
- SLE 12

Updated 'terminal console' to 'terminal'

---

xml/ay_upgrade.xml

Replaced "Installation" with "Upgrade" for menu item to select when performing offline upgrade utilizing AutoYast within the AutoYast Guide for SLES 15 SP4.

Replaced "Installation" with "Upgrade"

---

xml/ay_software.xml

Describe how to use regular expressions to install packages and patterns in AutoYaST. It is a relatively unknown feature that has been there [since 2009](https://github.com/yast/yast-autoinstallation/commit/d7dbe6322f709f4f372e1e119a2ec89d0ef1ccfe) but, AFAIK, it was never documented.
- SLE 12

AutoYaST: document packages/patterns installation using regexps

---

xml/security_ssh.xml

Certificate auth in OpenSSH is good for large scale deployments, and giving admins more control
Jira DOCTEAM-615
- SLE 12

add chapter to Security Guide on using OpenSSH certificate auth

---

xml/tuning_systemd_coredump.xml

Add new "infinity" coredump core size value for coredump.conf
Jira SLE-23932
- SLE 12

add new coredump core size value, infinity, in Tuning Guide

---

xml/utilities.xml

Tuning Guide, Utilities Chapter: Add note that mcelog tool is only available for x86-64.
* bsc#1201583
- SLE 12

fix bsc#1201583: mcelog is x86_64 only

---

xml/storage_lvm.xml

Empty <replaceable> triggered all styling to break. Removed it to make things look pretty again.
- SLE 12

Remove empty replaceable that broke all subsequent styling.

---

xml/storage_raid.xml

Fix this line using sudo that does't work  
```bash
sudo echo "CREATE names=yes" >> /etc/mdadm.conf
````
The command does not work because the redirection is performed by shell which does not have the permission to write to the file and not by sudo  
Using the following line fixes the issue
```bash
echo "CREATE names=yes" | sudo tee -a /etc/mdadm.conf
```
* bsc#...
* jsc#SLE-...
- SLE 12

fix sudo usage

---

xml/security_pcidss.xml

Publication page for the PCI-DSS Guide has moved recently. Adjust the link in the Security Guide accordingly.
- SLE 12

Security Guide: fix broken link to PCI-DSS

---

xml/security_cryptctl.xml

There is a JIRA request to make HA envinroment for cryptcl: https://jira.suse.com/browse/PED-1326
An crmsh-script was written to make a cluster setup easy.
This document enhancement describes the usage of this script and how to setup a HA environment for cryptctl.
* jsc#PED-1326
- SLE 12

Cryptctl ha cluster

---

xml/security_fips.xml

The correct pattern name for the FIPS configuration is patttern-base-fips instead of pattern-server-enterprise-fips
* bsc#1204981
- SLE 12

correction: pattern for FIPS modules in SLE 15 SP3

---

xml/adm_support.xml

Reported by ContentKing.
The reported link doesn't exist anymore and should be removed or replaced. This was the old link:
https://community.microfocus.com/t5/GroupWise-Tips-Information/Create-Your-Own-Supportconfig-Plugin/ta-p/1783289
A quick search revealed it is maybe here:
https://community.microfocus.com/img/gw/groupwise/w/groupwise/34308/create-your-own-supportconfig-plugin
To whom it may concern: please make sure to
* backport it to the other branches and
* if possible, apply the patch to the l10n directories
n/a
The following release contains the broken link. Maybe it would be feasible to distribute the load.
- SLE 12
- SLE Micro
When opening a PR, do *not* set the …

Remove broken link to Microfocus

---

xml/chrony.xml

There are 2 conflicting time sync systemd services, this update warns about not enabling both of them.
* bsc#1182393
- SLE 12

Added warning about conflicting time-sync services (bsc#1182393)

---

xml/libvirt_overview.xml

This change reworks the "Starting and stopping libvirtd" chapter. The traditional, monolithic libvirtd and how to control it are better described. The modular daemons are also introduced, along with details on how to enable them.
- SLE 12

vt-doc: Add documentation for libvirt modular daemons

---

xml/apps_evolution.xml

Add link to TID about how to fix behaviour in Evolution when moving a folder.
* jsc#PED-1582
- SLE 12

#PED-1582 mv folder evolution

---

xml/deployment_prep_zseries_prep_io_auto_config.xml

Add missing info about the DeviceAutoConfig parameter for IBM Z systems.
* bsc#1188066
- SLE 12

Depl. Guide: add info about deviceautoconfig (bsc#1188066)

---

xml/ulp.xml

Previously, the ULP docs referenced the livepatchable libraries by a mix of the package name and the .so files. This is confusing, as people reported libgcrypt being livepatchable when in fact it was not because openssl provides libcrypt.so. Hence, update the name to always mention the package name.
Fixes bsc#120636.
* bsc#120636.
SLE-15-SP4
- [ x] SLE 15 SP4/openSUSE Leap 15.4
- SLE 12
No. No backports are needed.

Change library names with the name of the packages.

---

xml/ay_partitioning.xml

XML configuration examples missed closing slash, this update fixes that
* bsc#1206069
- SLE 12

Added closing / to XML elements (bsc#1206096)

---

xml/virt_support.xml

This update will encourage customers to use large systems as a single VM.
fixes jsc#PED-2682
- SLE 12

Increased KVM_MAX_VCPUS to 1024 (jsc#PED-2682)

---

xml/ulp.xml

This PR updates the ULP documentation simplified by [Tomaz](https://github.com/SUSE/doc-sle/pull/1431) by answering his questions regarding it, such as:
* What is libpulp good for?
* Remove information about how to prepare a library to be livepatched,
as it is useless for the user.
* How to load a application with livepatch support;
* Where to get livepatches from.
* How to verify that a livepatch has been applied.
* How to check the internal libpulp message buffer.
- SLE 12

Improve ULP documentation 2

---

xml/uefi-httpboot-server.xml

Fix typos in two examples for setting up the DHCPv6 server for both PXE and HTTP boot,  https://documentation.suse.com/sled/15-SP4/html/SLED-all/cha-deployment-prep-uefi-httpboot.html#httpboot-dhcpv6-pxe-server
* bsc#1207494
* jsc#DOCTEAM-839
- SLE 12

Deployment: fix examples for uefi httpboot

---

xml/ulp.xml

The user space live patching documentation is rather technical and complicated for customers. This update tries to re-arrange information so that ULP is more acessible.
1. What id ULP good for? To keep system secure without application restart?
2. Are all SLE libraries compiled with the -fpatchable-function-entry GCC flag?
3. If yes, should a customer care about how to make library live-patchable?
4. libpulp is preloaded with `LD_PRELOAD=/usr/lib64/libpulp.so` followe by the application command?
5. Where do i get live patches from?
6. How to verify, for example, the patched syscall in glibc is installed ?
7. How to verify that EVERYTHING is using that new patched syscall since using the old version of the syscall would leave the security vulnerability open) ?
When opening a PR, check all …

Improve ULP documentation

---

xml/gpu_passthru.xml

Specifying the various ovmf firmware with the 'nvram' setting in /etc/libvirt/qemu.conf is deprecated in favor of firmware autoselection, which is already documented in the section "Installing UEFI support". Remove the old, outdated information.
Fix outdated section of the VT doc.
- SLE 12

vt-doc: Remove outdated information about the use of UEFI

---

xml/deployment_yast_installer.xml

Fixes the validity issue for openSUSE  by profiling the complete section for SLES/SLED.
Also fixed some typos and tweaked some entities. As OpenSCAP was mentioned for fixing
any remaining issues manually, added a link to the OpenSCAP paper, too.  
* jsc#SLE-25039
- SLE 12

STIG Hardening: minor fixes

---

xml/art_amd-sev.xml

Basic attestation was requested for SLE15 SP5 via jsc#PED-1472. This change adds the initial documenation.
Describe basic VM attestation process
* jsc#PED-1472
- SLE 12

sev-doc: Add section describing basic attestation process

---

xml/book_security.xml
xml/security_pcidss.xml

Based on feedback during SLE Doc Day and for better visibility of the Compliance-related topcis, it was agreed with the Cert team to add a new part about 'Compliance' to the Security Guide and move the relevant chapters there.   
* jsc-DOCTEAM-821
- SLE 12

Security Guide: add part about Compliance

---

xml/book_security.xml
xml/security_stig.xml

See title, as proposed by Ivan from the Sec Cert team. Do not merge before we have published the STIG paper, otherwise the link will be broken.
Related to:
* jsc#DOCTEAM-616
* jsc#DOCTEAM-821
- SLE 12

Security Guide: add pointer to STIG document

---

xml/rmt_install.xml

The original command would return an error, since Helm does not know where to get `rmt/rmt-helm-0.1` from.
Fix small (but significant) issues in the RMT installation docs with kubernetes.
- SLE 12

[RMT] Fix install command with helm

---

xml/selinux.xml

Add corrections suggested by @jsegitz: correct `restorecon`  command and remove (unneeded) `enforcing=0` boot parameter for permissive mode.
* bsc#1208592
* jsc#DOCTEAM-906
- SLE 12

Correct SELinux Documentation for 15 SP5/SP4 (bsc#1208592) 

---

xml/selinux.xml

Add corrections suggested by @jsegitz: correct `restorecon`  command and remove (unneeded) `enforcing=0` boot parameter for permissive mode.
* bsc#1208592
* jsc#DOCTEAM-906
- SLE 12

Correct SELinux Documentation for 15 SP[1-3] (bsc#1208592) 

---

xml/rmt_migrate_from_smt.xml

RMT does in fact support forwarding system registration data to SCC.
This PR fixes the RMT/SMT comparison table to fix that incorrect piece of information.
No.
- SLE 12

Fix RMT/SMT comparison table

---

xml/ay_security_settings.xml

SLE 15 SP4 OU2 supports system hardening with OpenSCAP. The required 'ssg-apply' utility however only gets found if you use the 'Basesystem' module from the media or enable online updates during installation. We did not take this into account in #1393.
* [bsc#...](https://bugzilla.suse.com/show_bug.cgi?id=1209400)
* [jsc#...](https://jira.suse.com/browse/DOCTEAM-937)
- SLE 12

AutoYaST -> OpenSCAP: Make sure ssg-apply gets found (BSC#1209400)

---

xml/ay_general_options.xml

AutoYaST Guide: Correcting the default value for blacklisting unused devices on IBM Z.
* bsc#1207426
* jsc#DOCTEAM-896
- SLE 12

AY Guide: Config Options - correct default value

---

xml/journalctl.xml

Adjust steps as requested in https://bugzilla.suse.com/show_bug.cgi?id=1196637#c28 after the software behavior has changed.
* bsc#1196637
* jsc#DOCTEAM-895
- SLE 12

Admin Guide: make systemd journal persistent

---

xml/adm_wbem.xml

The current command syntax for the sfcbd daemon , is not correct and needs a prefix of 
`sblim`
[https://jira.suse.com/browse/DOCTEAM-699](DOCTEAM-699)
- [ x] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
- [ x] SLE 15 SP4/openSUSE Leap 15.4
- [ x] SLE 15 SP3/openSUSE Leap 15.3
- [x ] SLE 15 SP2/openSUSE Leap 15.2
- [ x] SLE 15 SP1
- SLE 12
- [ x] SLE 12 SP5

added the correct service name

---

xml/libvirt_configuration_gui.xml
xml/libvirt_configuration_virsh.xml

SLE15 SP4 and newer do not require host-passthrough CPU type for VMs with greater than 4TB of memory. It's possible to use a custom CPU type and increase the CPU address bits if necessary with <maxphysaddr>.
- SLE 12

vt-doc: Remove note about large memory VMs requiring host-passthrough

---

DC-SLES-raspberry-pi
DEF-SLES-manuals
xml/MAIN.SLEDS.xml
xml/art_raspberry-pi.xml

We decided to move the Raspberry Pi Quick Start into the set. 
This has the following advantages:
- The Bugzilla information is inherited from the set and does not need to be updated individually for the Quick Start with each new SP.
- During localization hand-off, the Quick Start can be treated like any other deliverable (can be 'locdropped' with a DEF file).  
I also compared PDF and HTML builds before and after the changes: everything looks good. 
* see [internal locdrop howto](https://confluence.suse.com/display/documentation/Performing+a+loc+drop)
- SLE 12

Include Raspi Pi Quick in set

---

xml/ay_partitioning.xml

There are several problems with the current documentation of `<raid_options>`.
First of all, the identifiers for the different MD parities changed at SLE-15. That was originally unintended, we just realized now. To fix the situation, we implemented backwards compatibility for importing (reading) the profile. But exporting (cloning) the system will keep using the identifiers that were introduced at SLE-15. Pull request implementing the mentioned backwards compatibility - https://github.com/yast/yast-storage-ng/pull/1331.
The documentation stating which parities were valid for each RAID level was not correct. On the one hand, it was not very precise (for example, parity makes no sense for RAID0 or RAID1, but the original text seems to suggest it's ok). On the other hand, the criteria is …

AutoYaST: improve RAID documentation and fix wrong examples

---

xml/apps_firefox.xml
xml/apps_libreoffice.xml

Corrections from proofing drop implemented
- SLE 12

proofing corrections GNOME

---

xml/common_intro_available_doc.xml
xml/storage_lvm.xml
xml/storage_multipath.xml
xml/storage_nfs.xml

Integrate proofing corrections for the Storage Guide from proofing drop 2
- SLE 12

Storage Guide: integrate proofing corrections

---

xml/security_cryptofs.xml

The scope of this PR is to add Rage encryption software and tell users that this is the preferred method over GPG.   
[PED-1897](https://jira.suse.com/browse/PED-1897)
- SLE 12

PED1897-Add Rage encryption

---

xml/snapper.xml

Fix `snapper--iso list` to `snapper --iso list`
- SLE 12
Not sure if this should be backported.

Fix snapper command

---

xml/art_amd-sev.xml

Integrate proofing corrections for the AMD-SEV Guide from proofing drop 3.
- SLE 12

AMD-SEV: integrate proofing corrections

---

xml/libvirt_configuration_gui.xml
xml/libvirt_configuration_virsh.xml
xml/libvirt_overview.xml
xml/virt_support.xml

Integrate proofing corrections for the Virtualization Guide from proofing drop 3.
- SLE 12

Virtualization Guide: integrate proofing corrections

---

xml/rmt_rmt-cli.xml

Integrate proofing corrections for the RMT Guide from proofing drop 3.
- SLE 12

RMT Guide: integrate proofing corrections

---

xml/ay_running_system.xml

On an already installed system, AutoYaST ignores the `<partitioning>` section. Let's make this clear.
* [bsc#1211753](https://bugzilla.suse.com/show_bug.cgi?id=1211753)
- SLE 12

Indicate that <partitioning/> section is ignored on an installed system

---

xml/common_intro_support.xml
xml/tuning_how.xml
xml/tuning_sapconf.xml
xml/tuning_taskscheduler.xml
xml/utilities.xml

Integrate proofing corrections for the Tuning Guide from proofing drop 3.
- SLE 12

Tuning Guide: integrate proofing corrections

---

xml/art_amd-sev.xml
xml/art_minimal-vm.xml
xml/art_virtualization-best-practices.xml

Some articles were missing the license blurb as reported by Julia.
Adding them for
- Minimal VM Quick
- AMD-SEV
- Virt. Best Practices 
- SLE 12

Add license blurb

---

xml/security_ldap_install.xml

Prefix of sudo is missing in some commands for 389 Directory Server . Also xml format error rectified.
[DOCTEAM-1020](https://jira.suse.com/browse/DOCTEAM-1020)
- SLE 12

JSC#DOCTEAM-1020-adds sudo and format

---

xml/net_teaming.xml

The package is no longer in supported repos
* bsc#1212159
- SLE 12

Remove python-libteam package from docs

---

xml/ay_kernel_dumps.xml

this config option has been removed since kdump version 1.9.0 and yast-kdump version 4.6.1
* bsc#...
* jsc#...
- SLE 12

ay_kernel_dumps: remove KDUMP_COPY_KERNEL

---

xml/selinux.xml

SLE 12 supported versions do not have the statement for SUSE consulting. 
[DOCTEAM-661](https://jira.suse.com/browse/DOCTEAM-661)
- SLE 12

Security Guide-adds consulting statement

---

xml/security_ldap_ca.xml

Bz1212001: cherry-pick

---

xml/security_fips.xml

As discussed in a mail thread with the cert team.
- SLE 12

FIPS: add specific note for 15 SP5

---

xml/help_admin.xml

* manuals are only available online
* added info on release notes
* fixed contents of GNOME help center
Backport needed to
- [x ] SLE 15 SP4/openSUSE Leap 15.4

Fix for bsc#1213642

---

xml/art_modules.xml

fixes PED-4724
We need to update lifecycle information and module content on the Python 3 module description 
Backport required to

Added extensive information for Python 3 module (from RN)

---

xml/storage_nvmeof.xml
xml/utilities.xml

This PR relocates a note about `iostat` in multipath scenarios to the `utilities.xml` file of the Tuning guide. The change has been made based on [this Bugzilla comment](https://bugzilla.suse.com/show_bug.cgi?id=1194343#c8).
* JIRA: [DOCTEAM-665](https://jira.suse.com/browse/DOCTEAM-); there is a [duplicate](https://jira.suse.com/browse/DOCTEAM-1025) which will be closed along with merging this PR.
* [BSC#1194343](https://bugzilla.suse.com/show_bug.cgi?id=1194343)
- SLE 12

Relocate note on isostat in multipath setups

---

xml/ay_users_groups.xml
xml/deployment_yast_installer.xml
xml/yast2_userman.xml

I was asked to clarify that renaming the account is not supported. I did that for the Deployment guide, but as the YaST installer always names the root account 'root', there is no real harm. But with AutoYaST and 'yast2 users' you can actually rename the account, so I fixed the other guides as well.
@lvicoun, please check b95ca63f43422bb282af5b8c6aed09735be248bc
@tbazant please check d951c0c590798f57afb9bec0c4c3d527f8174900
@dariavladykina please check everything for language and style.
* [PED-3897](https://jira.suse.com/browse/PED-3897)
- SLE 12
When opening a PR, do *not* set the following …

Dont rename the root account (PED-3897)

---

xml/virt_support.xml

QEMU support statement is clearer now
- [ x SLE 15 SP1
- SLE 12

Updated QEMU support statement

---

xml/grub2.xml
xml/systemd.xml
xml/troubleshooting.xml

Fixing grub rescue target instructions
* bsc#1193363
- SLE 12

Changes to the grub edit mode (bsc#1193363)

---

xml/art_virtualization-best-practices.xml

multipath iSCSI update to virt best practices
* bsc#1210642
- SLE 12

Virt Best Practices: add scsi persistent reservation on multipathed

---

xml/ay_partitioning.xml

As requested in the Jira entries mentioned below, https://github.com/yast/yast-storage-ng/pull/1355 implements support for the new `crypt_method` LUKS2 (well, it actually makes that support official) and adds support for four new LUKS-related AutoYaST elements.
The usage of that new method and, especially, the way the other new elements can impact the amount of RAM used during installation.
This pull request adds a first draft documenting all that. Feel free to reorganize the information as needed. But please keep some note somewhere about the RAM implications since the new settings are highly demanded by several users and partners, but they should be aware of the implications.
* [jsc#PED-3878](https://jira.suse.com/browse/PED-3878)
* [jsc#PED-5518](https://jira.suse.com/browse/PED-5518) …

Initial draft for new LUKS-related partitioning elements

---

xml/libvirt_overview.xml

Along with some wording improvements, prefer the use of 'daemon' over 'driver' when referring to modular daemons.
- SLE 12

vt-doc: Improve libvirt daemons description

---

xml/libvirt_overview.xml

Change the libvirt daemons chapter to reflect modular daemons are now enabled by default. This change is based on top of PR#1596 and is only valid for SLE15 SP6 and newer. The change in PR#1596 should also be applied to SLE15 SP4 and SP5.
* jsc#PED-4303
- SLE 12

Switch modular daemons

---

xml/net_basic.xml

Quagga tool is no longer maintained, better replace it with FRR
- SLE 12

Removed Quagga + advised FRR

---

xml/file_management.xml

Remove /usr as a separate FS
[BZ](https://bugzilla.suse.com/show_bug.cgi?id=1212851)
- SLE 12

[WIP]: removes /usr as a separate fs

---

xml/apparmor_profiles.xml
xml/apparmor_profiles_man.xml
xml/apparmor_whatimmunize.xml
xml/audit_components.xml
xml/audit_scenarios.xml
xml/audit_setup.xml
xml/security_firewall.xml
xml/security_kerberos.xml
xml/security_ldap_docker_container.xml
xml/security_ldap_migrate_test.xml
xml/security_ldap_replication.xml
xml/security_pam.xml
xml/security_ssh.xml

The scope of this PR is to add the tag <?dbfo keep-together=always?> to <screen> to avoid breakage of a diagram or command outputs . 
* bsc#...
* jsc#...
- SLE 12

adds <?dbfo keep-together=always?> to screen

---

xml/apparmor_profiles.xml

Correct the syntax issue which is creating translation issues.
* bsc#...
* jsc#...
- SLE 12

corrected syntax

---

xml/security_firewall.xml

Removes redundant statement and cherry-pick to maintenance/sp2
[DOCTEAM-898](https://jira.suse.com/browse/DOCTEAM-898)
- SLE 12

removes redundant statement

---

xml/rmt_rmt-cli.xml

A new command `rmt-cli clean packages` was introduced. This update describes its usage.
* bsc#1220226
* jsc#DOCTEAM-1294
- SLE 12

Added 'clean packages' command description

---

xml/tuning_memory.xml

The variable has a _ at the end, see
strings /lib/ld-2.31.so | grep MMAP_THRE
MALLOC_MMAP_THRESHOLD_
or https://man7.org/linux/man-pages/man3/mallopt.3.html
Document MALLOC_MMAP_THRESHOLD_ (fix the environment variable name).
* bsc#...
* jsc#...
- SLE 12

Update tuning_memory.xml -use MALLOC_MMAP_THRESHOLD_

---

xml/security_pam.xml

Replaces ldap wih sssd
[BZ1211727](https://bugzilla.suse.com/show_bug.cgi?id=1211727)
- SLE 12

[WIP]:BZ1211727:adds sssd as auth example

---

xml/adm_support.xml
xml/ay_kernel_dumps.xml
xml/kernel_modules.xml
xml/klp.xml
xml/product-entities.ent
xml/security_spectre_meltdown_checker.xml
xml/selinux.xml
xml/slemicro_pcp.xml
xml/tuning_kexec.xml
xml/tuning_multikernel.xml
xml/tuning_taskscheduler.xml
xml/utilities.xml
xml/xen2kvm.xml

Update code examples etc. to SLE 15 SP6 kernel version. Affects the following guides:
- Admin Guide
- AY Guide
- Security & Hardening Guide
- Tuning Guide
- Virtualization Guide
* jsc#PED-4595
No backporting!

update kernel versions (recent)

---

xml/rmt_migrate_from_smt.xml

RMT now supports also CentOS/RHEL distros so changed false to true in the table. Also changed Expanded Support references to SUSE Liberty Linux as that's the official product name
RMT now support managing RHEL/CentOS 7 repos
* bsc#...
* jsc#...
- SLE 12

Renamed expaned to Liberty and update RMT support for EL 7

---

xml/ay_grub_bootloader.xml
xml/ay_partitioning.xml
xml/ay_running_system.xml
xml/common_intro_available_doc.xml
xml/common_intro_convention.xml
xml/deployment_yast_installer.xml

Integrate proofing corrections for the AutoYAST Guide from proofing drop 1.
- SLE 12

AutoYAST Guide: integrate proofing corrections

---

xml/ay_users_groups.xml
xml/common_intro_available_doc.xml
xml/common_intro_convention.xml
xml/deployment_prep_aarch64_raspi.xml
xml/deployment_yast_installer.xml
xml/yast2_userman.xml

Integrate proofing corrections for the Deployment Guide from proofing drop 1.
- SLE 12

Deployment Guide: integrate proofing corrections

---

xml/common_intro_available_doc.xml
xml/common_intro_convention.xml
xml/sle_update_finish.xml
xml/sle_update_preparation.xml

Integrate proofing corrections for the Upgrade Guide from proofing drop 1.
- SLE 12

Upgrade Guide: integrate proofing corrections

---

xml/art_installation-sleds.xml
xml/book_autoyast.xml
xml/book_deployment.xml
xml/book_upgrade.xml

Metadata: add revhistory for 4 deliverables that will be handed over to localization with locdrop 1:
- Install Quick
- Deployment Guide
- Upgrade Guide
- AutoYasT Guide
[Link to internal page](https://confluence.suse.com/display/documentation/Adding+metadata+to+all+SUSE+documentation)

metadata: add revhistory for 4 deliverables (locdrop 1)

---

xml/deployment_yast_installer.xml

YaST cannot create a partition proposal for FBA disks.
* [bsc#1209059](https://bugzilla.suse.com/show_bug.cgi?id=1209059)
- SLE 12

bsc#1209059: note for DASD (IBM Z)

---

.github/PULL_REQUEST_TEMPLATE.md

Removes the SLE12-SP4  and SLE15-SP1 checkboxs (as its no longer supported) in the PR template
* bsc#...
* jsc#...
- SLE 12

removes sle12-sp4 checkbox

---

xml/art_modules.xml
xml/phrases-decl.ent

This adds the confidential computing module to the Modules & Extensions guides as well as the Deployment and Installation Quickstart guides.
* [jsc#PED-8169](https://jira.suse.com/browse/PED-8169)
- SLE 12

Confidential computing module ped 8169

---

xml/adm_sudo.xml
xml/system_repair.xml
xml/systemd.xml

Integrate proofing corrections for the Administration Guide from proofing drop 2.
- SLE 12

Administration Guide: Integrate proofing corrections

---

xml/art_raspberry-pi.xml

Add final fixes for the Raspberry Pi Quick Start.
- SLE 12

Raspberry Pi QS: final fixes

---

xml/security_ssh.xml

security_ssh.xml - sshd_config was named sshd_configuration in the sftp section
Apologies for the extra branch. Would I've spotted this earlier I would have created a more general branch. 
Anyway: another bug in naming: sshd_config was named sshd_configuration in the section about sftp (22.16.2).
Not that I know off.
- SLE 12

security_ssh.xml - sshd_config was named sshd_configuration

---

xml/qemu_monitor.xml
xml/xen_xmtoxl.xml

Removes the word "officially"
[DOCTEAM-1375](https://jira.suse.com/browse/DOCTEAM-1375)
- SLE 12

[WIP]DOCTEAM-1375:removes officially

---

xml/deployment_images_ignition.xml

`typeGuid` and `wipeTable` have been reversed

fix JSON and YAML syntax

---

xml/deployment_boot_parameters.xml
xml/deployment_prep_aarch64.xml
xml/deployment_prep_aarch64_choose.xml
xml/virt_support.xml

Updated the ARM entity in Deployment Guide from `arm64` (resolves to ARM AArch64) to the correct `aarch64` (resolves to AArch64).

Updated arm entity in Deployment Guide

---

xml/selinux.xml

Correct the wrong repo link
[DOCTEAM-1493](https://jira.suse.com/browse/DOCTEAM-1493)
- SLE 12

[WIP]DOCTEAM-1493: corrects wrong repo link

---

xml/security_aide.xml

AIDE project moved to GitHub some time ago.
* https://aide.github.io/
* https://github.com/aide/aide
Update all documentation to point to the current AIDE project website.
None that I'm aware of.
- SLE 12

Update security_aide.xml - fix AIDE project url

---

xml/security_firewall.xml

Document nftables as the default backend for firewalld
[DOCTEAM-1225](https://jira.suse.com/browse/DOCTEAM-1225)
- SLE 12

DOCTEAM-1225: adds nftables section

---

xml/book_tuning.xml
xml/product-entities.ent
xml/tuning_tuned.xml

Provide decent documentation on the [TuneD](https://tuned-project.org) application and associated utilities, in the context of SLES. The requirement for documentation is described in the [Bugzilla#1093289](https://bugzilla.suse.com/show_bug.cgi?id=1093289). The [source code](https://github.com/redhat-performance/tuned) for the application is available on GitHub.
* [bsc#1093289](https://bugzilla.suse.com/show_bug.cgi?id=1093289)
* [jsc#DOCTEAM-96](https://jira.suse.com/browse/DOCTEAM-96)
- SLE 12

TuneD documentation

---

xml/storage_mdadm-resize.xml

With mdadm 3.3 or newer, partitions can be hot-replaced with new disks so that the array remains fault-tolerant through the replacement process. This could be a useful alternative to note in the resizing guide.
- SLE 12

Document hot-replacement to resize mdadm partitions

---

xml/libvirt_guest_installation.xml

Fix PXE enablement (there is no Network PXE but the NIC)
* bsc#...
* https://jira.suse.com/browse/DOCTEAM-1619
- SLE 12

Update libvirt_guest_installation.xml (PXE part))

---

xml/art_amd-sev.xml

Fixing bug#1232762 and other related bugs in the ovmf package requires removing SEV support from ovmf-x86_64-4m-{code,vars}.bin and ovmf-x86_64-{code,vars}.bin. New firmwares specificly for SEV, SEV-ES, and SEV-SNP have been introduced. Update the documentation to use the new SEV-specific firmware.
* bsc#1232762
- SLE 12

sev-doc: Fix ovmf firmware paths

---

xml/rmt_install.xml

[DOCTEAM-1627](https://jira.suse.com/browse/DOCTEAM-1627)
- SLE 12

DOCTEAM-1627: set enabled option to false in the yaml example

---

xml/ay_partitioning.xml

Changing zFCP disk disk in AY.
* bsc#...
* jsc#...
- SLE 12

Fix for BSC#1218169.

---

xml/klp.xml
xml/product-entities.ent

Update kernel version number for SLE 15 SP7 (checked against internal Snapshot-202412-2.1). Also checked the output of `klp -v patches` to update the string in the KLP chapter.
Nope.
No backporting!

bump kernel version number (SLE 15 SP7)

---

xml/utilities.xml

Clarify how to interpret and act when `%vmeff` value exceeds 100% as part of `sar -B` report, because it doesn't make sense under normal circumstances that the kernel reclaims more virtual memory pages than it scans.
* A note should appear at the end of the section https://susedoc.github.io/doc-sle/main/html/SLES-tuning/cha-util.html#sec-util-multi-sar-report-paging
* bsc#...https://bugzilla.suse.com/show_bug.cgi?id=1218839
* jsc#...https://jira.suse.com/browse/DOCTEAM-1252
- SLE 12

Additional clarification about %vmeff exceeding 100% in newer kernels

---

xml/libvirt_configuration_virsh.xml

Starting with libvirt 10.10.0, an iommu and ioapic are configured automatically if needed, e.g. when configuring a VM with >255 vCPUs. For SLE15 SP7 and newer, remove the note about needing to add the configuration manually.
- SLE 12

vt-doc: Remove note about exceeding 255 vCPUs

---

xml/ulp.xml

(note: I am not able to compile the docs, there seems to be something wrong with the shipped openSUSE environment).
This update the documentation about userspace livepatching with the following information:
1- Remove the paragraph stating that on Micro new processes will run
unpatched software.  This is not true anymore since libpulp 0.3.8.
2- State that ulp is available on x86_64 and powerpc64le.
3- State that for openssl-3 we have openssl-3-livepatches.
* jsc#PED-12221
- SLE 12

Update docs about userspace livepatching

---

xml/net_dhcp.xml

Section 40.3.2 talks about a security patch for isc , since we are replacing with kea , is this section still valid? 
https://documentation.suse.com/sles/15-SP6/html/SLES-all/cha-dhcp.html#sec-dhcp-server
[PED-11693](https://jira.suse.com/browse/PED-11693)
- SLE 12

PED-11693: adds note for kea server

---

xml/ay_rules_classes.xml

correcture of the "hostname" attribute
I testing the previous Value "host name" on three different suse/sles installations, but only the corrected "hostname" works. I think thats a typo or translation error.
With the actual "host name"-Value, it's not possible to use the Value for working autoyast-Installations.
* bsc#...
* jsc#...

fix hostname-Attribute for autoyast Rules

---

xml/art-kubevirt.xml
xml/art-nvidia-vgpu.xml
xml/art_amd-sev.xml
xml/art_installation-sleds.xml
xml/art_modules.xml
xml/art_raspberry-pi.xml
xml/art_virtualization-best-practices.xml
xml/book_administration.xml
xml/book_autoyast.xml
xml/book_deployment.xml
xml/book_gnome-user.xml
xml/book_rmt.xml
xml/book_security.xml
xml/book_storage.xml
xml/book_tuning.xml
xml/book_upgrade.xml
xml/book_virtualization.xml

Set date in revision history to FCS date for 15 SP7 and keep initial entry as agreed with @lvicoun.

Revision History: initial entry for FCS of 15 SP7

---

xml/ay_custom_user_scripts.xml

Contrary to what was described, the init-scripts section must not be placed in the <script> part. This will cause autoyast to abort with an error message, and all validation methods will not accept this tag in the previously described location. The documentation has been corrected accordingly in both of these critical locations.
* bsc#...
* jsc#...
- [ x ] SLE 15 next/openSUSE Leap next *(current `main`, no backport necessary)*
- [ x ] SLE 15 SP6/openSUSE Leap 15.6
- [ x ] SLE 15 SP5/openSUSE Leap 15.5
- SLE 12

correction of init-scripts handling

---

xml/art_modules.xml
xml/ay_configuration_management.xml
xml/ay_software.xml
xml/klp.xml
xml/phrases-decl.ent
xml/planning.xml
xml/product-entities.ent
xml/rmt_migrate_from_smt.xml
xml/sle_update_background.xml
xml/sle_update_offline.xml
xml/sle_update_online.xml
xml/sle_update_upgrading.xml
xml/software_management.xml

With the upcoming version 5.1, **SUSE Manager** will be renamed to **SUSE Multi-Linux Manager** (already released SuMa versions keep their name and their documentation URLs).
The SLE 15 SP7 documentation needs to reflect the product name change. 
Also, the 'generic' URL `https://documentation.suse.com/suma` (which always redirects to the docs for the latest released SuMa version) will be replaced with `https://documentation.suse.com/multi-linux-manager` moving forward.
https://jira.suse.com/browse/DOCTEAM-1754
15 SP7 only - NO backports to older versions!

Product renaming (SuMa -> SMLM)

---

xml/art-nvidia-vgpu.xml

Document the fix for the following issue: NVIDIA vGPU driver v16.2 failed to be installed on SLE 15 SP7 KVM host
* https://bugzilla.suse.com/show_bug.cgi?id=1239449
* https://jira.suse.com/browse/DOCTEAM-1768
- SLE 12

Doc Bug Fix: NVIDIA vGPU driver v16.2 failed to be installed on SLE 15 SP7 KVM host

---

xml/sle_update_preparation.xml

After upgrading from SLE 12 to SLE 15, zipl fails when enabling secure boot as there is no signature for the old kernel. This can be fixed with `SUSE_SECURE_BOOT=auto` in /etc/default/grub.
* [bsc#1204547](https://bugzilla.suse.com/show_bug.cgi?id=1204547)
- SLE 12

Add note on old kernels in /boot/zipl (BSC#1204547)

---

xml/ay_custom_user_scripts.xml

Fix the location of the `init-scripts` in the AutoYaST documentation. It partially reverts #1819 which assumes that the `init-scripts` are out of the `scripts` section. If that's the case, it is a bug in AutoYaST, not in the documentation.
@eeagle please, do you have more info about the original problem? Thank you!
* #1819
* [bsc#1243421](https://bugzilla.suse.com/show_bug.cgi?id=1243421)
NOTE: I marked the same versions than the original PR.
- SLE 12

Correct the location of the init-scripts section

---

xml/suse_l10n.xml

Description
Removing duplicated product entity
- SLE 12

rm duplicate product entity
